import type {UiV2Context,UiV2Env} from "./context";
import {esc,renderUiV2Shell,uiV2Html} from "./shell";

type AuditRow={id:number;occurred_at:string;actor_display_name:string|null;action:string;entity_type:string;entity_id:string|null;source:string|null;old_values:string|null;new_values:string|null;metadata:string|null};
type SettingRow={key:string;value:string};

const auditCss=`<style>
.audit-toolbar{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:13px;margin-bottom:11px}.audit-search{width:100%;padding:12px 14px;border:1px solid var(--ui-line-strong);border-radius:11px;background:var(--ui-surface-2);color:var(--ui-text);font-size:.9rem}.audit-search:focus{outline:2px solid color-mix(in srgb,var(--ui-hover) 40%,transparent);border-color:var(--ui-hover)}.audit-count{color:var(--ui-muted);font-size:.75rem;white-space:nowrap}.audit-list{border:1px solid var(--ui-line);border-radius:14px;background:var(--ui-surface-2);overflow:hidden}.audit-event{border-bottom:1px solid var(--ui-line)}.audit-event:last-child{border-bottom:0}.audit-event[hidden]{display:none}.audit-summary{display:grid;grid-template-columns:180px minmax(180px,.8fr) minmax(220px,1fr) 24px;gap:15px;align-items:center;padding:15px 17px;cursor:pointer;list-style:none}.audit-summary::-webkit-details-marker{display:none}.audit-summary:hover{background:color-mix(in srgb,var(--ui-hover) 5%,var(--ui-surface-2))}.audit-time{color:var(--ui-muted);font-size:.72rem}.audit-action strong,.audit-action span{display:block}.audit-action strong{font-size:.8rem}.audit-action span{margin-top:4px;color:var(--ui-muted);font-size:.68rem}.audit-meta{color:var(--ui-muted);font-size:.72rem;line-height:1.45}.audit-arrow{color:var(--ui-navigation);font-size:1rem;transition:transform .15s ease}.audit-event[open] .audit-arrow{transform:rotate(90deg)}.audit-detail{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;padding:0 17px 16px}.audit-json{min-width:0;padding:11px;border:1px solid var(--ui-line);border-radius:10px;background:var(--ui-surface-3)}.audit-json span{display:block;margin-bottom:7px;color:var(--ui-accent);font-size:.6rem;font-weight:900;letter-spacing:.06em;text-transform:uppercase}.audit-json pre{margin:0;color:var(--ui-secondary);font:600 .64rem/1.5 ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap;overflow-wrap:anywhere}.audit-empty{padding:28px;color:var(--ui-muted);text-align:center}@media(max-width:780px){.audit-summary{grid-template-columns:1fr 24px;gap:6px}.audit-time,.audit-action,.audit-meta{grid-column:1}.audit-arrow{grid-column:2;grid-row:1/4}.audit-detail{grid-template-columns:1fr}}@media(max-width:520px){.audit-toolbar{grid-template-columns:1fr}.audit-count{white-space:normal}}
</style>`;

const pretty=(value:string)=>value.replaceAll("."," ").replaceAll("_"," ").replace(/\b\w/g,character=>character.toUpperCase());
const parseJson=(value:string|null)=>{if(!value)return null;try{return JSON.stringify(JSON.parse(value),null,2)}catch{return value}};
const localeFor=(value:string)=>{const setting=value.toLowerCase();if(setting.includes("uk")||setting.includes("gb")||setting.includes("dd/mm"))return "en-GB";if(setting.includes("us")||setting.includes("mm/dd"))return "en-US";return value.includes("-")?value:"en-GB"};

export async function renderUiV2Audit(env:UiV2Env,context:UiV2Context){
  if(!context.user.canViewAudit)return uiV2Html(renderUiV2Shell(context,{eyebrow:"Security",title:"Audit Log",description:"You do not have permission to view the audit history.",body:"",activePath:"/ui-v2/audit"}),403);
  const [result,settingResult]=await Promise.all([
    env.DB.prepare("SELECT id,occurred_at,actor_display_name,action,entity_type,entity_id,source,old_values,new_values,metadata FROM audit_log ORDER BY occurred_at DESC,id DESC LIMIT 250").all<AuditRow>(),
    env.DB.prepare("SELECT key,value FROM settings WHERE key IN ('date_format','alliance_timezone')").all<SettingRow>()
  ]);
  const rows=result.results??[],settings=Object.fromEntries((settingResult.results??[]).map(row=>[row.key,row.value])),locale=localeFor(settings.date_format||"en-GB"),timezone=settings.alliance_timezone||"Europe/London";
  const events=rows.map(row=>{
    const entity=[pretty(row.entity_type),row.entity_id?`#${row.entity_id}`:"",row.source?`via ${row.source}`:""].filter(Boolean).join(" · ");
    const oldValue=parseJson(row.old_values),newValue=parseJson(row.new_values),metadata=parseJson(row.metadata);
    const detail=[oldValue?`<div class="audit-json"><span>Before</span><pre>${esc(oldValue)}</pre></div>`:"",newValue?`<div class="audit-json"><span>After</span><pre>${esc(newValue)}</pre></div>`:"",metadata?`<div class="audit-json"><span>Context</span><pre>${esc(metadata)}</pre></div>`:""].filter(Boolean).join("");
    const search=`${row.action} ${pretty(row.action)} ${row.actor_display_name||"System"} ${row.entity_type} ${row.entity_id||""} ${row.source||""} ${row.old_values||""} ${row.new_values||""} ${row.metadata||""}`.toLowerCase();
    return `<details class="audit-event" data-audit-event data-search="${esc(search)}"><summary class="audit-summary"><time class="audit-time" datetime="${esc(row.occurred_at)}">${esc(row.occurred_at)}</time><div class="audit-action"><strong>${esc(pretty(row.action))}</strong><span>${esc(row.actor_display_name||"System")}</span></div><div class="audit-meta">${esc(entity)}</div><span class="audit-arrow">›</span></summary>${detail?`<div class="audit-detail">${detail}</div>`:""}</details>`;
  }).join("");
  const script=`<script>(()=>{const locale=${JSON.stringify(locale)},timezone=${JSON.stringify(timezone)};document.querySelectorAll('.audit-time').forEach(element=>{let raw=element.getAttribute('datetime')||'';if(raw&&!/[zZ]|[+-]\\d\\d:?\\d\\d$/.test(raw))raw=raw.replace(' ','T')+'Z';const date=new Date(raw);if(Number.isNaN(date.getTime()))return;try{element.textContent=new Intl.DateTimeFormat(locale,{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false,timeZone:timezone}).format(date)}catch{element.textContent=new Intl.DateTimeFormat('en-GB',{dateStyle:'short',timeStyle:'medium',hour12:false}).format(date)}});const input=document.querySelector('[data-audit-search]'),count=document.querySelector('[data-audit-count]'),events=[...document.querySelectorAll('[data-audit-event]')];input?.addEventListener('input',()=>{const query=input.value.trim().toLowerCase();let shown=0;events.forEach(event=>{const visible=!query||(event.dataset.search||'').includes(query);event.hidden=!visible;if(visible)shown++});if(count)count.textContent=shown+(query?' matching':' most recent')+' event'+(shown===1?'':'s')})})();</script>`;
  const body=`${auditCss}<div class="audit-toolbar"><input class="audit-search" type="search" autocomplete="off" placeholder="Search action, person, item or source" data-audit-search><span class="audit-count" data-audit-count>${rows.length} most recent event${rows.length===1?"":"s"}</span></div><div class="audit-list">${events||'<div class="audit-empty">No audit events have been recorded yet.</div>'}</div>${script}`;
  return uiV2Html(renderUiV2Shell(context,{eyebrow:"Security",title:"Audit Log",description:"Search the history of meaningful platform changes. Select an event to inspect its recorded details.",body,activePath:"/ui-v2/audit",back:{href:"/ui-v2/security",label:"Security & Access"}}));
}
