import type {UiV2Context,UiV2Env} from "./context";
import {esc,renderUiV2Shell,uiV2Html} from "./shell";

type CountRow={total:number};
type GuildRow={guild_name:string};
type AwayRow={display_name:string};

const londonToday=()=>{
  const parts=new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());
  const part=(type:string)=>parts.find(item=>item.type===type)?.value||"";
  return `${part("year")}-${part("month")}-${part("day")}`;
};

const icon=(name:"players"|"security"|"settings"|"away"|"backup")=>{
  const paths={
    players:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',
    security:'<path d="M12 3l8 4v5c0 5-3.4 8.5-8 9-4.6-.5-8-4-8-9V7l8-4z"/><path d="M9 12l2 2 4-4"/>',
    settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l-2.83 2.83A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1.4 1.6h-3.2A1.7 1.7 0 0 0 9 19.4a1.7 1.7 0 0 0-1.91.31l-2.83-2.83A1.7 1.7 0 0 0 4.6 15 1.7 1.7 0 0 0 3 13.6v-3.2A1.7 1.7 0 0 0 4.6 9a1.7 1.7 0 0 0-.34-1.88l2.83-2.83A1.7 1.7 0 0 0 9 4.6 1.7 1.7 0 0 0 10.4 3h3.2A1.7 1.7 0 0 0 15 4.6a1.7 1.7 0 0 0 1.91-.31l2.83 2.83A1.7 1.7 0 0 0 19.4 9a1.7 1.7 0 0 0 1.6 1.4v3.2a1.7 1.7 0 0 0-1.6 1.4z"/>',
    away:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18M9 16l2 2 4-4"/>',
    backup:'<path d="M12 3v12M7 10l5 5 5-5M5 21h14a2 2 0 0 0 2-2v-2M3 17v2a2 2 0 0 0 2 2"/>'
  };
  return `<span class="console-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${paths[name]}</svg></span>`;
};

const dashboardCss=`<style>
.preview-note{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:18px;padding:11px 14px;border:1px solid color-mix(in srgb,var(--ui-accent) 35%,var(--ui-line));border-radius:11px;background:color-mix(in srgb,var(--ui-accent) 7%,var(--ui-surface-2));color:var(--ui-soft);font-size:.76rem;line-height:1.45}.preview-note strong{color:var(--ui-accent)}.sample-badge{flex:0 0 auto;padding:5px 8px;border:1px solid var(--ui-line-strong);border-radius:999px;color:var(--ui-secondary);font-size:.6rem;font-weight:900;letter-spacing:.06em;text-transform:uppercase}
.snapshot-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px;margin-bottom:22px}.snapshot-card{padding:15px 16px;border:1px solid var(--ui-line);border-radius:13px;background:var(--ui-surface-2)}.snapshot-card span,.snapshot-card strong,.snapshot-card small{display:block}.snapshot-card span{color:var(--ui-muted);font-size:.65rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase}.snapshot-card strong{margin-top:7px;font-size:1.42rem;line-height:1}.snapshot-card small{margin-top:6px;color:var(--ui-secondary);font-size:.67rem}.snapshot-card .positive{color:var(--ui-success)}
.dashboard-section{margin-top:23px}.section-head{display:flex;align-items:end;justify-content:space-between;gap:18px;margin-bottom:11px}.section-head h2{margin:0;font-size:1.12rem}.section-head p{margin:4px 0 0;color:var(--ui-muted);font-size:.78rem}.section-link{color:var(--ui-navigation);font-size:.7rem;font-weight:900;text-decoration:none}.section-link:hover{color:var(--ui-hover)}
.life-grid{display:grid;grid-template-columns:1.35fr 1fr;gap:13px}.side-stack{display:grid;gap:13px}.dashboard-card{padding:18px;border:1px solid var(--ui-line);border-radius:14px;background:var(--ui-surface-2);min-width:0}.dashboard-card h3{margin:0;font-size:1rem}.card-top{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.card-type{color:var(--ui-accent);font-size:.63rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.news-card{min-height:100%}.news-feature{padding:18px;border:1px solid var(--ui-line);border-radius:12px;background:linear-gradient(135deg,color-mix(in srgb,var(--ui-accent) 12%,var(--ui-surface-3)),var(--ui-surface-3))}.news-feature .news-date{color:var(--ui-accent);font-size:.65rem;font-weight:900;text-transform:uppercase}.news-feature h3{margin:8px 0 8px;font-size:1.28rem}.news-feature p{margin:0;color:var(--ui-soft);font-size:.83rem;line-height:1.55}.news-list{display:grid;margin-top:11px}.news-row{display:grid;grid-template-columns:72px minmax(0,1fr);gap:11px;padding:11px 2px;border-top:1px solid var(--ui-line)}.news-row time{color:var(--ui-muted);font-size:.67rem}.news-row strong{font-size:.78rem;line-height:1.35}
.event-list,.people-list{display:grid}.event-row,.person-row{display:grid;grid-template-columns:50px minmax(0,1fr) auto;align-items:center;gap:11px;padding:10px 0;border-top:1px solid var(--ui-line)}.event-row:first-child,.person-row:first-child{border-top:0;padding-top:0}.event-row:last-child,.person-row:last-child{padding-bottom:0}.date-tile{display:grid;place-items:center;min-height:45px;border:1px solid var(--ui-line-strong);border-radius:9px;background:var(--ui-surface-3);text-align:center}.date-tile strong,.date-tile span{display:block}.date-tile strong{font-size:.86rem}.date-tile span{color:var(--ui-muted);font-size:.55rem;font-weight:900;text-transform:uppercase}.row-copy strong,.row-copy span{display:block}.row-copy strong{font-size:.79rem}.row-copy span{margin-top:3px;color:var(--ui-muted);font-size:.66rem}.row-state{padding:5px 7px;border-radius:999px;background:var(--ui-surface-3);color:var(--ui-secondary);font-size:.57rem;font-weight:900;white-space:nowrap}.row-state.warning{color:var(--ui-warning)}.row-state.success{color:var(--ui-success)}
.game-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px}.game-card{position:relative;overflow:hidden}.game-card::before{position:absolute;top:0;right:0;left:0;height:3px;background:var(--ui-accent);content:""}.game-card h3{margin:5px 0 2px}.game-subtitle{color:var(--ui-muted);font-size:.68rem}.game-score{display:flex;align-items:end;justify-content:space-between;gap:12px;margin:18px 0 12px}.game-score strong{font-size:1.55rem;line-height:1}.game-score span{color:var(--ui-muted);font-size:.66rem;text-align:right}.progress{height:8px;border-radius:999px;background:var(--ui-surface-3);overflow:hidden}.progress>span{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,var(--ui-button),var(--ui-accent))}.game-facts{display:grid;gap:7px;margin-top:14px}.game-fact{display:flex;justify-content:space-between;gap:12px;padding-top:7px;border-top:1px solid var(--ui-line);font-size:.68rem}.game-fact span{color:var(--ui-muted)}.game-fact strong{text-align:right}.game-action{display:inline-flex;margin-top:14px;color:var(--ui-navigation);font-size:.69rem;font-weight:900;text-decoration:none}.game-action:hover{color:var(--ui-hover)}
.manage-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px}.manage-card{position:relative;display:block;min-height:160px;padding:16px;border:1px solid var(--ui-line);border-radius:13px;background:var(--ui-surface-2);color:inherit;text-decoration:none;transition:border-color .15s ease,box-shadow .15s ease,transform .15s ease}.manage-card:hover{border-color:var(--ui-hover);box-shadow:0 0 18px color-mix(in srgb,var(--ui-hover) 11%,transparent);transform:translateY(-1px)}.console-icon{display:grid;width:38px;height:38px;place-items:center;border:1px solid var(--ui-line-strong);border-radius:10px;background:var(--ui-surface-3);color:var(--ui-accent)}.console-icon svg{width:20px;height:20px}.manage-card h3{margin:12px 0 5px;font-size:.9rem}.manage-card p{margin:0;color:var(--ui-muted);font-size:.7rem;line-height:1.45}.manage-arrow{position:absolute;right:14px;top:13px;color:var(--ui-navigation)}.attention{display:inline-flex;margin-top:10px;padding:5px 7px;border-radius:999px;background:color-mix(in srgb,var(--ui-warning) 11%,var(--ui-surface-3));color:var(--ui-warning);font-size:.58rem;font-weight:900}
@media(max-width:950px){.snapshot-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.life-grid{grid-template-columns:1fr}.side-stack{grid-template-columns:1fr 1fr}.game-grid{grid-template-columns:1fr 1fr}.game-grid .game-card:last-child{grid-column:1/-1}.manage-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:650px){.preview-note,.section-head{display:block}.sample-badge{display:inline-flex;margin-top:8px}.snapshot-grid,.side-stack,.game-grid,.manage-grid{grid-template-columns:1fr}.game-grid .game-card:last-child{grid-column:auto}.snapshot-card strong{font-size:1.25rem}.event-row,.person-row{grid-template-columns:46px minmax(0,1fr)}.row-state{grid-column:2;width:max-content}.news-row{grid-template-columns:62px minmax(0,1fr)}}
</style>`;

function managementCards(context:UiV2Context,pending:number){
  const cards:string[]=[];
  if(context.user.canManagePlayers)cards.push(`<a class="manage-card" href="/ui-v2/players">${icon("players")}<span class="manage-arrow">→</span><h3>Players</h3><p>Roster, profiles, membership, birthdays and leadership notes.</p>${pending?`<span class="attention">${pending} waiting</span>`:""}</a>`);
  if(context.user.canManageAway)cards.push(`<a class="manage-card" href="/ui-v2/away">${icon("away")}<span class="manage-arrow">→</span><h3>Away</h3><p>Record availability and review current or upcoming absences.</p></a>`);
  if(context.user.canManageSecurity)cards.push(`<a class="manage-card" href="/ui-v2/security">${icon("security")}<span class="manage-arrow">→</span><h3>Security</h3><p>Accounts, Access Groups and platform permissions.</p></a>`);
  if(context.user.canManageSettings)cards.push(`<a class="manage-card" href="/ui-v2/settings">${icon("settings")}<span class="manage-arrow">→</span><h3>Settings</h3><p>Alliance details, branding, Discord, ranks and player options.</p></a>`);
  if(context.user.isOwner)cards.push(`<a class="manage-card" href="/ui-v2/backup">${icon("backup")}<span class="manage-arrow">→</span><h3>Backup &amp; Export</h3><p>Portable exports and recovery tools for the alliance owner.</p></a>`);
  return cards.join("");
}

export async function renderUiV2Console(env:UiV2Env,context:UiV2Context){
  const today=londonToday();
  const [activePlayers,formerPlayers,pendingAccounts,guild,awayResult]=await Promise.all([
    env.DB.prepare("SELECT COUNT(*) total FROM players WHERE is_active=1").first<CountRow>(),
    env.DB.prepare("SELECT COUNT(*) total FROM players WHERE is_active=0").first<CountRow>(),
    context.user.canApproveAccounts?env.DB.prepare("SELECT COUNT(*) total FROM accounts WHERE approval_status='pending'").first<CountRow>():Promise.resolve(null),
    env.DB.prepare("SELECT guild_name FROM discord_guild_connection WHERE id=1 LIMIT 1").first<GuildRow>().catch(()=>null),
    env.DB.prepare("SELECT p.display_name FROM players p WHERE p.is_active=1 AND EXISTS(SELECT 1 FROM player_away_periods w WHERE w.player_id=p.id AND w.cancelled_at IS NULL AND w.start_date<=? AND (w.end_date IS NULL OR w.end_date>=?)) ORDER BY p.display_name COLLATE NOCASE LIMIT 4").bind(today,today).all<AwayRow>().catch(()=>null)
  ]);
  const active=Number(activePlayers?.total??0),former=Number(formerPlayers?.total??0),pending=Number(pendingAccounts?.total??0),awayPlayers=awayResult?.results??[];
  const awayRows=awayPlayers.length?awayPlayers.map((player,index)=>`<div class="person-row"><div class="date-tile"><strong>${index+1}</strong><span>Away</span></div><div class="row-copy"><strong>${esc(player.display_name)}</strong><span>Currently unavailable</span></div><span class="row-state warning">Away now</span></div>`).join(""):`<div class="person-row"><div class="date-tile"><strong>✓</strong><span>Clear</span></div><div class="row-copy"><strong>Nobody currently away</strong><span>Live player-away data</span></div><span class="row-state success">All present</span></div>`;
  const management=managementCards(context,pending);
  const body=`${dashboardCss}
    <div class="preview-note"><span><strong>First dashboard preview.</strong> Player and away totals are live; events, birthdays, news and game statistics use clearly marked sample content until data is imported.</span><span class="sample-badge">Layout preview</span></div>
    <div class="snapshot-grid">
      <div class="snapshot-card"><span>Active players</span><strong>${active}</strong><small>${former} former player${former===1?"":"s"}</small></div>
      <div class="snapshot-card"><span>Alliance power</span><strong>6.42B</strong><small class="positive">↑ 1.8% this week · Sample</small></div>
      <div class="snapshot-card"><span>Average power</span><strong>64.2M</strong><small>Per active player · Sample</small></div>
      <div class="snapshot-card"><span>Weekly VS</span><strong>31.6B</strong><small class="positive">Leading by 1.8B · Sample</small></div>
    </div>
    <section class="dashboard-section">
      <div class="section-head"><div><h2>What’s happening</h2><p>News, events and member availability in one view.</p></div></div>
      <div class="life-grid">
        <article class="dashboard-card news-card"><div class="card-top"><span class="card-type">Alliance news</span><span class="sample-badge">Sample</span></div><div class="news-feature"><span class="news-date">Leadership update</span><h3>Welcome to the new alliance dashboard</h3><p>Important announcements will live here, with the newest story given prominence and older updates kept close at hand.</p></div><div class="news-list"><div class="news-row"><time>Today</time><strong>Season planning information added</strong></div><div class="news-row"><time>Yesterday</time><strong>Desert Storm team selection reminder</strong></div></div></article>
        <div class="side-stack">
          <article class="dashboard-card"><div class="card-top"><h3>Upcoming events</h3><span class="sample-badge">Sample</span></div><div class="event-list"><div class="event-row"><div class="date-tile"><strong>18</strong><span>Sep</span></div><div class="row-copy"><strong>VS · Hero Advancement</strong><span>Daily target closes at reset</span></div><span class="row-state">Today</span></div><div class="event-row"><div class="date-tile"><strong>19</strong><span>Sep</span></div><div class="row-copy"><strong>Shield reminder</strong><span>Protect before enemy buster</span></div><span class="row-state warning">21:00</span></div><div class="event-row"><div class="date-tile"><strong>20</strong><span>Sep</span></div><div class="row-copy"><strong>Desert Storm</strong><span>Selected team check-in</span></div><span class="row-state">20:00</span></div></div></article>
          <article class="dashboard-card"><div class="card-top"><h3>Birthdays</h3><span class="sample-badge">Sample</span></div><div class="people-list"><div class="person-row"><div class="date-tile"><strong>24</strong><span>Sep</span></div><div class="row-copy"><strong>Example Player</strong><span>Birthday coming up</span></div><span class="row-state">6 days</span></div><div class="person-row"><div class="date-tile"><strong>03</strong><span>Oct</span></div><div class="row-copy"><strong>Another Player</strong><span>Birthday coming up</span></div><span class="row-state">15 days</span></div></div></article>
          <article class="dashboard-card"><div class="card-top"><h3>Players away</h3>${context.user.canManageAway?'<a class="section-link" href="/ui-v2/away">Manage →</a>':""}</div><div class="people-list">${awayRows}</div></article>
        </div>
      </div>
    </section>
    <section class="dashboard-section">
      <div class="section-head"><div><h2>Game performance</h2><p>The latest alliance activity and competition statistics.</p></div><span class="sample-badge">Sample data</span></div>
      <div class="game-grid">
        <article class="dashboard-card game-card"><span class="card-type">VS Battle Centre</span><h3>Winning the week</h3><span class="game-subtitle">Day 4 · Hero Advancement</span><div class="game-score"><strong>31.6B</strong><span>Opponent<br>29.8B</span></div><div class="progress"><span style="width:74%"></span></div><div class="game-facts"><div class="game-fact"><span>Daily target reached</span><strong>74%</strong></div><div class="game-fact"><span>Players over 7.2M</span><strong>63 / 100</strong></div></div><span class="game-action">Open VS details →</span></article>
        <article class="dashboard-card game-card"><span class="card-type">Desert Storm</span><h3>Next battle</h3><span class="game-subtitle">Saturday · 20:00</span><div class="game-score"><strong>19/20</strong><span>Players<br>selected</span></div><div class="progress"><span style="width:95%"></span></div><div class="game-facts"><div class="game-fact"><span>Confirmed</span><strong>17</strong></div><div class="game-fact"><span>Last result</span><strong class="positive">Victory</strong></div></div><span class="game-action">View team →</span></article>
        <article class="dashboard-card game-card"><span class="card-type">Alliance Train</span><h3>Last 7 days</h3><span class="game-subtitle">Participation overview</span><div class="game-score"><strong>84</strong><span>Total seats<br>used</span></div><div class="progress"><span style="width:84%"></span></div><div class="game-facts"><div class="game-fact"><span>Average per day</span><strong>12</strong></div><div class="game-fact"><span>Top conductor</span><strong>Example Player</strong></div></div><span class="game-action">Open Train details →</span></article>
      </div>
    </section>
    ${management?`<section class="dashboard-section"><div class="section-head"><div><h2>Manage the alliance</h2><p>Only tools available to your account are shown.</p></div><span class="sample-badge">${guild?`Discord · ${esc(guild.guild_name)}`:"Discord not connected"}</span></div><div class="manage-grid">${management}</div></section>`:""}`;
  return uiV2Html(renderUiV2Shell(context,{eyebrow:"Alliance overview",title:"Alliance Dashboard",description:"Everything happening across the alliance, from member updates to game performance.",body,activePath:"/ui-v2"}));
}
