import {playerSameOrigin} from "../player_access";
import type {UiV2Context,UiV2Env} from "./context";
import {esc,renderUiV2Shell,uiV2Html} from "./shell";

type Linked={player_id:number;display_name:string;rank:number;discord_id:string;discord_name:string|null};
type Guild={guild_id:string};type Setting={key:string;value:string};type Member={roles:string[]};
const redirect=(r:Request,p:string)=>Response.redirect(new URL(p,r.url),303);
async function config(e:UiV2Env){const [g,s]=await Promise.all([e.DB.prepare("SELECT guild_id FROM discord_guild_connection WHERE id=1").first<Guild>(),e.DB.prepare("SELECT key,value FROM settings WHERE key LIKE 'discord_rank_role_r%'").all<Setting>()]);return{guild:g?.guild_id||"",roles:Object.fromEntries((s.results??[]).map(x=>[Number(x.key.slice(-1)),x.value])) as Record<number,string>}}
async function api(e:UiV2Env,path:string,method="GET"){if(!e.DISCORD_BOT_TOKEN)throw new Error("Bot token missing");const r=await fetch(`https://discord.com/api/v10${path}`,{method,headers:{authorization:`Bot ${e.DISCORD_BOT_TOKEN}`}});if(!r.ok)throw new Error(`Discord ${r.status}`);return r.status===204?null:r.json()}
export async function syncDiscordPlayerRank(e:UiV2Env,playerId:number,c?:UiV2Context){const row=await e.DB.prepare("SELECT p.id player_id,p.display_name,p.rank,i.provider_subject discord_id,i.provider_username discord_name FROM players p JOIN accounts a ON a.player_id=p.id AND a.is_active=1 AND a.approval_status='active' JOIN account_identities i ON i.account_id=a.id AND i.provider='discord' WHERE p.id=? AND p.is_active=1").bind(playerId).first<Linked>();if(!row)return"unlinked";const cfg=await config(e),wanted=cfg.roles[row.rank],managed=Object.values(cfg.roles);if(!cfg.guild||!wanted||managed.length<5)return"unconfigured";const member=await api(e,`/guilds/${cfg.guild}/members/${row.discord_id}`) as Member;for(const role of managed)if(role!==wanted&&member.roles.includes(role))await api(e,`/guilds/${cfg.guild}/members/${row.discord_id}/roles/${role}`,"DELETE");if(!member.roles.includes(wanted))await api(e,`/guilds/${cfg.guild}/members/${row.discord_id}/roles/${wanted}`,"PUT");if(c)await e.DB.prepare("INSERT INTO audit_log(public_id,actor_account_id,actor_display_name,action,entity_type,entity_id,source,new_values) VALUES(?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),c.user.accountId,c.user.displayName,"discord.rank.synced","player",String(playerId),"ui-v2-discord",JSON.stringify({discordId:row.discord_id,rank:row.rank,roleId:wanted})).run();return"synced"}
const css=`<style>.dr-card{padding:20px;border:1px solid var(--ui-line);border-radius:15px;background:var(--ui-surface-2)}.dr-card p{color:var(--ui-muted);font-size:.76rem}.dr-list{display:grid;gap:7px;margin:15px 0}.dr-row{display:flex;justify-content:space-between;gap:12px;padding:11px;border:1px solid var(--ui-line);border-radius:9px;background:var(--ui-surface-3);font-size:.72rem}.dr-row span{color:var(--ui-muted)}.dr-button{padding:11px 14px;border:0;border-radius:9px;background:var(--ui-button);color:var(--ui-button-text);font-weight:900;cursor:pointer}.dr-note{margin-bottom:14px;padding:12px;border:1px solid var(--ui-line);border-radius:10px;color:var(--ui-secondary)}</style>`;
async function rows(e:UiV2Env){return(await e.DB.prepare("SELECT p.id player_id,p.display_name,p.rank,i.provider_subject discord_id,i.provider_username discord_name FROM players p JOIN accounts a ON a.player_id=p.id AND a.is_active=1 AND a.approval_status='active' JOIN account_identities i ON i.account_id=a.id AND i.provider='discord' WHERE p.is_active=1 ORDER BY p.rank DESC,p.display_name COLLATE NOCASE LIMIT 100").all<Linked>()).results??[]}
async function page(r:Request,e:UiV2Env,c:UiV2Context){if(!c.user.canManageDiscord)return new Response("Forbidden",{status:403});const list=await rows(e),u=new URL(r.url),note=u.searchParams.has("synced")?`<div class="dr-note">Role sync finished: ${esc(u.searchParams.get("synced"))} updated, ${esc(u.searchParams.get("skipped")||"0")} skipped and ${esc(u.searchParams.get("failed")||"0")} failed.</div>`:"",body=`${css}${note}<section class="dr-card"><h2>Linked Discord members</h2><p>Review the website rank that will be applied. Only the platform-managed R1–R5 roles are changed.</p><div class="dr-list">${list.map(x=>`<div class="dr-row"><strong>${esc(x.display_name)}</strong><span>${esc(x.discord_name?`@${x.discord_name}`:x.discord_id)} · R${x.rank}</span></div>`).join("")||"No linked active players."}</div><form method="post" action="/ui-v2/settings/discord-rank-sync"><button class="dr-button" type="submit">Sync all linked players</button></form></section>`;return uiV2Html(renderUiV2Shell(c,{eyebrow:"Discord",title:"Rank Role Sync",description:"Keep Discord roles aligned with website player ranks.",body,activePath:"/ui-v2/settings/discord",back:{href:"/ui-v2/settings/discord",label:"Discord Settings"}}))}
async function run(r:Request,e:UiV2Env,c:UiV2Context){if(!c.user.canManageDiscord||!playerSameOrigin(r,e))return new Response("Forbidden",{status:403});let synced=0,skipped=0,failed=0;for(const row of await rows(e))try{const result=await syncDiscordPlayerRank(e,row.player_id,c);result==="synced"?synced++:skipped++}catch(error){console.error("Discord rank sync failed",row.player_id,error);failed++}return redirect(r,`/ui-v2/settings/discord-rank-sync?synced=${synced}&skipped=${skipped}&failed=${failed}`)}
export async function handleUiV2DiscordRankSync(r:Request,e:UiV2Env,c:UiV2Context):Promise<Response|null>{if(new URL(r.url).pathname!=="/ui-v2/settings/discord-rank-sync")return null;return r.method==="GET"?page(r,e,c):r.method==="POST"?run(r,e,c):new Response("Method not allowed",{status:405})}
