import {playerSameOrigin} from "../player_access";
import type {UiV2Context,UiV2Env} from "./context";
import {esc,renderUiV2Shell,uiV2Html} from "./shell";

type BaseChange={display_name:string;old_base:number;new_base:number;changed_at:string};
type RankChange={display_name:string;old_rank:number;new_rank:number;old_title:string|null;new_title:string|null;changed_at:string};
type Snapshot={player_id:number;display_name:string;total_strength:number|null;recorded_at:string};
type Growth={name:string;before:number;after:number;gain:number};
type Setting={key:string;value:string};
type Report={days:number;start:string;end:string;baseChanges:BaseChange[];promotions:RankChange[];otherRanks:RankChange[];growth:Growth[];sourceKey:string};

const allowedDays=new Set([7,14,30]);
const redirect=(request:Request,path:string)=>Response.redirect(new URL(path,request.url),303);
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const addDays=(date:string,days:number)=>{const value=new Date(`${date}T12:00:00Z`);value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10)};
const fmt=(value:number)=>value>=1e9?(value/1e9).toFixed(2).replace(/0+$/,"").replace(/\.$/,"")+"B":value>=1e6?(value/1e6).toFixed(1).replace(/\.0$/,"")+"M":value.toLocaleString("en-GB");
const rankName=(rank:number,title:string|null)=>title||`R${rank}`;
const fieldValue=(lines:string[])=>lines.length?lines.join("\n").slice(0,1024):"None this period";

async function buildReport(env:UiV2Env,days:number):Promise<Report>{
  const end=today(),start=addDays(end,-days+1),endExclusive=addDays(end,1),[baseResult,rankResult,snapshotResult]=await Promise.all([
    env.DB.prepare("SELECT p.display_name,CAST(json_extract(a.old_values,'$.base_level') AS INTEGER) old_base,CAST(json_extract(a.new_values,'$.base_level') AS INTEGER) new_base,a.created_at changed_at FROM audit_log a JOIN players p ON p.id=CAST(a.entity_id AS INTEGER) WHERE a.entity_type='player' AND a.action IN ('player.updated','player.import.updated','player.import.reactivated') AND a.created_at>=? AND a.created_at<? AND json_extract(a.old_values,'$.base_level') IS NOT NULL AND json_extract(a.new_values,'$.base_level') IS NOT NULL AND CAST(json_extract(a.new_values,'$.base_level') AS INTEGER)>CAST(json_extract(a.old_values,'$.base_level') AS INTEGER) ORDER BY a.created_at,p.display_name COLLATE NOCASE").bind(start,endExclusive).all<BaseChange>(),
    env.DB.prepare("SELECT p.display_name,h.old_rank,h.new_rank,ro.display_name old_title,rn.display_name new_title,h.changed_at FROM player_rank_history h JOIN players p ON p.id=h.player_id LEFT JOIN alliance_ranks ro ON ro.rank_level=h.old_rank LEFT JOIN alliance_ranks rn ON rn.rank_level=h.new_rank WHERE h.old_rank IS NOT NULL AND h.changed_at>=? AND h.changed_at<? ORDER BY h.changed_at,p.display_name COLLATE NOCASE").bind(start,endExclusive).all<RankChange>(),
    env.DB.prepare("SELECT s.player_id,p.display_name,s.total_strength,s.recorded_at FROM player_roster_snapshots s JOIN players p ON p.id=s.player_id WHERE s.recorded_at<? AND s.total_strength IS NOT NULL ORDER BY s.player_id,s.recorded_at,s.id").bind(endExclusive).all<Snapshot>()
  ]);
  const grouped=new Map<number,Snapshot[]>();for(const snapshot of snapshotResult.results??[])grouped.set(snapshot.player_id,[...(grouped.get(snapshot.player_id)||[]),snapshot]);const growth:Growth[]=[];for(const rows of grouped.values()){let latestIndex=-1;for(let index=0;index<rows.length;index++)if(rows[index].recorded_at>=start)latestIndex=index;if(latestIndex>0){const latest=rows[latestIndex],previous=rows[latestIndex-1],after=Number(latest.total_strength),before=Number(previous.total_strength);if(after>before)growth.push({name:latest.display_name,before,after,gain:after-before})}}growth.sort((a,b)=>b.gain-a.gain||a.name.localeCompare(b.name));
  const rankChanges=rankResult.results??[];return{days,start,end,baseChanges:baseResult.results??[],promotions:rankChanges.filter(row=>row.new_rank>row.old_rank),otherRanks:rankChanges.filter(row=>row.new_rank<row.old_rank),growth:growth.slice(0,5),sourceKey:`${start}:${end}`};
}

const css=`<style>.ru-note{margin-bottom:14px;padding:12px 14px;border:1px solid var(--ui-line);border-radius:10px;background:var(--ui-surface-2);color:var(--ui-secondary)}.ru-toolbar{display:flex;align-items:end;justify-content:space-between;gap:14px;margin-bottom:14px;padding:15px;border:1px solid var(--ui-line);border-radius:13px;background:var(--ui-surface-2)}.ru-toolbar span,.ru-field span{display:block;margin-bottom:6px;color:var(--ui-muted);font-size:.7rem;font-weight:850}.ru-toolbar form{display:flex;align-items:end;gap:9px}.ru-toolbar select{padding:10px;border:1px solid var(--ui-line-strong);border-radius:9px;background:var(--ui-surface-3);color:var(--ui-text)}.ru-button{padding:10px 14px;border:0;border-radius:9px;background:var(--ui-button);color:var(--ui-button-text);font-weight:900;cursor:pointer}.ru-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.ru-card{padding:17px;border:1px solid var(--ui-line);border-radius:13px;background:var(--ui-surface-2)}.ru-card h2{margin:0;font-size:.95rem}.ru-card>p{margin:5px 0 12px;color:var(--ui-muted);font-size:.7rem}.ru-row{display:flex;justify-content:space-between;gap:12px;padding:9px 0;border-top:1px solid var(--ui-line);font-size:.72rem}.ru-row span:last-child{color:var(--ui-muted);text-align:right}.ru-empty{padding:13px 0;color:var(--ui-muted);font-size:.72rem}.ru-post{margin-top:14px;padding:17px;border:1px solid var(--ui-line);border-radius:13px;background:var(--ui-surface-2)}.ru-post h2{margin:0 0 5px;font-size:.95rem}.ru-post p{margin:0 0 13px;color:var(--ui-muted);font-size:.72rem;line-height:1.5}@media(max-width:700px){.ru-toolbar{display:block}.ru-toolbar form{margin-top:12px}.ru-grid{grid-template-columns:1fr}}</style>`;
const card=(title:string,description:string,rows:string[])=>`<section class="ru-card"><h2>${esc(title)} · ${rows.length}</h2><p>${esc(description)}</p>${rows.length?rows.join(""):'<div class="ru-empty">Nothing to include for this period.</div>'}</section>`;

async function page(request:Request,env:UiV2Env,context:UiV2Context){
  if(!context.user.canManageDiscord)return new Response("Forbidden",{status:403});const url=new URL(request.url),requested=Number(url.searchParams.get("days")||7),days=allowedDays.has(requested)?requested:7,report=await buildReport(env,days),feedback=url.searchParams.get("discord"),note=feedback==="posted"?"Roster Update posted to Discord.":feedback==="duplicate"?"This Roster Update period has already been posted.":feedback==="disabled"?"Choose an Alliance Updates channel in Discord Notifications first.":feedback==="empty"?"There are no roster achievements to post for this period.":feedback==="failed"?"Discord could not receive the update. Nothing else was changed.":"",posted=await env.DB.prepare("SELECT posted_at FROM discord_notification_posts WHERE notification_type='roster_update' AND source_key=?").bind(report.sourceKey).first<{posted_at:string}>(),hasContent=report.baseChanges.length+report.promotions.length+report.otherRanks.length+report.growth.length>0;
  const cards=[card("Base Upgrades","Players whose recorded base level increased.",report.baseChanges.map(row=>`<div class="ru-row"><strong>${esc(row.display_name)}</strong><span>Base ${row.old_base} → ${row.new_base}</span></div>`)),card("Rank Promotions","Players promoted during this period.",report.promotions.map(row=>`<div class="ru-row"><strong>${esc(row.display_name)}</strong><span>${esc(rankName(row.old_rank,row.old_title))} → ${esc(rankName(row.new_rank,row.new_title))}</span></div>`)),card("Other Rank Changes","Recorded rank changes that were not promotions.",report.otherRanks.map(row=>`<div class="ru-row"><strong>${esc(row.display_name)}</strong><span>${esc(rankName(row.old_rank,row.old_title))} → ${esc(rankName(row.new_rank,row.new_title))}</span></div>`)),card("Power Growth","Top positive Total Strength gains from the latest comparison.",report.growth.map(row=>`<div class="ru-row"><strong>${esc(row.name)}</strong><span>+${fmt(row.gain)} · ${fmt(row.after)}</span></div>`))].join("");
  const post=posted?`<div class="ru-note">Already posted on ${esc(posted.posted_at)}.</div>`:hasContent?`<form method="post" action="/ui-v2/discord/roster-update/post"><input type="hidden" name="days" value="${days}"><input type="hidden" name="source_key" value="${esc(report.sourceKey)}"><button class="ru-button" type="submit">Post Roster Update to Discord</button></form>`:'<div class="ru-note">Nothing to post for this period.</div>',body=`${css}${note?`<div class="ru-note">${esc(note)}</div>`:""}<div class="ru-toolbar"><div><strong>${days}-day Roster Update</strong><span>${esc(report.start)} to ${esc(report.end)} · Preview before posting</span></div><form method="get"><label class="ru-field"><span>Period</span><select name="days">${[7,14,30].map(value=>`<option value="${value}"${value===days?" selected":""}>Last ${value} days</option>`).join("")}</select></label><button class="ru-button">Preview</button></form></div><div class="ru-grid">${cards}</div><section class="ru-post"><h2>Alliance Updates channel</h2><p>The post celebrates recorded progress. It includes base upgrades, promotions, other rank changes and up to five leading Total Strength gains.</p>${post}</section>`;
  return uiV2Html(renderUiV2Shell(context,{eyebrow:"Discord",title:"Roster Update",description:"Preview a positive player-progress update before posting it to the alliance.",body,activePath:"/ui-v2/settings/discord-notifications",back:{href:"/ui-v2/settings/discord-notifications",label:"Discord Notifications"}}));
}

async function post(request:Request,env:UiV2Env,context:UiV2Context){
  if(!context.user.canManageDiscord||!playerSameOrigin(request,env))return new Response("Forbidden",{status:403});const form=await request.formData(),requested=Number(form.get("days")||7),days=allowedDays.has(requested)?requested:7,report=await buildReport(env,days);if(String(form.get("source_key")||"")!==report.sourceKey)return redirect(request,`/ui-v2/discord/roster-update?days=${days}`);const count=report.baseChanges.length+report.promotions.length+report.otherRanks.length+report.growth.length;if(!count)return redirect(request,`/ui-v2/discord/roster-update?days=${days}&discord=empty`);const existing=await env.DB.prepare("SELECT id FROM discord_notification_posts WHERE notification_type='roster_update' AND source_key=?").bind(report.sourceKey).first();if(existing)return redirect(request,`/ui-v2/discord/roster-update?days=${days}&discord=duplicate`);const settings=Object.fromEntries(((await env.DB.prepare("SELECT key,value FROM settings WHERE key='discord_alliance_channel_id'").all<Setting>()).results??[]).map(row=>[row.key,row.value]));if(!settings.discord_alliance_channel_id)return redirect(request,`/ui-v2/discord/roster-update?days=${days}&discord=disabled`);
  const fields=[report.baseChanges.length?{name:`🏗️ Base Upgrades · ${report.baseChanges.length}`,value:fieldValue(report.baseChanges.map(row=>`**${row.display_name}** · Base ${row.old_base} → ${row.new_base}`)),inline:false}:null,report.promotions.length?{name:`🌟 Promotions · ${report.promotions.length}`,value:fieldValue(report.promotions.map(row=>`**${row.display_name}** · ${rankName(row.old_rank,row.old_title)} → ${rankName(row.new_rank,row.new_title)}`)),inline:false}:null,report.otherRanks.length?{name:`🦆 Rank Changes · ${report.otherRanks.length}`,value:fieldValue(report.otherRanks.map(row=>`**${row.display_name}** · ${rankName(row.old_rank,row.old_title)} → ${rankName(row.new_rank,row.new_title)}`)),inline:false}:null,report.growth.length?{name:"💪 Leading Power Growth",value:fieldValue(report.growth.map(row=>`**${row.name}** · +${fmt(row.gain)} · now ${fmt(row.after)}`)),inline:false}:null].filter(Boolean);
  try{if(!env.DISCORD_BOT_TOKEN)throw new Error("Discord bot token missing");const response=await fetch(`https://discord.com/api/v10/channels/${settings.discord_alliance_channel_id}/messages`,{method:"POST",headers:{authorization:`Bot ${env.DISCORD_BOT_TOKEN}`,"content-type":"application/json"},body:JSON.stringify({embeds:[{title:"Alliance Roster Update",description:`Celebrating player progress recorded from **${report.start}** to **${report.end}**.`,color:0x63b9e8,fields,footer:{text:context.alliance.name}}]})});if(!response.ok)throw new Error(`Discord message ${response.status}`);const message=await response.json<{id:string}>();await env.DB.batch([env.DB.prepare("INSERT INTO discord_notification_posts(notification_type,source_key,channel_id,discord_message_id,posted_by_account_id) VALUES('roster_update',?,?,?,?)").bind(report.sourceKey,settings.discord_alliance_channel_id,message.id,context.user.accountId),env.DB.prepare("INSERT INTO audit_log(public_id,actor_account_id,actor_display_name,action,entity_type,entity_id,source,new_values) VALUES(?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),context.user.accountId,context.user.displayName,"discord.roster_update.posted","discord_notifications",report.sourceKey,"ui-v2-discord",JSON.stringify({days,start:report.start,end:report.end,channel:settings.discord_alliance_channel_id,messageId:message.id,items:count}))]);return redirect(request,`/ui-v2/discord/roster-update?days=${days}&discord=posted`)}catch(error){console.error(error);return redirect(request,`/ui-v2/discord/roster-update?days=${days}&discord=failed`)}
}

export async function handleUiV2DiscordRosterUpdate(request:Request,env:UiV2Env,context:UiV2Context):Promise<Response|null>{const path=new URL(request.url).pathname;if(path==="/ui-v2/discord/roster-update")return request.method==="GET"?page(request,env,context):new Response("Method not allowed",{status:405});if(path==="/ui-v2/discord/roster-update/post")return request.method==="POST"?post(request,env,context):new Response("Method not allowed",{status:405});return null}
