import {playerSameOrigin} from "../player_access";
import type {UiV2Context,UiV2Env} from "./context";
import {esc,renderUiV2Shell,uiV2Html} from "./shell";

type Guild={guild_id:string;guild_name:string};
type DiscordChannel={id:string;name:string;type:number;parent_id?:string|null};
type DiscordRole={id:string;name:string};
type DiscordUser={id:string;username:string;global_name?:string|null};
type ChannelDef={key:string;name:string;type:0|2;topic?:string;duck?:string};
type CategoryDef={key:string;name:string;private?:boolean;duck?:string;channels:ChannelDef[]};

const API="https://discord.com/api/v10",VIEW_CHANNEL="1024",SEND_MESSAGES="2048",READ_ALLOW="66560",TEXT_ALLOW="117824",VOICE_ALLOW="36701184";
const redirect=(request:Request,path:string)=>Response.redirect(new URL(path,request.url),303);
const audit=(env:UiV2Env,context:UiV2Context,action:string,values:unknown)=>env.DB.prepare("INSERT INTO audit_log (public_id,actor_account_id,actor_display_name,action,entity_type,entity_id,source,new_values) VALUES (?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),context.user.accountId,context.user.displayName,action,"discord_setup","settings","ui-v2-discord",JSON.stringify(values));
const textName=(value:string,fallback:string)=>value.trim().toLowerCase().replace(/[^a-z0-9-_]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80)||fallback;
const displayName=(value:string,fallback:string)=>value.trim().replace(/[\r\n\t]/g," ").slice(0,80)||fallback;

const TEMPLATE:CategoryDef[]=[
  {key:"news",name:"📣 News & Announcements",channels:[
    {key:"welcome",name:"welcome",type:0,topic:"Welcome and essential server information",duck:"welcome-to-the-pond"},{key:"rules",name:"rules",type:0,topic:"Alliance Discord rules"},{key:"announcements",name:"announcements",type:0,topic:"Official alliance announcements"},{key:"alliance_updates",name:"alliance-updates",type:0,topic:"Automated updates from The Alliance Management Platform"},{key:"last_war_news",name:"last-war-news",type:0},{key:"last_war_updates",name:"last-war-update-note",type:0}
  ]},
  {key:"leadership",name:"🔐 Leadership HQ",private:true,duck:"🔐 R4/R5 HQ",channels:[
    {key:"leadership_chat",name:"leadership-chat",type:0},{key:"member_discussion",name:"member-discussion",type:0},{key:"planning",name:"planning",type:0},{key:"leadership_updates",name:"updates",type:0},{key:"discord_admin",name:"discord-admin",type:0}
  ]},
  {key:"community",name:"Community",duck:"🦆 The Pond",channels:[
    {key:"general",name:"general-chat",type:0,duck:"general-quacking"},{key:"game_chat",name:"game-chat",type:0},{key:"memes",name:"memes-and-mayhem",type:0},{key:"screenshots",name:"screenshots",type:0}
  ]},
  {key:"war",name:"⚔️ War Room",channels:[{key:"desert_storm",name:"desert-storm",type:0},{key:"season",name:"current-season",type:0,duck:"season-6"},{key:"guides",name:"strategies-and-guides",type:0}]},
  {key:"vs",name:"🗓️ VS Tips",channels:[{key:"vs_pics",name:"vs-pics",type:0},...["monday","tuesday","wednesday","thursday","friday","saturday","sunday"].map(name=>({key:`vs_${name}`,name,type:0 as const}))]},
  {key:"voice",name:"🔊 Voice Channels",channels:[{key:"main_voice",name:"Alliance Voice",type:2,duck:"The Duck Pond"},{key:"war_voice",name:"War Room",type:2}]}
];

async function discord<T>(env:UiV2Env,path:string,init:RequestInit={}){if(!env.DISCORD_BOT_TOKEN)throw new Error("Discord bot token is not configured");const headers=new Headers(init.headers);headers.set("authorization",`Bot ${env.DISCORD_BOT_TOKEN}`);if(init.body)headers.set("content-type","application/json");const response=await fetch(`${API}${path}`,{...init,headers});if(!response.ok)throw new Error(`Discord ${path} ${response.status}`);return response.status===204?null as T:response.json<T>()}

const css=`<style>
.dsu-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.dsu-card{padding:20px;border:1px solid var(--ui-line);border-radius:15px;background:var(--ui-surface-2)}.dsu-card h2{margin:0 0 7px;font-size:1rem}.dsu-card p{margin:0 0 13px;color:var(--ui-muted);font-size:.76rem;line-height:1.55}.dsu-template{display:grid;gap:12px;margin:15px 0}.dsu-category{padding:13px;border:1px solid var(--ui-line);border-radius:11px;background:var(--ui-surface-3)}.dsu-cat-head,.dsu-channel{display:grid;grid-template-columns:24px minmax(0,1fr) auto;align-items:center;gap:9px}.dsu-cat-head{padding-bottom:8px}.dsu-cat-head input[type=text],.dsu-channel input[type=text],.dsu-field input{width:100%;padding:9px 10px;border:1px solid var(--ui-line-strong);border-radius:8px;background:var(--ui-surface-2);color:var(--ui-text)}.dsu-permissions{display:flex;align-items:center;gap:8px;margin:0 0 10px 33px;color:var(--ui-secondary);font-size:.67rem;font-weight:800}.dsu-channels{display:grid;gap:7px;padding-left:16px;border-left:2px solid var(--ui-line)}.dsu-channel span,.dsu-cat-head span{color:var(--ui-muted);font-size:.62rem;font-weight:850}.dsu-duck{grid-column:2/-1;color:var(--ui-muted);font-size:.62rem}.dsu-button{display:inline-flex;align-items:center;justify-content:center;padding:11px 14px;border:1px solid transparent;border-radius:9px;background:var(--ui-button);color:var(--ui-button-text);font-weight:900;text-decoration:none;cursor:pointer}.dsu-button.secondary{border-color:var(--ui-line-strong);background:var(--ui-surface-3);color:var(--ui-navigation)}.dsu-field{display:block;margin-bottom:13px}.dsu-field span{display:block;margin-bottom:6px;font-size:.72rem;font-weight:900}.dsu-field small{display:block;margin-top:6px;color:var(--ui-muted);font-size:.66rem}.dsu-note{margin-bottom:14px;padding:12px;border:1px solid var(--ui-line);border-radius:10px;color:var(--ui-secondary)}.dsu-wide{grid-column:1/-1}@media(max-width:700px){.dsu-grid{grid-template-columns:1fr}.dsu-wide{grid-column:auto}.dsu-cat-head,.dsu-channel{grid-template-columns:24px minmax(0,1fr)}.dsu-cat-head>span,.dsu-channel>span{grid-column:2}.dsu-button{width:100%}}
</style>`;

const exists=(items:DiscordChannel[],type:number,name:string)=>items.some(item=>item.type===type&&item.name.toLowerCase()===name.toLowerCase());
const templateRows=(items:DiscordChannel[])=>TEMPLATE.map(category=>{const categoryExists=exists(items,4,category.name),channels=category.channels.map(channel=>`<label class="dsu-channel"><input type="checkbox" name="use_channel_${channel.key}" value="1" checked><input type="text" name="name_channel_${channel.key}" maxlength="80" value="${esc(channel.name)}"><span>${exists(items,channel.type,channel.name)?"Existing":channel.type===2?"Voice":"Text"}</span>${channel.duck?`<small class="dsu-duck">DuCK example: ${esc(channel.duck)}</small>`:""}</label>`).join(""),permissionText=category.key==="news"?"View-only for members; R4/R5 and bot can post":category.key==="leadership"?"Visible only to R4, R5 and the bot":category.key==="voice"?"R1–R5 can connect and speak":"Visible and writable for R1–R5";return `<div class="dsu-category"><label class="dsu-cat-head"><input type="checkbox" name="use_category_${category.key}" value="1" checked><input type="text" name="name_category_${category.key}" maxlength="80" value="${esc(category.name)}"><span>${categoryExists?"Existing":category.private?"Private":"Category"}</span>${category.duck?`<small class="dsu-duck">DuCK example: ${esc(category.duck)}</small>`:""}</label><label class="dsu-permissions"><input type="checkbox" name="apply_permissions_${category.key}" value="1"${categoryExists?"":" checked"}> Apply recommended permissions · ${permissionText}${categoryExists?" (off by default for existing category)":""}</label><div class="dsu-channels">${channels}</div></div>`}).join("");

async function page(request:Request,env:UiV2Env,context:UiV2Context){if(!context.user.canManageDiscord)return new Response("Forbidden",{status:403});const guild=await env.DB.prepare("SELECT guild_id,guild_name FROM discord_guild_connection WHERE id=1").first<Guild>();if(!guild)return redirect(request,"/ui-v2/settings/discord?error=Connect%20a%20Discord%20server%20first.");let bot:DiscordUser|null=null,channels:DiscordChannel[]=[];try{[bot,channels]=await Promise.all([discord<DiscordUser>(env,"/users/@me"),discord<DiscordChannel[]>(env,`/guilds/${guild.guild_id}/channels`)])}catch{}const url=new URL(request.url),result=url.searchParams.get("result"),error=url.searchParams.get("error"),note=url.searchParams.has("connected")?'<div class="dsu-note">Discord is connected. Choose how this server should be configured.</div>':result==="template"?`<div class="dsu-note">Template complete: ${esc(url.searchParams.get("created")||"0")} items created, ${esc(url.searchParams.get("reused")||"0")} reused and permissions applied to ${esc(url.searchParams.get("permissions")||"0")} categories.</div>`:result==="identity"?'<div class="dsu-note">Bot name and server image updated.</div>':error?`<div class="dsu-note">${esc(error)}</div>`:"",body=`${css}${note}<div class="dsu-grid"><section class="dsu-card dsu-wide"><h2>Complete alliance server template</h2><p>Tick only the categories and channels wanted, and rename anything before creating it. Roles R1–R5 are created or reused. Existing permissions change only when their permission box is selected. Ticket Tool is not included.</p><form method="post" action="/ui-v2/settings/discord-setup/create"><div class="dsu-template">${templateRows(channels)}</div><button class="dsu-button" type="submit">Check and add selected structure</button></form></section><section class="dsu-card"><h2>Use existing channels</h2><p>Map the platform to differently named channels without changing the server.</p><a class="dsu-button secondary" href="/ui-v2/settings/discord-notifications">Choose existing channels</a></section><section class="dsu-card"><h2>Bot appearance in ${esc(guild.guild_name)}</h2><form method="post" action="/ui-v2/settings/discord-setup/identity" enctype="multipart/form-data"><label class="dsu-field"><span>Bot name</span><input name="bot_name" maxlength="32" required value="${esc(bot?.global_name||bot?.username||"Alliance Platform")}"></label><label class="dsu-field"><span>Server bot image</span><input name="bot_image" type="file" accept="image/png,image/jpeg,image/webp,image/gif"><small>PNG, JPEG, WebP or GIF; maximum 256 KB.</small></label><button class="dsu-button" type="submit">Save bot appearance</button></form></section></div>`;return uiV2Html(renderUiV2Shell(context,{eyebrow:"Discord",title:"Server Setup",description:"Build, extend or connect the alliance Discord server.",body,activePath:"/ui-v2/settings/discord",back:{href:"/ui-v2/settings/discord",label:"Discord Settings"}}))}

const permissionSet=(key:string,guildId:string,rankRoles:Record<number,DiscordRole>,botId:string)=>{const rows:Array<{id:string;type:0|1;allow:string;deny:string}>=[{id:guildId,type:0,allow:key==="news"?READ_ALLOW:"0",deny:key==="news"?SEND_MESSAGES:VIEW_CHANNEL}],levels=key==="leadership"||key==="news"?[4,5]:[1,2,3,4,5],allow=key==="voice"?VOICE_ALLOW:TEXT_ALLOW;levels.forEach(level=>rows.push({id:rankRoles[level].id,type:0,allow,deny:"0"}));rows.push({id:botId,type:1,allow:key==="voice"?VOICE_ALLOW:TEXT_ALLOW,deny:"0"});return rows};
async function applyPermissions(env:UiV2Env,channelId:string,rows:Array<{id:string;type:0|1;allow:string;deny:string}>){for(const row of rows)await discord(env,`/channels/${channelId}/permissions/${row.id}`,{method:"PUT",body:JSON.stringify({type:row.type,allow:row.allow,deny:row.deny})})}

async function createStructure(request:Request,env:UiV2Env,context:UiV2Context){
  if(!context.user.canManageDiscord||!playerSameOrigin(request,env))return new Response("Forbidden",{status:403});
  const guild=await env.DB.prepare("SELECT guild_id,guild_name FROM discord_guild_connection WHERE id=1").first<Guild>();if(!guild)return redirect(request,"/ui-v2/settings/discord");const form=await request.formData();
  try{
    const [items,roles,bot]=await Promise.all([discord<DiscordChannel[]>(env,`/guilds/${guild.guild_id}/channels`),discord<DiscordRole[]>(env,`/guilds/${guild.guild_id}/roles`),discord<DiscordUser>(env,"/users/@me")]);let created=0,reused=0,permissionsApplied=0;const rankRoles:Record<number,DiscordRole>={};
    for(const level of [5,4,3,2,1]){let role=roles.find(item=>item.name.toUpperCase()===`R${level}`);if(!role){role=await discord<DiscordRole>(env,`/guilds/${guild.guild_id}/roles`,{method:"POST",body:JSON.stringify({name:`R${level}`,permissions:"0",mentionable:false})});created++}else reused++;rankRoles[level]=role}
    const added:DiscordChannel[]=[],selected:Record<string,string>={};
    for(const categoryDef of TEMPLATE){
      if(form.get(`use_category_${categoryDef.key}`)!=="1")continue;const categoryName=displayName(String(form.get(`name_category_${categoryDef.key}`)||""),categoryDef.name);let category=items.find(item=>item.type===4&&item.name.toLowerCase()===categoryName.toLowerCase())||added.find(item=>item.type===4&&item.name.toLowerCase()===categoryName.toLowerCase()),overwrites=permissionSet(categoryDef.key,guild.guild_id,rankRoles,bot.id);
      if(!category){category=await discord<DiscordChannel>(env,`/guilds/${guild.guild_id}/channels`,{method:"POST",body:JSON.stringify({name:categoryName,type:4,permission_overwrites:form.get(`apply_permissions_${categoryDef.key}`)==="1"?overwrites:undefined})});added.push(category);created++;if(form.get(`apply_permissions_${categoryDef.key}`)==="1")permissionsApplied++}else{reused++;if(form.get(`apply_permissions_${categoryDef.key}`)==="1"){await applyPermissions(env,category.id,overwrites);permissionsApplied++}}
      for(const channelDef of categoryDef.channels){if(form.get(`use_channel_${channelDef.key}`)!=="1")continue;const raw=String(form.get(`name_channel_${channelDef.key}`)||""),channelName=channelDef.type===0?textName(raw,channelDef.name):displayName(raw,channelDef.name);let channel=items.find(item=>item.type===channelDef.type&&item.parent_id===category!.id&&item.name.toLowerCase()===channelName.toLowerCase())||added.find(item=>item.type===channelDef.type&&item.parent_id===category!.id&&item.name.toLowerCase()===channelName.toLowerCase());if(!channel){channel=await discord<DiscordChannel>(env,`/guilds/${guild.guild_id}/channels`,{method:"POST",body:JSON.stringify({name:channelName,type:channelDef.type,parent_id:category.id,topic:channelDef.type===0?channelDef.topic:undefined})});added.push(channel);created++}else reused++;selected[channelDef.key]=channel.id}
    }
    const statements:D1PreparedStatement[]=[];if(selected.alliance_updates)statements.push(env.DB.prepare("INSERT INTO settings(key,value,updated_at) VALUES('discord_alliance_channel_id',?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").bind(selected.alliance_updates));if(selected.leadership_updates)statements.push(env.DB.prepare("INSERT INTO settings(key,value,updated_at) VALUES('discord_leadership_channel_id',?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").bind(selected.leadership_updates));for(let level=1;level<=5;level++)statements.push(env.DB.prepare("INSERT INTO settings(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").bind(`discord_rank_role_r${level}`,rankRoles[level].id));statements.push(audit(env,context,"discord.template.applied",{guildId:guild.guild_id,created,reused,permissionsApplied,selected,roles:Object.fromEntries(Object.entries(rankRoles).map(([level,role])=>[`R${level}`,role.id]))}));await env.DB.batch(statements);return redirect(request,`/ui-v2/settings/discord-setup?result=template&created=${created}&reused=${reused}&permissions=${permissionsApplied}`)
  }catch(error){console.error("Discord template creation failed",error);return redirect(request,"/ui-v2/settings/discord-setup?error="+encodeURIComponent("The template stopped before completion. Existing and newly created items are safe; run it again after checking the bot permissions."))}
}

const imageData=async(file:File)=>{const allowed=new Set(["image/png","image/jpeg","image/webp","image/gif"]);if(!allowed.has(file.type)||file.size>262144)throw new Error("invalid image");const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(let offset=0;offset<bytes.length;offset+=8192)binary+=String.fromCharCode(...bytes.subarray(offset,offset+8192));return `data:${file.type};base64,${btoa(binary)}`};
async function saveIdentity(request:Request,env:UiV2Env,context:UiV2Context){if(!context.user.canManageDiscord||!playerSameOrigin(request,env))return new Response("Forbidden",{status:403});const guild=await env.DB.prepare("SELECT guild_id FROM discord_guild_connection WHERE id=1").first<Guild>();if(!guild)return redirect(request,"/ui-v2/settings/discord");const form=await request.formData(),name=String(form.get("bot_name")||"").trim(),file=form.get("bot_image");if(name.length<2||name.length>32)return redirect(request,"/ui-v2/settings/discord-setup?error="+encodeURIComponent("Enter a bot name between 2 and 32 characters."));try{const payload:Record<string,string>={nick:name};if(file instanceof File&&file.size)payload.avatar=await imageData(file);await discord(env,`/guilds/${guild.guild_id}/members/@me`,{method:"PATCH",body:JSON.stringify(payload)});await env.DB.batch([env.DB.prepare("INSERT INTO settings(key,value,updated_at) VALUES('discord_bot_display_name',?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").bind(name),audit(env,context,"discord.bot_identity.updated",{name,imageUpdated:Boolean(file instanceof File&&file.size)})]);return redirect(request,"/ui-v2/settings/discord-setup?result=identity")}catch(error){console.error("Discord bot identity update failed",error);return redirect(request,"/ui-v2/settings/discord-setup?error="+encodeURIComponent("The bot appearance could not be updated. Check the image and bot permissions."))}}

export async function handleUiV2DiscordSetup(request:Request,env:UiV2Env,context:UiV2Context):Promise<Response|null>{const path=new URL(request.url).pathname;if(path==="/ui-v2/settings/discord-setup")return request.method==="GET"?page(request,env,context):new Response("Method not allowed",{status:405});if(path==="/ui-v2/settings/discord-setup/create")return request.method==="POST"?createStructure(request,env,context):new Response("Method not allowed",{status:405});if(path==="/ui-v2/settings/discord-setup/identity")return request.method==="POST"?saveIdentity(request,env,context):new Response("Method not allowed",{status:405});return null}
