import {loadUiV2Context,type UiV2Env} from "./context";
import {renderUiV2Audit} from "./audit";
import {handleUiV2Away} from "./away";
import {handleUiV2Backup} from "./backup";
import {handleUiV2Branding} from "./branding";
import {renderUiV2Console} from "./console";
import {handleUiV2Events} from "./events";
import {renderUiV2Leadership} from "./leadership";
import {renderUiV2Players} from "./players";
import {handleUiV2PlayerImport} from "./player_import";
import {handleUiV2PlayerManagement} from "./player_management";
import {handleUiV2Ranks} from "./ranks";
import {handleUiV2Security} from "./security";
import {handleUiV2Settings} from "./settings";
import {handleUiV2Train} from "./train";
import {handleUiV2Vs} from "./vs";
import {handleUiV2DesertStorm} from "./desert_storm";
import {handleUiV2ShieldDrops} from "./shield_drops";
import {renderUiV2Intelligence} from "./intelligence";
import {handleUiV2SelfProfile} from "./self_profile";
import {handleUiV2ReportCard} from "./report_card";
import {handleUiV2DiscordNotifications} from "./discord_notifications";
import {handleUiV2VsLeadershipReport} from "./vs_leadership_report";
import {handleUiV2DiscordRosterUpdate} from "./discord_roster_update";
import {handleUiV2DiscordDesertStorm} from "./discord_desert_storm";
import {handleUiV2DiscordSetup} from "./discord_setup";
import {handleUiV2DiscordRankSync} from "./discord_rank_sync";
import {handleUiV2DiscordShieldReminders} from "./discord_shield_reminders";
import {handleUiV2DiscordOrphanAccess} from "./discord_orphan_access";
import {handleUiV2ImportCentre} from "./import_center";
import {handleUiV2IntegrationsKeys} from "./integrations_keys";
import {renderUiV2VsPerformance} from "./vs_performance";

export async function handleUiV2(request:Request,env:UiV2Env):Promise<Response|null>{
  const url=new URL(request.url);
  const branding=await handleUiV2Branding(request,env);
  if(branding)return branding;
  const playerManagement=url.pathname.startsWith("/ui-v2/players/import")||url.pathname==="/ui-v2/players/new"||url.pathname==="/ui-v2/players/access"||/^\/ui-v2\/players\/access\/\d+\/(?:approve|reject|block)$/.test(url.pathname)||/^\/ui-v2\/players\/\d+(?:\/(?:update|performance|deactivate|reactivate|disconnect|login-enable|login-disable|notes)|\/notes\/\d+\/(?:update|delete))?$/.test(url.pathname);
  const away=url.pathname==="/ui-v2/away"||/^\/ui-v2\/away\/\d+\/(?:update|cancel)$/.test(url.pathname);
  const events=url.pathname==="/ui-v2/events";
  const train=url.pathname==="/ui-v2/train"||url.pathname==="/ui-v2/train/delete";
  const vs=url.pathname==="/ui-v2/vs"||url.pathname==="/ui-v2/vs/performance";
  const ds=url.pathname.startsWith("/ui-v2/desert-storm");
  const shieldDrops=url.pathname==="/ui-v2/shield-drops"||url.pathname==="/ui-v2/shield-drops/delete";
  const backup=url.pathname==="/ui-v2/backup"||/^\/ui-v2\/backup\/(?:complete|excel|roster)$/.test(url.pathname);
  const importCentre=url.pathname.startsWith("/ui-v2/import-centre");
  const security=url.pathname==="/ui-v2/security"||url.pathname==="/ui-v2/security/groups"||url.pathname==="/ui-v2/security/owner-transfer"||/^\/ui-v2\/security\/(?:groups\/\d+(?:\/(?:delete|permissions|ranks|members(?:\/\d+\/remove)?))?|accounts\/\d+\/(?:administrator-add|administrator-remove)|blocks\/\d+\/unblock)$/.test(url.pathname);
  const settings=url.pathname==="/ui-v2/settings"||/^\/ui-v2\/settings\/(?:details|players|discord(?:\/(?:verify|disconnect))?)$/.test(url.pathname);
  const integrationsKeys=url.pathname.startsWith("/ui-v2/settings/integrations");
  const selfProfile=url.pathname==="/ui-v2/my-profile"||url.pathname==="/ui-v2/my-profile/performance"||url.pathname==="/ui-v2/my-profile/name"||url.pathname==="/ui-v2/player-changes"||/^\/ui-v2\/player-changes\/\d+\/(?:approve|reject)$/.test(url.pathname);
  const reportCard=url.pathname==="/ui-v2/report-card"||url.pathname==="/ui-v2/report-card/image.svg";
  const discordNotifications=url.pathname==="/ui-v2/settings/discord-notifications"||url.pathname==="/ui-v2/settings/discord-notifications/test"||url.pathname==="/ui-v2/vs/discord";
  const discordSetup=url.pathname==="/ui-v2/settings/discord-setup"||url.pathname==="/ui-v2/settings/discord-setup/create"||url.pathname==="/ui-v2/settings/discord-setup/identity";
  const discordRankSync=url.pathname==="/ui-v2/settings/discord-rank-sync";
  const discordShieldReminders=url.pathname==="/ui-v2/settings/discord-shield-reminders";
  const discordOrphanAccess=url.pathname==="/ui-v2/settings/discord-orphan-access";
  const vsLeadershipReport=url.pathname==="/ui-v2/vs/leadership-report"||url.pathname==="/ui-v2/vs/leadership-report/discord";
  const rosterUpdate=url.pathname==="/ui-v2/discord/roster-update"||url.pathname==="/ui-v2/discord/roster-update/post";
  const supported=(request.method==="GET"&&(url.pathname==="/ui-v2"||url.pathname==="/ui-v2/leadership"||url.pathname==="/ui-v2/intelligence"||reportCard||discordNotifications||discordSetup||discordRankSync||discordShieldReminders||discordOrphanAccess||vsLeadershipReport||rosterUpdate||url.pathname==="/ui-v2/players"||url.pathname==="/ui-v2/ranks"||url.pathname==="/ui-v2/audit"||selfProfile||away||events||train||vs||ds||shieldDrops||backup||importCentre||playerManagement||security||settings||integrationsKeys))||(request.method==="POST"&&(url.pathname==="/ui-v2/ranks"||discordNotifications||discordSetup||discordRankSync||discordShieldReminders||discordOrphanAccess||vsLeadershipReport||rosterUpdate||selfProfile||away||events||train||vs||ds||shieldDrops||backup||importCentre||playerManagement||security||settings||integrationsKeys));
  if(!supported)return null;

  const context=await loadUiV2Context(request,env);
  if(!context)return Response.redirect(new URL("/login",request.url),302);

  const securityResponse=await handleUiV2Security(request,env,context);
  if(securityResponse)return securityResponse;
  const integrationsKeysResponse=await handleUiV2IntegrationsKeys(request,env,context);
  if(integrationsKeysResponse)return integrationsKeysResponse;
  const selfProfileResponse=await handleUiV2SelfProfile(request,env,context);
  if(selfProfileResponse)return selfProfileResponse;
  const reportCardResponse=await handleUiV2ReportCard(request,env,context);
  if(reportCardResponse)return reportCardResponse;
  const discordNotificationResponse=await handleUiV2DiscordNotifications(request,env,context);
  if(discordNotificationResponse)return discordNotificationResponse;
  const discordSetupResponse=await handleUiV2DiscordSetup(request,env,context);
  if(discordSetupResponse)return discordSetupResponse;
  const discordRankSyncResponse=await handleUiV2DiscordRankSync(request,env,context);
  if(discordRankSyncResponse)return discordRankSyncResponse;
  const discordShieldResponse=await handleUiV2DiscordShieldReminders(request,env,context);
  if(discordShieldResponse)return discordShieldResponse;
  const discordOrphanResponse=await handleUiV2DiscordOrphanAccess(request,env,context);
  if(discordOrphanResponse)return discordOrphanResponse;
  const vsLeadershipReportResponse=await handleUiV2VsLeadershipReport(request,env,context);
  if(vsLeadershipReportResponse)return vsLeadershipReportResponse;
  const rosterUpdateResponse=await handleUiV2DiscordRosterUpdate(request,env,context);
  if(rosterUpdateResponse)return rosterUpdateResponse;
  const awayResponse=await handleUiV2Away(request,env,context);
  if(awayResponse)return awayResponse;
  const eventsResponse=await handleUiV2Events(request,env,context);
  if(eventsResponse)return eventsResponse;
  const trainResponse=await handleUiV2Train(request,env,context);
  if(trainResponse)return trainResponse;
  if(request.method==="GET"&&url.pathname==="/ui-v2/vs/performance")return renderUiV2VsPerformance(env,context);
  const vsResponse=await handleUiV2Vs(request,env,context);
  if(vsResponse)return vsResponse;
  const discordDesertStormResponse=await handleUiV2DiscordDesertStorm(request,env,context);
  if(discordDesertStormResponse)return discordDesertStormResponse;
  const dsResponse=await handleUiV2DesertStorm(request,env,context);
  if(dsResponse)return dsResponse;
  const shieldDropsResponse=await handleUiV2ShieldDrops(request,env,context);
  if(shieldDropsResponse)return shieldDropsResponse;
  const backupResponse=await handleUiV2Backup(request,env,context);
  if(backupResponse)return backupResponse;
  const importResponse=await handleUiV2ImportCentre(request,env,context);
  if(importResponse)return importResponse;
  if(request.method==="GET"&&url.pathname==="/ui-v2/audit")return renderUiV2Audit(env,context);
  const settingsResponse=await handleUiV2Settings(request,env,context);
  if(settingsResponse)return settingsResponse;
  const playerImport=await handleUiV2PlayerImport(request,env,context);
  if(playerImport)return playerImport;
  const management=await handleUiV2PlayerManagement(request,env,context);
  if(management)return management;
  if(request.method==="GET"&&url.pathname==="/ui-v2/players")return renderUiV2Players(env,context,url);
  if(request.method==="GET"&&url.pathname==="/ui-v2/leadership")return renderUiV2Leadership(env,context);
  if(request.method==="GET"&&url.pathname==="/ui-v2/intelligence")return renderUiV2Intelligence(env,context,url);
  if(url.pathname==="/ui-v2/ranks")return handleUiV2Ranks(request,env,context);

  return renderUiV2Console(env,context);
}
