import * as XLSX from "xlsx";
import {playerSameOrigin} from "../player_access";
import type {UiV2Context,UiV2Env} from "./context";
import {esc,renderUiV2Shell,uiV2Html} from "./shell";

type Player={id:number;display_name:string};
type VsRow={date:string;challenge:string;playerId:number|null;player:string;points:number|null;fingerprint:string;errors:string[];duplicate:boolean;noScore:boolean};
type VsPayload=Omit<VsRow,"errors"|"duplicate">;
type DsRow={date:string;team:"A"|"B"|"";playerId:number|null;player:string;selected:boolean;participated:boolean;opponent:string;ourScore:number|null;opponentScore:number|null;playerScore:number|null;fingerprint:string;errors:string[];duplicate:boolean};
type DsPayload=Omit<DsRow,"errors"|"duplicate">;
type Batch={id:number;public_id:string;dataset_type:string;file_name:string;status:string;row_count:number;imported_count:number;skipped_count:number;failed_count:number;created_at:string;rolled_back_at:string|null;created_by:string|null};
type Change={entity_key:string;before_json:string|null;after_json:string};
type StoredDay={challenge:string;target:number;scores:Array<{playerId:number;points:number}>};
type StoredDsEvent={battleTime:string|null;teamAOpponent:string;teamBOpponent:string;teamAScore:number|null;teamAEnemyScore:number|null;teamBScore:number|null;teamBEnemyScore:number|null;resultsFinalisedAt:string|null;players:Array<{playerId:number;team:string;selectionStatus:string;participated:number;playerScore:number|null}>};

const redirect=(r:Request,path:string)=>Response.redirect(new URL(path,r.url),303);
const normalHeader=(v:string)=>v.trim().toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," ");
const cell=(row:Record<string,unknown>,aliases:string[])=>{const wanted=new Set(aliases.map(normalHeader));for(const [key,value] of Object.entries(row))if(wanted.has(normalHeader(key)))return value;return ""};
const validDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(`${v}T12:00:00Z`));
const excelDate=(value:unknown)=>{if(value instanceof Date)return value.toISOString().slice(0,10);if(typeof value==="number"){const parsed=XLSX.SSF.parse_date_code(value);return parsed?`${parsed.y}-${String(parsed.m).padStart(2,"0")}-${String(parsed.d).padStart(2,"0")}`:""}const text=String(value??"").trim();if(validDate(text))return text;const parts=text.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{4})$/);return parts?`${parts[3]}-${parts[2].padStart(2,"0")}-${parts[1].padStart(2,"0")}`:""};
const points=(value:unknown)=>{const text=String(value??"").trim().replaceAll(",","").toUpperCase(),match=text.match(/^([0-9]+(?:\.[0-9]+)?)\s*([KMB])?$/);if(!match)return null;const factor=match[2]==="B"?1e9:match[2]==="M"?1e6:match[2]==="K"?1e3:1,result=Math.round(Number(match[1])*factor);return Number.isSafeInteger(result)&&result>=0?result:null};
const yes=(value:unknown)=>["yes","y","true","1"].includes(String(value??"").trim().toLowerCase());
const whole=(value:unknown)=>{const text=String(value??"").trim().replaceAll(",","");if(!text)return null;const n=Number(text);return Number.isSafeInteger(n)&&n>=0?n:null};
const weekday=(date:string)=>validDate(date)?new Intl.DateTimeFormat("en-GB",{weekday:"long",timeZone:"UTC"}).format(new Date(`${date}T12:00:00Z`)):"";
const fmt=(n:number|null)=>n===null?"—":n>=1e9?`${Number((n/1e9).toFixed(2))}B`:n>=1e6?`${Number((n/1e6).toFixed(2))}M`:n.toLocaleString("en-GB");
const digest=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,"0")).join("");

const css=`<style>.ic-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.ic-card{padding:20px;border:1px solid var(--ui-line);border-radius:15px;background:var(--ui-surface-2)}.ic-card h2{margin:0 0 7px;font-size:1.03rem}.ic-card p{margin:0;color:var(--ui-muted);font-size:.76rem;line-height:1.55}.ic-tag{display:inline-block;margin-bottom:10px;padding:5px 8px;border-radius:999px;background:var(--ui-surface-3);color:var(--ui-accent);font-size:.61rem;font-weight:900;text-transform:uppercase}.ic-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}.ic-button{display:inline-flex;align-items:center;justify-content:center;padding:10px 13px;border:0;border-radius:9px;background:var(--ui-button);color:var(--ui-button-text);font-size:.72rem;font-weight:900;text-decoration:none;cursor:pointer}.ic-button.secondary{border:1px solid var(--ui-line-strong);background:var(--ui-surface-3);color:var(--ui-navigation)}.ic-button.danger{border:1px solid color-mix(in srgb,var(--ui-danger) 45%,var(--ui-line));background:transparent;color:var(--ui-danger)}.ic-upload{display:grid;gap:12px}.ic-field span{display:block;margin-bottom:6px;color:var(--ui-secondary);font-size:.7rem;font-weight:850}.ic-field input{width:100%;padding:11px;border:1px solid var(--ui-line-strong);border-radius:9px;background:var(--ui-surface-3);color:var(--ui-text)}.ic-notice{margin-bottom:15px;padding:12px 14px;border:1px solid var(--ui-line);border-radius:11px;background:var(--ui-surface-2);color:var(--ui-muted);font-size:.76rem}.ic-notice.good{border-color:color-mix(in srgb,var(--ui-success) 42%,var(--ui-line));color:var(--ui-success)}.ic-notice.bad{border-color:color-mix(in srgb,var(--ui-danger) 42%,var(--ui-line));color:var(--ui-danger)}.ic-table-wrap{overflow:auto;border:1px solid var(--ui-line);border-radius:13px;background:var(--ui-surface-2)}.ic-table{width:100%;min-width:760px;border-collapse:collapse}.ic-table th,.ic-table td{padding:10px 11px;border-bottom:1px solid var(--ui-line);font-size:.71rem;text-align:left}.ic-table th{color:var(--ui-muted);font-size:.61rem;text-transform:uppercase}.ic-error{color:var(--ui-danger)}.ic-skip{color:var(--ui-warning)}.ic-history{display:grid;gap:9px;margin-top:17px}.ic-batch{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:13px;align-items:center;padding:14px;border:1px solid var(--ui-line);border-radius:12px;background:var(--ui-surface-2)}.ic-batch strong,.ic-batch span{display:block}.ic-batch span{margin-top:4px;color:var(--ui-muted);font-size:.67rem}.ic-empty{padding:22px;color:var(--ui-muted);text-align:center}@media(max-width:720px){.ic-grid{grid-template-columns:1fr}.ic-batch{grid-template-columns:1fr}.ic-actions{display:grid}.ic-button{width:100%}}</style>`;

const audit=(env:UiV2Env,context:UiV2Context,action:string,id:string,values:unknown)=>env.DB.prepare("INSERT INTO audit_log(public_id,actor_account_id,actor_display_name,action,entity_type,entity_id,source,new_values) VALUES(?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),context.user.accountId,context.user.displayName,action,"import_batch",id,"ui-v2-import-centre",JSON.stringify(values));

async function home(request:Request,env:UiV2Env,context:UiV2Context){
  const batches=(await env.DB.prepare("SELECT b.id,b.public_id,b.dataset_type,b.file_name,b.status,b.row_count,b.imported_count,b.skipped_count,b.failed_count,b.created_at,b.rolled_back_at,a.display_name created_by FROM import_batches b LEFT JOIN accounts a ON a.id=b.created_by_account_id ORDER BY b.created_at DESC,b.id DESC LIMIT 20").all<Batch>()).results??[];
  const state=new URL(request.url).searchParams.get("state"),notice=state==="imported"?'<div class="ic-notice good">Import completed. The batch can be reviewed or rolled back below.</div>':state==="rolled-back"?'<div class="ic-notice good">The import batch was rolled back successfully.</div>':state==="changed"?'<div class="ic-notice bad">Rollback stopped because the imported VS data has been edited since the import.</div>':"";
  const history=batches.map(b=>`<article class="ic-batch"><div><strong>${esc(b.file_name)}</strong><span>${b.dataset_type==="vs_history"?"VS history":b.dataset_type==="desert_storm_history"?"Desert Storm history":esc(b.dataset_type)} · ${b.imported_count} imported · ${b.skipped_count} skipped · ${esc(b.created_at)} · ${esc(b.created_by||"System")}${b.status==="rolled_back"?` · Rolled back ${esc(b.rolled_back_at||"")}`:""}</span></div>${b.status==="completed"?`<form method="post" action="/ui-v2/import-centre/${b.id}/rollback" data-confirm="Roll back this entire import batch? Later edits to imported data will prevent rollback." data-confirm-title="Roll back import" data-confirm-button="Roll back"><button class="ic-button danger" type="submit">Roll back batch</button></form>`:'<span class="ic-tag">Rolled back</span>'}</article>`).join("");
  const body=`${css}${notice}<div class="ic-grid"><article class="ic-card"><span class="ic-tag">Current data</span><h2>Player roster</h2><p>Use the existing roster preview to add, update or reactivate players before importing historical sheets.</p><div class="ic-actions"><a class="ic-button" href="/ui-v2/players/import">Open roster importer</a></div></article><article class="ic-card"><span class="ic-tag">Historical data</span><h2>VS performance history</h2><p>Blank and zero points are skipped as no participation. The weekday is used when the source has no Challenge column.</p><form class="ic-upload" method="post" action="/ui-v2/import-centre/vs/preview" enctype="multipart/form-data"><label class="ic-field"><span>VS Excel or CSV file</span><input type="file" name="file" accept=".xlsx,.csv" required></label><div class="ic-actions"><a class="ic-button secondary" href="/ui-v2/import-centre/vs/template.csv">Download template</a><button class="ic-button" type="submit">Preview VS history</button></div></form></article><article class="ic-card"><span class="ic-tag">Historical data</span><h2>Desert Storm history</h2><p>Import both teams, selections, substitutes, participation, opponents and individual points from the DS History tab.</p><form class="ic-upload" method="post" action="/ui-v2/import-centre/desert-storm/preview" enctype="multipart/form-data"><label class="ic-field"><span>Desert Storm Excel or CSV file</span><input type="file" name="file" accept=".xlsx,.csv" required></label><div class="ic-actions"><a class="ic-button secondary" href="/ui-v2/import-centre/desert-storm/template.csv">Download template</a><button class="ic-button" type="submit">Preview Desert Storm history</button></div></form></article></div><section class="ic-history"><h2>Import history</h2>${history||'<div class="ic-empty">No migration batches have been imported yet.</div>'}</section>`;
  return uiV2Html(renderUiV2Shell(context,{eyebrow:"Data Migration",title:"Import Centre",description:"Move existing alliance information into the platform safely, one dataset at a time.",body,activePath:"/ui-v2/import-centre",back:{href:"/ui-v2/leadership",label:"Leadership Console"}}));
}

async function parseVs(env:UiV2Env,file:File):Promise<VsRow[]>{
  if(file.size>8*1024*1024)throw new Error("The spreadsheet is larger than 8 MB.");
  if(!/\.(xlsx|csv)$/i.test(file.name))throw new Error("Use an .xlsx or .csv file.");
  const book=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true}),sheet=book.Sheets[book.SheetNames.find(name=>normalHeader(name)==="vs points")||book.SheetNames[0]];if(!sheet)throw new Error("The spreadsheet has no readable worksheet.");
  const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:"",raw:true});if(!raw.length)throw new Error("The spreadsheet contains no VS rows.");if(raw.length>5000)throw new Error("Import a maximum of 5,000 VS rows at a time.");
  const [players,fingerprints]=await Promise.all([env.DB.prepare("SELECT id,display_name FROM players ORDER BY display_name COLLATE NOCASE").all<Player>(),env.DB.prepare("SELECT fingerprint FROM import_row_fingerprints WHERE dataset_type='vs_history'").all<{fingerprint:string}>()]),byName=new Map((players.results??[]).map(p=>[p.display_name.trim().toLowerCase(),p])),known=new Set((fingerprints.results??[]).map(x=>x.fingerprint)),seen=new Set<string>();
  return Promise.all(raw.map(async source=>{const date=excelDate(cell(source,["date","competition date","vs date"])),supplied=String(cell(source,["challenge","challenge name","day","vs day"])).trim().replace(/\s+/g," ").slice(0,80),challenge=supplied||weekday(date),player=String(cell(source,["player","player name","name"])).trim(),matched=byName.get(player.toLowerCase())||null,score=points(cell(source,["points","score","vs points","player score"])),noScore=score===null||score===0,fingerprint=await digest(JSON.stringify([date,challenge.toLowerCase(),matched?.id??player.toLowerCase(),score])),errors:string[]=[];if(!noScore){if(!validDate(date))errors.push("Invalid or missing date");if(!challenge)errors.push("Challenge is required");if(!player)errors.push("Player is required");else if(!matched)errors.push("Player not found")}const duplicate=!noScore&&(known.has(fingerprint)||seen.has(fingerprint));if(!noScore)seen.add(fingerprint);return{date,challenge,playerId:matched?.id??null,player,points:score,fingerprint,errors,duplicate,noScore}}));
}

function vsPreview(context:UiV2Context,fileName:string,rows:VsRow[]){
  const bad=rows.some(x=>x.errors.length),ready=rows.filter(x=>!x.errors.length&&!x.duplicate&&!x.noScore).length,skipped=rows.length-ready,payload=esc(JSON.stringify({fileName,rows:rows.filter(x=>!x.noScore).map(({errors,duplicate,...row})=>row)}));
  const table=rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.date||"—")}</td><td>${esc(r.challenge||"—")}</td><td>${esc(r.player||"—")}</td><td>${fmt(r.points)}</td><td class="${r.errors.length?"ic-error":r.duplicate||r.noScore?"ic-skip":""}">${r.errors.length?esc(r.errors.join("; ")):r.noScore?"No score — skip":r.duplicate?"Already imported — skip":"Ready"}</td></tr>`).join("");
  const body=`${css}<div class="ic-notice ${bad?"bad":"good"}">${bad?"Nothing has been saved. Correct the invalid rows and upload the file again.":`${ready} rows are ready and ${skipped} no-score or duplicate rows will be skipped.`}</div><div class="ic-table-wrap"><table class="ic-table"><thead><tr><th>#</th><th>Date</th><th>Challenge</th><th>Player</th><th>Points</th><th>Validation</th></tr></thead><tbody>${table}</tbody></table></div><div class="ic-actions"><a class="ic-button secondary" href="/ui-v2/import-centre">Cancel</a>${bad||!ready?"":`<form method="post" action="/ui-v2/import-centre/vs/commit"><textarea name="payload" hidden>${payload}</textarea><button class="ic-button" type="submit">Import ${ready} VS rows</button></form>`}</div>`;
  return uiV2Html(renderUiV2Shell(context,{eyebrow:"Data Migration",title:"VS Import Preview",description:"Review the historic scores before changing platform data.",body,activePath:"/ui-v2/import-centre",back:{href:"/ui-v2/import-centre",label:"Import Centre"}}));
}

async function parseDs(env:UiV2Env,file:File):Promise<DsRow[]>{
  if(file.size>8*1024*1024)throw new Error("The spreadsheet is larger than 8 MB.");if(!/\.(xlsx|csv)$/i.test(file.name))throw new Error("Use an .xlsx or .csv file.");
  const book=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true}),sheet=book.Sheets[book.SheetNames.find(name=>normalHeader(name)==="ds history")||book.SheetNames[0]];if(!sheet)throw new Error("The spreadsheet has no readable worksheet.");const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:"",raw:true});if(!raw.length)throw new Error("The spreadsheet contains no Desert Storm rows.");if(raw.length>5000)throw new Error("Import a maximum of 5,000 Desert Storm rows at a time.");
  const [players,fingerprints]=await Promise.all([env.DB.prepare("SELECT id,display_name FROM players ORDER BY display_name COLLATE NOCASE").all<Player>(),env.DB.prepare("SELECT fingerprint FROM import_row_fingerprints WHERE dataset_type='desert_storm_history'").all<{fingerprint:string}>()]),byName=new Map((players.results??[]).map(p=>[p.display_name.trim().toLowerCase(),p])),known=new Set((fingerprints.results??[]).map(x=>x.fingerprint)),seen=new Set<string>();
  return Promise.all(raw.map(async source=>{const date=excelDate(cell(source,["event date","date","battle date"])),teamText=String(cell(source,["team"])).trim().toUpperCase(),team=teamText==="A"||teamText==="B"?teamText as "A"|"B":"",player=String(cell(source,["player","player name","name"])).trim(),matched=byName.get(player.toLowerCase())||null,selected=yes(cell(source,["selected"])),participated=yes(cell(source,["took part","participated","played"])),opponent=String(cell(source,["opponent","enemy"])).trim().replace(/\s+/g," ").slice(0,80),ourScore=whole(cell(source,["our score","alliance score"])),opponentScore=whole(cell(source,["opponent score","enemy score"])),playerScore=whole(cell(source,["individual points","player score","points"])),fingerprint=await digest(JSON.stringify([date,team,matched?.id??player.toLowerCase(),selected,participated,opponent.toLowerCase(),ourScore,opponentScore,playerScore])),errors:string[]=[];if(!validDate(date))errors.push("Invalid or missing date");if(!team)errors.push("Team must be A or B");if(!player)errors.push("Player is required");else if(!matched)errors.push("Player not found");if(!opponent)errors.push("Opponent is required");if(participated&&playerScore===null)errors.push("Participant points are required");const duplicate=known.has(fingerprint)||seen.has(fingerprint);seen.add(fingerprint);return{date,team,playerId:matched?.id??null,player,selected,participated,opponent,ourScore,opponentScore,playerScore,fingerprint,errors,duplicate}}));
}

function dsPreview(context:UiV2Context,fileName:string,rows:DsRow[]){const bad=rows.some(x=>x.errors.length),ready=rows.filter(x=>!x.errors.length&&!x.duplicate).length,skipped=rows.filter(x=>x.duplicate).length,payload=esc(JSON.stringify({fileName,rows:rows.map(({errors,duplicate,...row})=>row)})),table=rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.date||"—")}</td><td>${esc(r.team||"—")}</td><td>${esc(r.player||"—")}</td><td>${r.selected?"Selected":"Substitute"}</td><td>${r.participated?fmt(r.playerScore):"Did not play"}</td><td>${esc(r.opponent||"—")}</td><td class="${r.errors.length?"ic-error":r.duplicate?"ic-skip":""}">${r.errors.length?esc(r.errors.join("; ")):r.duplicate?"Already imported — skip":"Ready"}</td></tr>`).join("");const body=`${css}<div class="ic-notice ${bad?"bad":"good"}">${bad?"Nothing has been saved. Correct the invalid rows or player matches and upload again.":`${ready} rows are ready and ${skipped} exact duplicates will be skipped.`}</div><div class="ic-table-wrap"><table class="ic-table"><thead><tr><th>#</th><th>Date</th><th>Team</th><th>Player</th><th>Selection</th><th>Participation</th><th>Opponent</th><th>Validation</th></tr></thead><tbody>${table}</tbody></table></div><div class="ic-actions"><a class="ic-button secondary" href="/ui-v2/import-centre">Cancel</a>${bad||!ready?"":`<form method="post" action="/ui-v2/import-centre/desert-storm/commit"><textarea name="payload" hidden>${payload}</textarea><button class="ic-button" type="submit">Import ${ready} Desert Storm rows</button></form>`}</div>`;return uiV2Html(renderUiV2Shell(context,{eyebrow:"Data Migration",title:"Desert Storm Import Preview",description:"Review both teams and their historic participation before saving.",body,activePath:"/ui-v2/import-centre",back:{href:"/ui-v2/import-centre",label:"Import Centre"}}))}

async function currentDay(env:UiV2Env,date:string):Promise<StoredDay|null>{const day=await env.DB.prepare("SELECT challenge_name,daily_target FROM vs_days WHERE competition_date=?").bind(date).first<{challenge_name:string;daily_target:number}>();if(!day)return null;const scores=(await env.DB.prepare("SELECT player_id,points FROM vs_scores WHERE competition_date=? ORDER BY player_id").bind(date).all<{player_id:number;points:number}>()).results??[];return{challenge:day.challenge_name,target:day.daily_target,scores:scores.map(x=>({playerId:x.player_id,points:x.points}))}};
const sameDay=(a:StoredDay|null,b:StoredDay|null)=>JSON.stringify(a)===JSON.stringify(b);
async function currentDsEvent(env:UiV2Env,date:string):Promise<StoredDsEvent|null>{const event=await env.DB.prepare("SELECT id,battle_time,team_a_opponent,team_b_opponent,team_a_score,team_a_enemy_score,team_b_score,team_b_enemy_score,results_finalised_at FROM ds_events WHERE battle_date=?").bind(date).first<{id:number;battle_time:string|null;team_a_opponent:string;team_b_opponent:string;team_a_score:number|null;team_a_enemy_score:number|null;team_b_score:number|null;team_b_enemy_score:number|null;results_finalised_at:string|null}>();if(!event)return null;const players=(await env.DB.prepare("SELECT player_id,team,selection_status,participated,player_score FROM ds_event_players WHERE event_id=? ORDER BY player_id").bind(event.id).all<{player_id:number;team:string;selection_status:string;participated:number;player_score:number|null}>()).results??[];return{battleTime:event.battle_time,teamAOpponent:event.team_a_opponent,teamBOpponent:event.team_b_opponent,teamAScore:event.team_a_score,teamAEnemyScore:event.team_a_enemy_score,teamBScore:event.team_b_score,teamBEnemyScore:event.team_b_enemy_score,resultsFinalisedAt:event.results_finalised_at,players:players.map(x=>({playerId:x.player_id,team:x.team,selectionStatus:x.selection_status,participated:x.participated,playerScore:x.player_score}))}}
const sameDsEvent=(a:StoredDsEvent|null,b:StoredDsEvent|null)=>JSON.stringify(a)===JSON.stringify(b);

async function commitVs(request:Request,env:UiV2Env,context:UiV2Context){
  if(!playerSameOrigin(request,env))return new Response("Forbidden",{status:403});const form=await request.formData();let parsed:{fileName:string;rows:VsPayload[]};try{parsed=JSON.parse(String(form.get("payload")||""))}catch{return new Response("Invalid preview data",{status:400})}if(!parsed||!Array.isArray(parsed.rows)||!parsed.rows.length||parsed.rows.length>5000)return new Response("Invalid preview data",{status:400});
  const players=(await env.DB.prepare("SELECT id,display_name FROM players").all<Player>()).results??[],ids=new Set(players.map(p=>p.id)),existingFp=new Set((await env.DB.prepare("SELECT fingerprint FROM import_row_fingerprints WHERE dataset_type='vs_history'").all<{fingerprint:string}>()).results?.map(x=>x.fingerprint)??[]),seen=new Set<string>(),rows=parsed.rows.map(r=>({date:String(r.date),challenge:String(r.challenge).trim().slice(0,80),playerId:Number(r.playerId),player:String(r.player),points:Number(r.points),fingerprint:String(r.fingerprint)}));
  for(const row of rows){const expected=await digest(JSON.stringify([row.date,row.challenge.toLowerCase(),row.playerId,row.points]));if(!validDate(row.date)||!row.challenge||!ids.has(row.playerId)||!Number.isSafeInteger(row.points)||row.points<=0||row.fingerprint!==expected)return new Response("The preview no longer validates. Upload the file again.",{status:400})}
  const ready=rows.filter(r=>!existingFp.has(r.fingerprint)&&!seen.has(r.fingerprint)&&(seen.add(r.fingerprint),true));if(!ready.length)return redirect(request,"/ui-v2/import-centre");
  const dates=[...new Set(ready.map(r=>r.date))],targetRow=await env.DB.prepare("SELECT value FROM settings WHERE key='player_vs_daily_target'").first<{value:string}>(),target=Number(targetRow?.value||7200000),before=new Map<string,StoredDay|null>();for(const date of dates)before.set(date,await currentDay(env,date));
  const batch=await env.DB.prepare("INSERT INTO import_batches(public_id,dataset_type,file_name,row_count,imported_count,skipped_count,created_by_account_id) VALUES(?,?,?,?,?,?,?) RETURNING id,public_id").bind(crypto.randomUUID(),"vs_history",parsed.fileName.slice(0,255),rows.length,ready.length,rows.length-ready.length,context.user.accountId).first<{id:number;public_id:string}>();if(!batch)throw new Error("Import batch could not be created");
  for(const date of dates){const dateRows=ready.filter(r=>r.date===date),prior=before.get(date),merged=new Map((prior?.scores??[]).map(x=>[x.playerId,x.points]));dateRows.forEach(r=>merged.set(r.playerId,r.points));const challenge=dateRows[dateRows.length-1].challenge,after:StoredDay={challenge,target:prior?.target??target,scores:[...merged].map(([playerId,score])=>({playerId,points:score})).sort((a,b)=>a.playerId-b.playerId)},statements:D1PreparedStatement[]=[env.DB.prepare("INSERT INTO vs_days(competition_date,challenge_name,daily_target,updated_by_account_id,updated_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(competition_date) DO UPDATE SET challenge_name=excluded.challenge_name,daily_target=excluded.daily_target,updated_by_account_id=excluded.updated_by_account_id,updated_at=CURRENT_TIMESTAMP").bind(date,after.challenge,after.target,context.user.accountId),env.DB.prepare("DELETE FROM vs_scores WHERE competition_date=?").bind(date)];after.scores.forEach(x=>statements.push(env.DB.prepare("INSERT INTO vs_scores(competition_date,player_id,points) VALUES(?,?,?)").bind(date,x.playerId,x.points)));statements.push(env.DB.prepare("INSERT INTO import_batch_changes(batch_id,entity_type,entity_key,operation,before_json,after_json) VALUES(?,?,?,?,?,?)").bind(batch.id,"vs_day",date,prior?"update":"insert",prior?JSON.stringify(prior):null,JSON.stringify(after)));await env.DB.batch(statements)}
  await env.DB.batch([...ready.map(r=>env.DB.prepare("INSERT INTO import_row_fingerprints(dataset_type,fingerprint,batch_id) VALUES('vs_history',?,?)").bind(r.fingerprint,batch.id)),audit(env,context,"import.vs_history.completed",batch.public_id,{fileName:parsed.fileName,rows:rows.length,imported:ready.length,skipped:rows.length-ready.length,dates:dates.length})]);return redirect(request,"/ui-v2/import-centre?state=imported");
}

async function commitDs(request:Request,env:UiV2Env,context:UiV2Context){
  if(!playerSameOrigin(request,env))return new Response("Forbidden",{status:403});const form=await request.formData();let parsed:{fileName:string;rows:DsPayload[]};try{parsed=JSON.parse(String(form.get("payload")||""))}catch{return new Response("Invalid preview data",{status:400})}if(!parsed||!Array.isArray(parsed.rows)||!parsed.rows.length||parsed.rows.length>5000)return new Response("Invalid preview data",{status:400});
  const players=(await env.DB.prepare("SELECT id FROM players").all<{id:number}>()).results??[],ids=new Set(players.map(p=>p.id)),existingFp=new Set((await env.DB.prepare("SELECT fingerprint FROM import_row_fingerprints WHERE dataset_type='desert_storm_history'").all<{fingerprint:string}>()).results?.map(x=>x.fingerprint)??[]),seen=new Set<string>(),rows=parsed.rows.map(r=>({date:String(r.date),team:String(r.team) as "A"|"B",playerId:Number(r.playerId),player:String(r.player),selected:Boolean(r.selected),participated:Boolean(r.participated),opponent:String(r.opponent).trim().slice(0,80),ourScore:r.ourScore===null?null:Number(r.ourScore),opponentScore:r.opponentScore===null?null:Number(r.opponentScore),playerScore:r.playerScore===null?null:Number(r.playerScore),fingerprint:String(r.fingerprint)}));
  for(const row of rows){const expected=await digest(JSON.stringify([row.date,row.team,row.playerId,row.selected,row.participated,row.opponent.toLowerCase(),row.ourScore,row.opponentScore,row.playerScore]));if(!validDate(row.date)||!(["A","B"] as string[]).includes(row.team)||!ids.has(row.playerId)||!row.opponent||row.participated&&(!Number.isSafeInteger(row.playerScore)||Number(row.playerScore)<0)||row.fingerprint!==expected)return new Response("The preview no longer validates. Upload the file again.",{status:400})}
  const ready=rows.filter(r=>!existingFp.has(r.fingerprint)&&!seen.has(r.fingerprint)&&(seen.add(r.fingerprint),true));if(!ready.length)return redirect(request,"/ui-v2/import-centre");const dates=[...new Set(ready.map(r=>r.date))];for(const date of dates){const sourceRows=rows.filter(r=>r.date===date);if(!sourceRows.some(r=>r.team==="A")||!sourceRows.some(r=>r.team==="B"))return new Response(`Both teams are required for ${date}.`,{status:400})}const before=new Map<string,StoredDsEvent|null>();for(const date of dates)before.set(date,await currentDsEvent(env,date));
  const batch=await env.DB.prepare("INSERT INTO import_batches(public_id,dataset_type,file_name,row_count,imported_count,skipped_count,created_by_account_id) VALUES(?,?,?,?,?,?,?) RETURNING id,public_id").bind(crypto.randomUUID(),"desert_storm_history",parsed.fileName.slice(0,255),rows.length,ready.length,rows.length-ready.length,context.user.accountId).first<{id:number;public_id:string}>();if(!batch)throw new Error("Import batch could not be created");
  for(const date of dates){const eventRows=rows.filter(r=>r.date===date),prior=before.get(date),teamA=eventRows.find(r=>r.team==="A")!,teamB=eventRows.find(r=>r.team==="B")!,merged=new Map((prior?.players??[]).map(x=>[x.playerId,x]));eventRows.forEach(r=>merged.set(r.playerId,{playerId:r.playerId,team:r.team,selectionStatus:r.selected?"selected":"substitute",participated:r.participated?1:0,playerScore:r.participated?r.playerScore:null}));const finalised=eventRows.some(r=>r.ourScore!==null||r.opponentScore!==null),after:StoredDsEvent={battleTime:prior?.battleTime??null,teamAOpponent:teamA.opponent,teamBOpponent:teamB.opponent,teamAScore:teamA.ourScore,teamAEnemyScore:teamA.opponentScore,teamBScore:teamB.ourScore,teamBEnemyScore:teamB.opponentScore,resultsFinalisedAt:finalised?(prior?.resultsFinalisedAt||"imported"):null,players:[...merged.values()].sort((a,b)=>a.playerId-b.playerId)};let id=(await env.DB.prepare("SELECT id FROM ds_events WHERE battle_date=?").bind(date).first<{id:number}>())?.id;if(id)await env.DB.prepare("UPDATE ds_events SET team_a_opponent=?,team_b_opponent=?,team_a_score=?,team_a_enemy_score=?,team_b_score=?,team_b_enemy_score=?,results_finalised_at=?,updated_by_account_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(after.teamAOpponent,after.teamBOpponent,after.teamAScore,after.teamAEnemyScore,after.teamBScore,after.teamBEnemyScore,after.resultsFinalisedAt,context.user.accountId,id).run();else id=(await env.DB.prepare("INSERT INTO ds_events(battle_date,battle_time,team_a_opponent,team_b_opponent,team_a_score,team_a_enemy_score,team_b_score,team_b_enemy_score,results_finalised_at,updated_by_account_id) VALUES(?,?,?,?,?,?,?,?,?,?) RETURNING id").bind(date,after.battleTime,after.teamAOpponent,after.teamBOpponent,after.teamAScore,after.teamAEnemyScore,after.teamBScore,after.teamBEnemyScore,after.resultsFinalisedAt,context.user.accountId).first<{id:number}>())!.id;const statements:D1PreparedStatement[]=[env.DB.prepare("DELETE FROM ds_event_players WHERE event_id=?").bind(id)];after.players.forEach(x=>statements.push(env.DB.prepare("INSERT INTO ds_event_players(event_id,player_id,team,selection_status,participated,player_score) VALUES(?,?,?,?,?,?)").bind(id,x.playerId,x.team,x.selectionStatus,x.participated,x.playerScore)));statements.push(env.DB.prepare("INSERT INTO import_batch_changes(batch_id,entity_type,entity_key,operation,before_json,after_json) VALUES(?,?,?,?,?,?)").bind(batch.id,"ds_event",date,prior?"update":"insert",prior?JSON.stringify(prior):null,JSON.stringify(after)));await env.DB.batch(statements)}
  await env.DB.batch([...ready.map(r=>env.DB.prepare("INSERT INTO import_row_fingerprints(dataset_type,fingerprint,batch_id) VALUES('desert_storm_history',?,?)").bind(r.fingerprint,batch.id)),audit(env,context,"import.desert_storm_history.completed",batch.public_id,{fileName:parsed.fileName,rows:rows.length,imported:ready.length,skipped:rows.length-ready.length,events:dates.length})]);return redirect(request,"/ui-v2/import-centre?state=imported")
}

async function rollback(request:Request,env:UiV2Env,context:UiV2Context,id:number){
  if(!playerSameOrigin(request,env))return new Response("Forbidden",{status:403});const batch=await env.DB.prepare("SELECT id,public_id,status,dataset_type FROM import_batches WHERE id=?").bind(id).first<{id:number;public_id:string;status:string;dataset_type:string}>();if(!batch||batch.status!=="completed"||!["vs_history","desert_storm_history"].includes(batch.dataset_type))return new Response("Import batch cannot be rolled back",{status:400});const changes=(await env.DB.prepare("SELECT entity_key,before_json,after_json FROM import_batch_changes WHERE batch_id=? ORDER BY id DESC").bind(id).all<Change>()).results??[];
  if(batch.dataset_type==="vs_history")for(const change of changes){const current=await currentDay(env,change.entity_key),after=JSON.parse(change.after_json) as StoredDay;if(!sameDay(current,after))return redirect(request,"/ui-v2/import-centre?state=changed")}
  if(batch.dataset_type==="desert_storm_history")for(const change of changes){const current=await currentDsEvent(env,change.entity_key),after=JSON.parse(change.after_json) as StoredDsEvent;if(!sameDsEvent(current,after))return redirect(request,"/ui-v2/import-centre?state=changed")}
  if(batch.dataset_type==="vs_history")for(const change of changes){const before=change.before_json?JSON.parse(change.before_json) as StoredDay:null;if(!before){await env.DB.prepare("DELETE FROM vs_days WHERE competition_date=?").bind(change.entity_key).run();continue}const statements:D1PreparedStatement[]=[env.DB.prepare("UPDATE vs_days SET challenge_name=?,daily_target=?,updated_by_account_id=?,updated_at=CURRENT_TIMESTAMP WHERE competition_date=?").bind(before.challenge,before.target,context.user.accountId,change.entity_key),env.DB.prepare("DELETE FROM vs_scores WHERE competition_date=?").bind(change.entity_key)];before.scores.forEach(x=>statements.push(env.DB.prepare("INSERT INTO vs_scores(competition_date,player_id,points) VALUES(?,?,?)").bind(change.entity_key,x.playerId,x.points)));await env.DB.batch(statements)}
  if(batch.dataset_type==="desert_storm_history")for(const change of changes){const before=change.before_json?JSON.parse(change.before_json) as StoredDsEvent:null,event=await env.DB.prepare("SELECT id FROM ds_events WHERE battle_date=?").bind(change.entity_key).first<{id:number}>();if(!before){if(event)await env.DB.prepare("DELETE FROM ds_events WHERE id=?").bind(event.id).run();continue}if(!event)return redirect(request,"/ui-v2/import-centre?state=changed");const statements:D1PreparedStatement[]=[env.DB.prepare("UPDATE ds_events SET battle_time=?,team_a_opponent=?,team_b_opponent=?,team_a_score=?,team_a_enemy_score=?,team_b_score=?,team_b_enemy_score=?,results_finalised_at=?,updated_by_account_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(before.battleTime,before.teamAOpponent,before.teamBOpponent,before.teamAScore,before.teamAEnemyScore,before.teamBScore,before.teamBEnemyScore,before.resultsFinalisedAt,context.user.accountId,event.id),env.DB.prepare("DELETE FROM ds_event_players WHERE event_id=?").bind(event.id)];before.players.forEach(x=>statements.push(env.DB.prepare("INSERT INTO ds_event_players(event_id,player_id,team,selection_status,participated,player_score) VALUES(?,?,?,?,?,?)").bind(event.id,x.playerId,x.team,x.selectionStatus,x.participated,x.playerScore)));await env.DB.batch(statements)}
  await env.DB.batch([env.DB.prepare("DELETE FROM import_row_fingerprints WHERE batch_id=?").bind(id),env.DB.prepare("UPDATE import_batches SET status='rolled_back',rolled_back_by_account_id=?,rolled_back_at=CURRENT_TIMESTAMP WHERE id=?").bind(context.user.accountId,id),audit(env,context,"import.batch.rolled_back",batch.public_id,{dataset:batch.dataset_type,dates:changes.length})]);return redirect(request,"/ui-v2/import-centre?state=rolled-back");
}

export async function handleUiV2ImportCentre(request:Request,env:UiV2Env,context:UiV2Context):Promise<Response|null>{
  const path=new URL(request.url).pathname;if(!path.startsWith("/ui-v2/import-centre"))return null;if(!context.user.isOwner)return uiV2Html(renderUiV2Shell(context,{eyebrow:"Data Migration",title:"Import Centre",description:"Only the platform Owner can import or roll back historic alliance data.",body:"",activePath:"/ui-v2/import-centre"}),403);
  if(path==="/ui-v2/import-centre"&&request.method==="GET")return home(request,env,context);
  if(path==="/ui-v2/import-centre/vs/template.csv"&&request.method==="GET")return new Response("Competition Date,Challenge,Player Name,Points\n2026-09-14,Drone Boost,Example Player,12.5M\n",{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":"attachment; filename=vs-history-import-template.csv","cache-control":"no-store"}});
  if(path==="/ui-v2/import-centre/desert-storm/template.csv"&&request.method==="GET")return new Response("Event Date,Team,Player,Selected,Took Part,Opponent,Our Score,Opponent Score,Individual Points\n2026-09-18,A,Example Player,Yes,Yes,Example Enemy,500000,450000,125000\n",{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":"attachment; filename=desert-storm-history-import-template.csv","cache-control":"no-store"}});
  if(path==="/ui-v2/import-centre/vs/preview"&&request.method==="POST"){if(!playerSameOrigin(request,env))return new Response("Forbidden",{status:403});const form=await request.formData(),file=form.get("file");if(!(file instanceof File)||!file.size)return home(request,env,context);try{return vsPreview(context,file.name,await parseVs(env,file))}catch(error){return uiV2Html(renderUiV2Shell(context,{eyebrow:"Data Migration",title:"VS Import Error",description:error instanceof Error?error.message:"The spreadsheet could not be read.",body:`${css}<a class="ic-button" href="/ui-v2/import-centre">Return to Import Centre</a>`,activePath:"/ui-v2/import-centre"}),400)}}
  if(path==="/ui-v2/import-centre/vs/commit"&&request.method==="POST")return commitVs(request,env,context);
  if(path==="/ui-v2/import-centre/desert-storm/preview"&&request.method==="POST"){if(!playerSameOrigin(request,env))return new Response("Forbidden",{status:403});const form=await request.formData(),file=form.get("file");if(!(file instanceof File)||!file.size)return home(request,env,context);try{return dsPreview(context,file.name,await parseDs(env,file))}catch(error){return uiV2Html(renderUiV2Shell(context,{eyebrow:"Data Migration",title:"Desert Storm Import Error",description:error instanceof Error?error.message:"The spreadsheet could not be read.",body:`${css}<a class="ic-button" href="/ui-v2/import-centre">Return to Import Centre</a>`,activePath:"/ui-v2/import-centre"}),400)}}
  if(path==="/ui-v2/import-centre/desert-storm/commit"&&request.method==="POST")return commitDs(request,env,context);
  const match=path.match(/^\/ui-v2\/import-centre\/(\d+)\/rollback$/);if(match&&request.method==="POST")return rollback(request,env,context,Number(match[1]));return new Response("Not found",{status:404});
}
