import type {UiV2Context,UiV2Env} from "./context";
import {esc,renderUiV2Shell,uiV2Html} from "./shell";

type Player={id:number;display_name:string;rank:number|null};
type VsRow={player_id:number;total:number;days:number;hit_target:number;recent_average:number;earlier_average:number};
type DsRow={player_id:number;selected:number;participated:number;score:number};
type ShieldRow={player_id:number;drops:number};
type AwayRow={player_id:number;away_days:number};

const allowedWeeks=new Set([2,4,6,8,10]);
const compact=(value:number)=>value>=1_000_000_000?`${(value/1_000_000_000).toFixed(2).replace(/\.00$/,"")}B`:value>=1_000_000?`${(value/1_000_000).toFixed(1).replace(/\.0$/,"")}M`:value>=1_000?`${(value/1_000).toFixed(1).replace(/\.0$/,"")}K`:Math.round(value).toLocaleString("en-GB");
const londonToday=()=>{const parts=new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),part=(type:string)=>parts.find(item=>item.type===type)?.value||"";return `${part("year")}-${part("month")}-${part("day")}`};

const css=`<style>
.intel-filter{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:14px;padding:14px 16px;border:1px solid var(--ui-line);border-radius:13px;background:var(--ui-surface-2)}.intel-filter strong,.intel-filter span{display:block}.intel-filter span{margin-top:4px;color:var(--ui-muted);font-size:.72rem}.intel-filter form{display:flex;align-items:center;gap:8px}.intel-filter select{padding:9px 30px 9px 10px;border:1px solid var(--ui-line-strong);border-radius:9px;background:var(--ui-surface-3);color:var(--ui-text)}.intel-filter button{padding:9px 12px;border:0;border-radius:9px;background:var(--ui-button);color:var(--ui-button-text);font-weight:900}.intel-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px;margin-bottom:14px}.intel-stat{padding:15px;border:1px solid var(--ui-line);border-radius:12px;background:var(--ui-surface-2)}.intel-stat span,.intel-stat strong,.intel-stat small{display:block}.intel-stat span{color:var(--ui-muted);font-size:.64rem;font-weight:900;text-transform:uppercase}.intel-stat strong{margin-top:7px;font-size:1.45rem}.intel-stat small{margin-top:5px;color:var(--ui-secondary);font-size:.65rem}.intel-card{padding:18px;border:1px solid var(--ui-line);border-radius:14px;background:var(--ui-surface-2)}.intel-card h2{margin:0;font-size:1rem}.intel-card>p{margin:5px 0 15px;color:var(--ui-muted);font-size:.72rem;line-height:1.5}.intel-table-wrap{overflow-x:auto}.intel-table{width:100%;border-collapse:collapse;min-width:850px}.intel-table th,.intel-table td{padding:11px 9px;border-top:1px solid var(--ui-line);font-size:.7rem;text-align:right}.intel-table th{color:var(--ui-muted);font-size:.6rem;text-transform:uppercase}.intel-table th:first-child,.intel-table td:first-child{text-align:left}.intel-name strong,.intel-name span{display:block}.intel-name span{margin-top:3px;color:var(--ui-muted);font-size:.61rem}.intel-status{display:inline-flex;padding:5px 8px;border-radius:999px;background:var(--ui-surface-3);color:var(--ui-secondary);font-size:.59rem;font-weight:900;white-space:nowrap}.intel-status.good{color:var(--ui-success)}.intel-status.watch{color:var(--ui-warning)}.intel-status.away{color:var(--ui-accent)}.intel-empty{padding:32px;color:var(--ui-muted);text-align:center}@media(max-width:760px){.intel-filter{display:block}.intel-filter form{margin-top:12px}.intel-stats{grid-template-columns:1fr 1fr}}@media(max-width:430px){.intel-stats{grid-template-columns:1fr}}</style>`;

export async function renderUiV2Intelligence(env:UiV2Env,context:UiV2Context,url:URL){
  if(!context.user.canViewIntelligence)return new Response("Forbidden",{status:403});
  const requested=Number(url.searchParams.get("weeks")||4),weeks=allowedWeeks.has(requested)?requested:4,today=londonToday(),days=weeks*7,halfDays=Math.max(7,Math.floor(days/2)),modifier=`-${days-1} days`,recentModifier=`-${halfDays-1} days`;
  const [playerResult,vsResult,dsResult,shieldResult,awayResult]=await Promise.all([
    env.DB.prepare("SELECT id,display_name,rank FROM players WHERE is_active=1 ORDER BY display_name COLLATE NOCASE").all<Player>(),
    env.DB.prepare("SELECT s.player_id,SUM(s.points) total,COUNT(*) days,SUM(CASE WHEN s.points>=d.daily_target THEN 1 ELSE 0 END) hit_target,COALESCE(AVG(CASE WHEN s.competition_date>=date(?,?) THEN s.points END),0) recent_average,COALESCE(AVG(CASE WHEN s.competition_date<date(?,?) THEN s.points END),0) earlier_average FROM vs_scores s JOIN vs_days d ON d.competition_date=s.competition_date WHERE s.competition_date BETWEEN date(?,?) AND ? GROUP BY s.player_id").bind(today,recentModifier,today,recentModifier,today,modifier,today).all<VsRow>(),
    env.DB.prepare("SELECT ep.player_id,COUNT(*) selected,SUM(ep.participated) participated,COALESCE(SUM(CASE WHEN ep.participated=1 THEN ep.player_score ELSE 0 END),0) score FROM ds_event_players ep JOIN ds_events e ON e.id=ep.event_id WHERE e.battle_date BETWEEN date(?,?) AND ? GROUP BY ep.player_id").bind(today,modifier,today).all<DsRow>(),
    env.DB.prepare("SELECT player_id,COUNT(*) drops FROM shield_drop_incidents WHERE war_date BETWEEN date(?,?) AND ? GROUP BY player_id").bind(today,modifier,today).all<ShieldRow>(),
    env.DB.prepare("SELECT player_id,CAST(SUM(julianday(MIN(COALESCE(end_date,?),?))-julianday(MAX(start_date,date(?,?)))+1) AS INTEGER) away_days FROM player_away_periods WHERE cancelled_at IS NULL AND start_date<=? AND COALESCE(end_date,?)>=date(?,?) GROUP BY player_id").bind(today,today,today,modifier,today,today,today,modifier).all<AwayRow>()
  ]);
  const players=playerResult.results??[],vs=new Map((vsResult.results??[]).map(row=>[row.player_id,row])),ds=new Map((dsResult.results??[]).map(row=>[row.player_id,row])),shields=new Map((shieldResult.results??[]).map(row=>[row.player_id,row])),away=new Map((awayResult.results??[]).map(row=>[row.player_id,row]));
  const rows=players.map(player=>{const v=vs.get(player.id),d=ds.get(player.id),s=shields.get(player.id),a=away.get(player.id),awayDays=Number(a?.away_days||0),trend=v?.earlier_average&&v.recent_average?((v.recent_average-v.earlier_average)/v.earlier_average)*100:null;let label="Building data",tone="";if(awayDays){label=`Away ${awayDays}d`;tone="away"}else if((v?.days||0)>=3&&(v?.hit_target||0)>=(v?.days||0)*.7){label="Consistent";tone="good"}else if((s?.drops||0)>0||((d?.selected||0)>0&&(d?.participated||0)<(d?.selected||0))){label="Review context";tone="watch"}else if((v?.days||0)>=2){label="Active";tone="good"}return{player,v,d,s,awayDays,trend,label,tone}}).sort((a,b)=>{const priority=(x:typeof a)=>x.tone==="watch"?0:x.tone==="away"?1:x.tone==="good"?2:3;return priority(a)-priority(b)||a.player.display_name.localeCompare(b.player.display_name)});
  const totalVs=rows.reduce((sum,row)=>sum+Number(row.v?.total||0),0),dsPlayed=rows.reduce((sum,row)=>sum+Number(row.d?.participated||0),0),dropTotal=rows.reduce((sum,row)=>sum+Number(row.s?.drops||0),0),awayPlayers=rows.filter(row=>row.awayDays>0).length;
  const table=rows.length?`<div class="intel-table-wrap"><table class="intel-table"><thead><tr><th>Player</th><th>VS total</th><th>Days</th><th>Target hit</th><th>VS trend</th><th>DS played</th><th>DS score</th><th>Shield drops</th><th>Leadership view</th></tr></thead><tbody>${rows.map(row=>`<tr><td class="intel-name"><strong>${esc(row.player.display_name)}</strong><span>R${row.player.rank??"—"}${row.awayDays?` · ${row.awayDays} away ${row.awayDays===1?"day":"days"}`:""}</span></td><td>${compact(Number(row.v?.total||0))}</td><td>${row.v?.days||0}</td><td>${row.v?.hit_target||0}</td><td>${row.trend===null?"—":`${row.trend>=0?"+":""}${row.trend.toFixed(0)}%`}</td><td>${row.d?.participated||0}/${row.d?.selected||0}</td><td>${compact(Number(row.d?.score||0))}</td><td>${row.s?.drops||0}</td><td><span class="intel-status ${row.tone}">${esc(row.label)}</span></td></tr>`).join("")}</tbody></table></div>`:'<div class="intel-empty">No active players are available for analysis.</div>';
  const body=`${css}<div class="intel-filter"><div><strong>${weeks}-week leadership view</strong><span>${days} days ending ${esc(today)} · Away time is shown before any attention flag.</span></div><form method="get"><label for="weeks">Period</label><select id="weeks" name="weeks">${[2,4,6,8,10].map(value=>`<option value="${value}"${value===weeks?" selected":""}>${value} weeks</option>`).join("")}</select><button type="submit">Update</button></form></div><div class="intel-stats"><div class="intel-stat"><span>VS contribution</span><strong>${compact(totalVs)}</strong><small>All recorded player points</small></div><div class="intel-stat"><span>DS participation</span><strong>${dsPlayed}</strong><small>Completed player appearances</small></div><div class="intel-stat"><span>Shield incidents</span><strong>${dropTotal}</strong><small>Repeat drops included</small></div><div class="intel-stat"><span>Away players</span><strong>${awayPlayers}</strong><small>Availability considered first</small></div></div><section class="intel-card"><h2>Leadership Watch</h2><p>A factual comparison of recorded activity. “Review context” is a prompt to check circumstances, not an automatic judgement.</p>${table}</section>`;
  return uiV2Html(renderUiV2Shell(context,{eyebrow:"Analysis",title:"Intelligence Centre",description:"Compare contribution, participation, availability and war-day incidents without losing the human context.",body,activePath:"/ui-v2/intelligence",back:{href:"/ui-v2/leadership",label:"Leadership Console"}}));
}
