import {playerSameOrigin} from "../player_access";
import type {UiV2Context,UiV2Env} from "./context";
import {esc,renderUiV2Shell,uiV2Html} from "./shell";

type Player={id:number;display_name:string;is_active:number};
type ExtractedRow={player_name:string;points_text:string;confidence:"high"|"medium"|"low";notes:string};
type OpenAiResponse={output?:Array<{content?:Array<{type?:string;text?:string}>}>;error?:{message?:string}};

const css=`<style>.si-grid{display:grid;gap:14px}.si-card{padding:20px;border:1px solid var(--ui-line);border-radius:15px;background:var(--ui-surface-2)}.si-card h2{margin:0 0 8px}.si-card p{margin:0;color:var(--ui-muted);font-size:.77rem;line-height:1.55}.si-form{display:grid;gap:14px}.si-fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}.si-field span{display:block;margin-bottom:6px;color:var(--ui-secondary);font-size:.7rem;font-weight:850}.si-field input,.si-field select,.si-table input,.si-table select{width:100%;padding:10px;border:1px solid var(--ui-line-strong);border-radius:9px;background:var(--ui-surface-3);color:var(--ui-text)}.si-table-wrap{overflow:auto;border:1px solid var(--ui-line);border-radius:13px}.si-table{width:100%;min-width:760px;border-collapse:collapse}.si-table th,.si-table td{padding:10px;border-bottom:1px solid var(--ui-line);font-size:.71rem;text-align:left}.si-table th{color:var(--ui-muted);font-size:.61rem;text-transform:uppercase}.si-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}.si-button{display:inline-flex;align-items:center;justify-content:center;padding:10px 13px;border:0;border-radius:9px;background:var(--ui-button);color:var(--ui-button-text);font-size:.72rem;font-weight:900;text-decoration:none;cursor:pointer}.si-button.secondary{border:1px solid var(--ui-line-strong);background:var(--ui-surface-3);color:var(--ui-navigation)}.si-notice{padding:12px 14px;border:1px solid var(--ui-line);border-radius:11px;background:var(--ui-surface-2);color:var(--ui-muted);font-size:.76rem}.si-notice.bad{border-color:color-mix(in srgb,var(--ui-danger) 42%,var(--ui-line));color:var(--ui-danger)}.si-confidence{font-weight:850;text-transform:capitalize}.si-confidence.low{color:var(--ui-danger)}.si-confidence.medium{color:var(--ui-warning)}@media(max-width:720px){.si-fields{grid-template-columns:1fr}.si-actions{display:grid}.si-button{width:100%}}</style>`;
const normalName=(value:string)=>value.trim().toLocaleLowerCase().replace(/\s+/g," ");
const validDate=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T12:00:00Z`));
const points=(value:string)=>{const clean=value.trim().replaceAll(",","").toUpperCase();if(!clean)return 0;const match=clean.match(/^([0-9]+(?:\.[0-9]+)?)\s*([KMB])?$/);if(!match)return null;const factor=match[2]==="B"?1e9:match[2]==="M"?1e6:match[2]==="K"?1e3:1,result=Math.round(Number(match[1])*factor);return Number.isSafeInteger(result)&&result>=0?result:null};
const digest=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,"0")).join("");
const imageDataUrl=async(file:File)=>{const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return `data:${file.type};base64,${btoa(binary)}`};

function page(context:UiV2Context,message=""){
  const body=`${css}${message}<div class="si-grid"><article class="si-card"><h2>VS daily scores</h2><p>Upload the leaderboard screenshots for one VS day. The images are read by OpenAI, then you review every player and score before anything is saved. Blank and zero scores count as no participation and are skipped.</p><form class="si-form" method="post" action="/ui-v2/import-centre/screenshots/vs/extract" enctype="multipart/form-data"><div class="si-fields"><label class="si-field"><span>VS competition date</span><input type="date" name="competition_date" required></label><label class="si-field"><span>VS challenge</span><input name="challenge" maxlength="80" placeholder="e.g. Drone Boost" required></label></div><label class="si-field"><span>Leaderboard screenshots (up to 10)</span><input type="file" name="screenshots" accept="image/png,image/jpeg,image/webp" multiple required></label><div class="si-actions"><button class="si-button" type="submit">Read screenshots</button><a class="si-button secondary" href="/ui-v2/import-centre">Back to Import Centre</a></div></form></article><article class="si-card"><h2>Coming next</h2><p>Weekly roster, Total Hero Power, Desert Storm selection and Desert Storm fight scores will use this same review-first workflow. Alliance Train and Shield Drop are intentionally excluded.</p></article></div>`;
  return uiV2Html(renderUiV2Shell(context,{eyebrow:"AI-assisted data entry",title:"Screenshot Import",description:"Turn game screenshots into checked, editable platform data.",body,activePath:"/ui-v2/import-centre",back:{href:"/ui-v2/import-centre",label:"Import Centre"}}));
}

async function playersAndAliases(env:UiV2Env){const [playerRows,aliasRows]=await Promise.all([env.DB.prepare("SELECT id,display_name,is_active FROM players ORDER BY is_active DESC,display_name COLLATE NOCASE").all<Player>(),env.DB.prepare("SELECT alias_normalized,player_id FROM player_name_aliases").all<{alias_normalized:string;player_id:number}>()]),players=playerRows.results??[],map=new Map(players.map(player=>[normalName(player.display_name),player.id]));for(const alias of aliasRows.results??[])map.set(alias.alias_normalized,alias.player_id);return{players,map}}

async function extractVs(env:UiV2Env,files:File[]){
  if(!env.OPENAI_API_KEY)throw new Error("Screenshot importing is not configured yet. Add the OPENAI_API_KEY Cloudflare secret first.");
  if(!files.length||files.length>10)throw new Error("Choose between 1 and 10 screenshots.");
  let total=0;for(const file of files){total+=file.size;if(!["image/png","image/jpeg","image/webp"].includes(file.type))throw new Error("Use PNG, JPEG or WebP screenshots.");if(file.size>8*1024*1024)throw new Error(`${file.name} is larger than 8 MB.`)}if(total>24*1024*1024)throw new Error("The screenshots are larger than 24 MB in total.");
  const images=await Promise.all(files.map(async file=>({type:"input_image",image_url:await imageDataUrl(file),detail:"high"})));
  const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${env.OPENAI_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:env.OPENAI_VISION_MODEL||"gpt-4.1-mini",store:false,input:[{role:"user",content:[{type:"input_text",text:"Read these Last War VS alliance leaderboard screenshots. Extract every visible player row and its VS score. Preserve player names exactly as shown. Score text may use commas or K/M/B suffixes. Include zero scores; never invent cropped or unreadable values. If the same player overlaps across screenshots, return that player once using the clearest reading."},...images]}],text:{format:{type:"json_schema",name:"vs_screenshot_rows",strict:true,schema:{type:"object",additionalProperties:false,properties:{rows:{type:"array",items:{type:"object",additionalProperties:false,properties:{player_name:{type:"string"},points_text:{type:"string"},confidence:{type:"string",enum:["high","medium","low"]},notes:{type:"string"}},required:["player_name","points_text","confidence","notes"]}}},required:["rows"]}}}})});
  const result=await response.json() as OpenAiResponse;if(!response.ok)throw new Error(result.error?.message||"OpenAI could not read the screenshots.");const text=result.output?.flatMap(item=>item.content??[]).find(item=>item.type==="output_text")?.text;if(!text)throw new Error("OpenAI returned no readable VS rows.");let parsed:{rows:ExtractedRow[]};try{parsed=JSON.parse(text)}catch{throw new Error("OpenAI returned an invalid screenshot result.")}if(!Array.isArray(parsed.rows)||!parsed.rows.length||parsed.rows.length>300)throw new Error("No usable VS rows were found in the screenshots.");return parsed.rows;
}

async function extractionPreview(env:UiV2Env,context:UiV2Context,date:string,challenge:string,files:File[]){
  if(!validDate(date)||!challenge.trim())throw new Error("Choose the VS competition date and enter the challenge.");const [rows,lookup]=await Promise.all([extractVs(env,files),playersAndAliases(env)]);
  const table=rows.map((row,index)=>{const matched=lookup.map.get(normalName(row.player_name));return `<tr><td>${index+1}</td><td>${esc(row.player_name)}</td><td><select name="player_id_${index}" required><option value="">Choose player…</option>${lookup.players.map(player=>`<option value="${player.id}"${player.id===matched?" selected":""}>${esc(player.display_name)}${player.is_active?"":" · Former"}</option>`).join("")}</select>${matched?"":'<div class="si-confidence low">No automatic match</div>'}</td><td><input name="points_${index}" value="${esc(row.points_text)}" placeholder="Blank = no score"></td><td><span class="si-confidence ${row.confidence}">${esc(row.confidence)}</span>${row.notes?`<div>${esc(row.notes)}</div>`:""}</td></tr>`}).join("");
  const body=`${css}<div class="si-notice">OpenAI has only prepared this preview. Check every name and score, especially medium or low-confidence readings. Nothing has been saved.</div><form method="post" action="/ui-v2/import-centre/screenshots/vs/validate"><input type="hidden" name="competition_date" value="${esc(date)}"><input type="hidden" name="challenge" value="${esc(challenge.trim())}"><input type="hidden" name="row_count" value="${rows.length}"><input type="hidden" name="file_names" value="${esc(files.map(file=>file.name).join(", "))}"><div class="si-table-wrap"><table class="si-table"><thead><tr><th>#</th><th>Read from image</th><th>Matched player</th><th>VS score</th><th>Confidence</th></tr></thead><tbody>${table}</tbody></table></div><div class="si-actions"><a class="si-button secondary" href="/ui-v2/import-centre/screenshots">Cancel</a><button class="si-button" type="submit">Validate scores</button></div></form>`;
  return uiV2Html(renderUiV2Shell(context,{eyebrow:"AI-assisted data entry",title:"Check VS Screenshot Results",description:`${date} · ${challenge.trim()} · ${rows.length} extracted rows`,body,activePath:"/ui-v2/import-centre",back:{href:"/ui-v2/import-centre/screenshots",label:"Screenshot Import"}}));
}

async function validatedPreview(request:Request,env:UiV2Env,context:UiV2Context){
  const form=await request.formData(),date=String(form.get("competition_date")||""),challenge=String(form.get("challenge")||"").trim(),count=Number(form.get("row_count")),fileNames=String(form.get("file_names")||"VS screenshots");if(!validDate(date)||!challenge||!Number.isInteger(count)||count<1||count>300)return new Response("The screenshot preview is no longer valid.",{status:400});const playerRows=(await env.DB.prepare("SELECT id,display_name FROM players").all<{id:number;display_name:string}>()).results??[],players=new Map(playerRows.map(player=>[player.id,player.display_name])),rows=[] as Array<{date:string;challenge:string;playerId:number;player:string;points:number;fingerprint:string;noScore:boolean}>,invalid:string[]=[];
  const seenPlayers=new Set<number>();for(let index=0;index<count;index++){const playerId=Number(form.get(`player_id_${index}`)),score=points(String(form.get(`points_${index}`)||""));if(!players.has(playerId)){invalid.push(`Row ${index+1}: choose a player.`);continue}if(seenPlayers.has(playerId)){invalid.push(`Row ${index+1}: ${players.get(playerId)} appears more than once.`);continue}seenPlayers.add(playerId);if(score===null){invalid.push(`Row ${index+1}: enter a valid score.`);continue}rows.push({date,challenge,playerId,player:players.get(playerId)!,points:score,fingerprint:await digest(JSON.stringify([date,challenge.toLowerCase(),playerId,score])),noScore:score===0})}
  if(invalid.length){const body=`${css}<div class="si-notice bad">${invalid.map(esc).join("<br>")}</div><div class="si-actions"><a class="si-button" href="/ui-v2/import-centre/screenshots">Upload screenshots again</a></div>`;return uiV2Html(renderUiV2Shell(context,{eyebrow:"AI-assisted data entry",title:"VS Screenshot Validation",description:"Nothing has been saved.",body,activePath:"/ui-v2/import-centre"}),400)}const scored=rows.filter(row=>!row.noScore),payload=esc(JSON.stringify({fileName:`Screenshot import: ${fileNames}`.slice(0,255),rows})),table=rows.map((row,index)=>`<tr><td>${index+1}</td><td>${esc(row.player)}</td><td>${row.points.toLocaleString("en-GB")}</td><td>${row.noScore?"No score — skip":"Ready"}</td></tr>`).join(""),body=`${css}<div class="si-notice">${scored.length} scores are ready. ${rows.length-scored.length} blank/zero scores will be treated as no participation and skipped.</div><div class="si-table-wrap"><table class="si-table"><thead><tr><th>#</th><th>Player</th><th>VS score</th><th>Validation</th></tr></thead><tbody>${table}</tbody></table></div><div class="si-actions"><a class="si-button secondary" href="/ui-v2/import-centre/screenshots">Cancel</a>${scored.length?`<form method="post" action="/ui-v2/import-centre/vs/commit"><textarea name="payload" hidden>${payload}</textarea><button class="si-button" type="submit">Import ${scored.length} VS scores</button></form>`:""}</div>`;return uiV2Html(renderUiV2Shell(context,{eyebrow:"AI-assisted data entry",title:"Confirm VS Screenshot Import",description:`${date} · ${challenge}`,body,activePath:"/ui-v2/import-centre",back:{href:"/ui-v2/import-centre/screenshots",label:"Screenshot Import"}}));
}

export async function handleUiV2ScreenshotImport(request:Request,env:UiV2Env,context:UiV2Context):Promise<Response|null>{
  const path=new URL(request.url).pathname;if(!path.startsWith("/ui-v2/import-centre/screenshots"))return null;if(!context.user.isOwner)return new Response("Forbidden",{status:403});if(path==="/ui-v2/import-centre/screenshots"&&request.method==="GET")return page(context,!env.OPENAI_API_KEY?'<div class="si-notice bad">Screenshot reading needs an OpenAI API key before it can be used.</div>':"");if(path==="/ui-v2/import-centre/screenshots/vs/extract"&&request.method==="POST"){if(!playerSameOrigin(request,env))return new Response("Forbidden",{status:403});const form=await request.formData(),files=form.getAll("screenshots").filter((item):item is File=>item instanceof File&&item.size>0);try{return await extractionPreview(env,context,String(form.get("competition_date")||""),String(form.get("challenge")||""),files)}catch(error){return page(context,`<div class="si-notice bad">${esc(error instanceof Error?error.message:"The screenshots could not be read.")}</div>`)}}if(path==="/ui-v2/import-centre/screenshots/vs/validate"&&request.method==="POST"){if(!playerSameOrigin(request,env))return new Response("Forbidden",{status:403});return validatedPreview(request,env,context)}return new Response("Not found",{status:404});
}
