import {playerSameOrigin} from "../player_access";
import type {UiV2Context,UiV2Env} from "./context";
import {esc,renderUiV2Shell,uiV2Html} from "./shell";

type Player={id:number;display_name:string};
type Day={competition_date:string;challenge_name:string;daily_target:number;total:number;participants:number;hit_target:number};
type Score={display_name:string;points:number};
const redirect=(r:Request,p:string)=>Response.redirect(new URL(p,r.url),303);
const power=(raw:string)=>{const clean=raw.trim().replaceAll(",","").toUpperCase(),match=clean.match(/^([0-9]+(?:\.[0-9]+)?)\s*([KMB])?$/);if(!match)return null;const factor=match[2]==="B"?1e9:match[2]==="M"?1e6:match[2]==="K"?1e3:1,value=Math.round(Number(match[1])*factor);return Number.isSafeInteger(value)&&value>=0?value:null};
const fmt=(n:number)=>n>=1e9?`${(n/1e9).toFixed(2).replace(/0+$/,"").replace(/\.$/,"")}B`:n>=1e6?`${(n/1e6).toFixed(1).replace(/\.0$/,"")}M`:n.toLocaleString("en-GB");
const validDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(`${v}T12:00:00Z`));
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());

const css=`<style>.vs-notice{margin-bottom:15px;padding:12px 14px;border:1px solid color-mix(in srgb,var(--ui-success) 45%,var(--ui-line));border-radius:11px;background:color-mix(in srgb,var(--ui-success) 9%,var(--ui-surface-2));color:var(--ui-success);font-size:.8rem;font-weight:850}.vs-layout{display:grid;grid-template-columns:minmax(330px,.85fr) minmax(0,1.4fr);gap:15px}.vs-card{padding:18px;border:1px solid var(--ui-line);border-radius:14px;background:var(--ui-surface-2)}.vs-card h2{margin:0 0 6px;font-size:1rem}.vs-card>p{margin:0 0 15px;color:var(--ui-muted);font-size:.78rem;line-height:1.5}.vs-form{display:grid;gap:11px}.vs-pair{display:grid;grid-template-columns:1fr 1fr;gap:10px}.vs-field span{display:block;margin-bottom:6px;color:var(--ui-muted);font-size:.67rem;font-weight:850}.vs-field input,.vs-field textarea{width:100%;padding:10px 11px;border:1px solid var(--ui-line-strong);border-radius:9px;background:var(--ui-surface-3);color:var(--ui-text)}.vs-field textarea{min-height:220px;resize:vertical;font-family:ui-monospace,monospace;font-size:.76rem;line-height:1.5}.vs-save{padding:11px 14px;border:0;border-radius:9px;background:var(--ui-button);color:var(--ui-button-text);font-size:.77rem;font-weight:950}.vs-days{display:grid;gap:10px}.vs-day{padding:14px;border:1px solid var(--ui-line);border-radius:11px;background:var(--ui-surface-3)}.vs-day-head,.vs-stats{display:flex;align-items:center;justify-content:space-between;gap:12px}.vs-day-head strong{font-size:.86rem}.vs-day-head span{color:var(--ui-accent);font-size:.68rem;font-weight:850}.vs-stats{margin-top:10px;padding-top:10px;border-top:1px solid var(--ui-line)}.vs-stat span,.vs-stat strong{display:block}.vs-stat span{color:var(--ui-muted);font-size:.59rem;text-transform:uppercase}.vs-stat strong{margin-top:3px;font-size:.76rem}.vs-scores{display:grid;margin-top:10px}.vs-score{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-top:1px solid var(--ui-line);font-size:.7rem}.vs-score span:last-child{font-weight:900}.vs-empty{padding:28px;color:var(--ui-muted);text-align:center}@media(max-width:850px){.vs-layout{grid-template-columns:1fr}}@media(max-width:560px){.vs-pair,.vs-stats{display:grid;grid-template-columns:1fr 1fr}.vs-day-head{align-items:flex-start}}</style>`;

async function load(env:UiV2Env){
  const [players,days]=(await Promise.all([env.DB.prepare("SELECT id,display_name FROM players WHERE is_active=1 ORDER BY display_name COLLATE NOCASE").all<Player>(),env.DB.prepare("SELECT d.competition_date,d.challenge_name,d.daily_target,COALESCE(SUM(s.points),0) total,COUNT(s.player_id) participants,COALESCE(SUM(CASE WHEN s.points>=d.daily_target THEN 1 ELSE 0 END),0) hit_target FROM vs_days d LEFT JOIN vs_scores s ON s.competition_date=d.competition_date GROUP BY d.competition_date ORDER BY d.competition_date DESC LIMIT 14").all<Day>()]));
  return {players:players.results??[],days:days.results??[]};
}
async function page(request:Request,env:UiV2Env,context:UiV2Context,message=""){
  if(!context.user.canManageVs)return uiV2Html(renderUiV2Shell(context,{eyebrow:"Competition",title:"VS Battle Centre",description:"You do not have permission to manage VS results.",body:"",activePath:"/ui-v2/vs"}),403);
  const {days}=await load(env),[targetRow,discordRows,postRows]=await Promise.all([env.DB.prepare("SELECT value FROM settings WHERE key='player_vs_daily_target'").first<{value:string}>(),env.DB.prepare("SELECT key,value FROM settings WHERE key IN ('discord_alliance_channel_id','discord_vs_enabled')").all<{key:string;value:string}>(),env.DB.prepare("SELECT source_key FROM discord_notification_posts WHERE notification_type='vs'").all<{source_key:string}>()]),currentTarget=Number(targetRow?.value||7200000),scoresByDate=new Map<string,Score[]>(),discord=Object.fromEntries((discordRows.results??[]).map(row=>[row.key,row.value])),posted=new Set((postRows.results??[]).map(row=>row.source_key));
  for(const day of days.slice(0,4))scoresByDate.set(day.competition_date,(await env.DB.prepare("SELECT p.display_name,s.points FROM vs_scores s JOIN players p ON p.id=s.player_id WHERE s.competition_date=? ORDER BY s.points DESC LIMIT 5").bind(day.competition_date).all<Score>()).results??[]);
  const discordAction=(day:Day)=>posted.has(day.competition_date)?'<div class="vs-notice">Posted to Discord</div>':discord.discord_vs_enabled==="1"&&discord.discord_alliance_channel_id?`<form method="post" action="/ui-v2/vs/discord"><input type="hidden" name="competition_date" value="${esc(day.competition_date)}"><button class="vs-save" type="submit">Post this day to Discord</button></form>`:"";
  const cards=days.map((day,index)=>`<article class="vs-day"><div class="vs-day-head"><strong>${esc(day.challenge_name)}</strong><span>${esc(day.competition_date)}</span></div><div class="vs-stats"><div class="vs-stat"><span>Alliance total</span><strong>${fmt(day.total)}</strong></div><div class="vs-stat"><span>Players entered</span><strong>${day.participants}</strong></div><div class="vs-stat"><span>Over ${fmt(day.daily_target)}</span><strong>${day.hit_target}</strong></div></div>${index<4?`<div class="vs-scores">${(scoresByDate.get(day.competition_date)||[]).map(score=>`<div class="vs-score"><span>${esc(score.display_name)}</span><span>${fmt(score.points)}</span></div>`).join("")}</div>`:""}${discordAction(day)}</article>`).join("");
  const discordMessage=new URL(request.url).searchParams.get("discord"),feedback=discordMessage==="posted"?"VS contribution posted to Discord.":discordMessage==="duplicate"?"That VS date has already been posted.":discordMessage==="disabled"?"Discord VS posting is not enabled.":discordMessage==="failed"?"Discord could not receive the message. Your VS results are unchanged.":message;
  const leadershipReport=context.user.canViewIntelligence?'<div class="vs-notice"><a href="/ui-v2/vs/leadership-report">Preview private VS Leadership Report →</a></div>':"";
  const body=`${css}${feedback?`<div class="vs-notice">${esc(feedback)}</div>`:""}${leadershipReport}<div class="vs-layout"><section class="vs-card"><h2>Enter daily results</h2><p>Use the VS competition date, even when entering the scores the following day. The current player target is <strong>${fmt(currentTarget)}</strong> and is controlled in Player Settings.</p><form class="vs-form" method="post" action="/ui-v2/vs"><label class="vs-field"><span>Competition date</span><input type="date" name="competition_date" value="${today()}" required></label><label class="vs-field"><span>Challenge</span><input name="challenge_name" maxlength="80" placeholder="e.g. Hero Advancement" required></label><label class="vs-field"><span>Player scores — one per line</span><textarea name="scores" placeholder="IceBite, 12.5M&#10;Biggus Duckus, 9.8M" required></textarea></label><button class="vs-save" type="submit">Save VS results</button></form></section><section class="vs-card"><h2>Recent competition days</h2><p>The latest results feed the front-page VS card automatically.</p><div class="vs-days">${cards||'<div class="vs-empty">No VS results have been recorded yet.</div>'}</div></section></div>`;
  return uiV2Html(renderUiV2Shell(context,{eyebrow:"Competition",title:"VS Battle Centre",description:"Record daily player contribution against the alliance target.",body,activePath:"/ui-v2/vs",back:{href:"/ui-v2/leadership",label:"Leadership Console"}}));
}
async function save(request:Request,env:UiV2Env,context:UiV2Context){
  if(!context.user.canManageVs||!playerSameOrigin(request,env))return new Response("Forbidden",{status:403});
  const form=await request.formData(),date=String(form.get("competition_date")||""),challenge=String(form.get("challenge_name")||"").trim().replace(/\s+/g," ").slice(0,80),targetRow=await env.DB.prepare("SELECT value FROM settings WHERE key='player_vs_daily_target'").first<{value:string}>(),target=Number(targetRow?.value||7200000),raw=String(form.get("scores")||"");
  if(!validDate(date)||!challenge||target===null||target<1)return page(request,env,context,"Nothing saved: check the date, challenge and target.");
  const players=(await env.DB.prepare("SELECT id,display_name FROM players WHERE is_active=1").all<Player>()).results??[],byName=new Map(players.map(p=>[p.display_name.trim().toLowerCase(),p])),parsed:Array<{player:Player;points:number}>=[],errors:string[]=[];
  raw.split(/\r?\n/).map(line=>line.trim()).filter(Boolean).forEach((line,index)=>{const match=line.match(/^(.+?)[,\t]\s*([^,\t]+)$/);if(!match){errors.push(`Line ${index+1} needs Player, Points`);return}const player=byName.get(match[1].trim().toLowerCase()),points=power(match[2]);if(!player)errors.push(`Line ${index+1}: player not found`);else if(points===null)errors.push(`Line ${index+1}: invalid points`);else if(points>0)parsed.push({player,points})});
  if(errors.length||!parsed.length||new Set(parsed.map(x=>x.player.id)).size!==parsed.length)return page(request,env,context,`Nothing saved: ${errors[0]||"remove duplicate players and try again."}`);
  const before=(await env.DB.prepare("SELECT player_id,points FROM vs_scores WHERE competition_date=?").bind(date).all()).results??[],statements:D1PreparedStatement[]=[env.DB.prepare("INSERT INTO vs_days (competition_date,challenge_name,daily_target,updated_by_account_id,updated_at) VALUES (?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(competition_date) DO UPDATE SET challenge_name=excluded.challenge_name,daily_target=excluded.daily_target,updated_by_account_id=excluded.updated_by_account_id,updated_at=CURRENT_TIMESTAMP").bind(date,challenge,target,context.user.accountId),env.DB.prepare("DELETE FROM vs_scores WHERE competition_date=?").bind(date)];
  parsed.forEach(row=>statements.push(env.DB.prepare("INSERT INTO vs_scores (competition_date,player_id,points) VALUES (?,?,?)").bind(date,row.player.id,row.points)));
  statements.push(env.DB.prepare("INSERT INTO audit_log (public_id,actor_account_id,actor_display_name,action,entity_type,entity_id,source,old_values,new_values) VALUES (?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),context.user.accountId,context.user.displayName,"vs.results.saved","vs_day",date,"ui-v2-vs",JSON.stringify(before),JSON.stringify({challenge,target,players:parsed.length,total:parsed.reduce((sum,row)=>sum+row.points,0)})));
  await env.DB.batch(statements);return redirect(request,"/ui-v2/vs?saved=1");
}
export async function handleUiV2Vs(request:Request,env:UiV2Env,context:UiV2Context):Promise<Response|null>{if(new URL(request.url).pathname!=="/ui-v2/vs")return null;if(request.method==="GET")return page(request,env,context,new URL(request.url).searchParams.get("saved")==="1"?"VS results saved.":"");if(request.method==="POST")return save(request,env,context);return new Response("Method not allowed",{status:405})}
