import {playerSameOrigin} from "../player_access";
import type {UiV2Context,UiV2Env} from "./context";
import {esc,renderUiV2Shell,uiV2Html} from "./shell";

type Week={week_start:string};
type Player={id:number;display_name:string};
type Day={competition_date:string;daily_target:number};
type Score={player_id:number;competition_date:string;points:number};
type Away={player_id:number;start_date:string;end_date:string|null};
type Setting={key:string;value:string};
type ReportRow={name:string;eligible:number;hits:number;away:number;total:number;rate:number;category:"watch"|"below"|"attention"|"no_score"|"good"|"away"};
type Report={weeks:number;weekStarts:string[];periodStart:string;periodEnd:string;rows:ReportRow[];sourceKey:string};

const allowedWeeks=new Set([2,4,6,8,10]);
const redirect=(request:Request,path:string)=>Response.redirect(new URL(path,request.url),303);
const fmt=(value:number)=>value>=1e9?(value/1e9).toFixed(2).replace(/0+$/,"").replace(/\.$/,"")+"B":value>=1e6?(value/1e6).toFixed(1).replace(/\.0$/,"")+"M":value.toLocaleString("en-GB");
const addDays=(date:string,days:number)=>{const value=new Date(`${date}T12:00:00Z`);value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10)};
const status=(rate:number):ReportRow["category"]=>rate>=.75?"good":rate>=.6?"watch":rate>=.45?"below":"attention";
const label=(category:ReportRow["category"])=>category==="watch"?"Watch":category==="below"?"Below Expectation":category==="attention"?"Needs Attention":category==="no_score"?"No Score":category==="away"?"Away Excluded":"Strong";
const detail=(row:ReportRow)=>`${row.name} · ${row.hits}/${row.eligible} targets${row.away?` · ${row.away} away`:""}`;

async function buildReport(env:UiV2Env,weeks:number):Promise<Report|null>{
  const weekRows=(await env.DB.prepare("SELECT date(competition_date,'weekday 0','-6 days') week_start FROM vs_days WHERE CAST(strftime('%w',competition_date) AS INTEGER) BETWEEN 1 AND 6 GROUP BY week_start HAVING COUNT(DISTINCT competition_date)>=6 ORDER BY week_start DESC LIMIT ?").bind(weeks).all<Week>()).results??[];
  if(!weekRows.length)return null;
  const weekStarts=weekRows.map(row=>row.week_start),periodStart=weekStarts.at(-1)!,periodEnd=addDays(weekStarts[0],5);
  const [playerResult,dayResult,scoreResult,awayResult]=await Promise.all([
    env.DB.prepare("SELECT id,display_name FROM players WHERE is_active=1 ORDER BY display_name COLLATE NOCASE").all<Player>(),
    env.DB.prepare("SELECT competition_date,daily_target FROM vs_days WHERE competition_date BETWEEN ? AND ? ORDER BY competition_date").bind(periodStart,periodEnd).all<Day>(),
    env.DB.prepare("SELECT player_id,competition_date,points FROM vs_scores WHERE competition_date BETWEEN ? AND ?").bind(periodStart,periodEnd).all<Score>(),
    env.DB.prepare("SELECT player_id,start_date,end_date FROM player_away_periods WHERE cancelled_at IS NULL AND start_date<=? AND COALESCE(end_date,?)>=?").bind(periodEnd,periodEnd,periodStart).all<Away>()
  ]);
  const validDates=new Set(weekStarts.flatMap(start=>Array.from({length:6},(_,index)=>addDays(start,index)))),days=(dayResult.results??[]).filter(day=>validDates.has(day.competition_date)),scores=new Map((scoreResult.results??[]).map(score=>[`${score.player_id}|${score.competition_date}`,score.points])),away=awayResult.results??[];
  const rows=(playerResult.results??[]).map(player=>{let eligible=0,hits=0,awayDays=0,total=0;for(const day of days){const isAway=away.some(period=>period.player_id===player.id&&period.start_date<=day.competition_date&&(!period.end_date||period.end_date>=day.competition_date));if(isAway){awayDays++;continue}eligible++;const points=Number(scores.get(`${player.id}|${day.competition_date}`)||0);total+=points;if(points>=day.daily_target)hits++}const rate=eligible?hits/eligible:0,category:ReportRow["category"]=eligible===0?"away":total===0?"no_score":status(rate);return{name:player.display_name,eligible,hits,away:awayDays,total,rate,category}});
  return{weeks:weekRows.length,weekStarts,periodStart,periodEnd,rows,sourceKey:`${weekRows.length}:${weekStarts.join(",")}`};
}

const css=`<style>.vlr-note{margin-bottom:14px;padding:12px 14px;border:1px solid var(--ui-line);border-radius:10px;background:var(--ui-surface-2);color:var(--ui-secondary)}.vlr-toolbar{display:flex;align-items:end;justify-content:space-between;gap:14px;margin-bottom:14px;padding:15px;border:1px solid var(--ui-line);border-radius:13px;background:var(--ui-surface-2)}.vlr-toolbar span,.vlr-field span{display:block;margin-bottom:6px;color:var(--ui-muted);font-size:.7rem;font-weight:850}.vlr-toolbar form{display:flex;align-items:end;gap:9px}.vlr-toolbar select{padding:10px;border:1px solid var(--ui-line-strong);border-radius:9px;background:var(--ui-surface-3);color:var(--ui-text)}.vlr-button{padding:10px 14px;border:0;border-radius:9px;background:var(--ui-button);color:var(--ui-button-text);font-weight:900;cursor:pointer}.vlr-button[disabled]{opacity:.5;cursor:not-allowed}.vlr-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.vlr-card{padding:17px;border:1px solid var(--ui-line);border-radius:13px;background:var(--ui-surface-2)}.vlr-card h2{margin:0;font-size:.95rem}.vlr-card>p{margin:5px 0 12px;color:var(--ui-muted);font-size:.7rem}.vlr-row{display:flex;justify-content:space-between;gap:12px;padding:9px 0;border-top:1px solid var(--ui-line);font-size:.72rem}.vlr-row span:last-child{color:var(--ui-muted);text-align:right}.vlr-empty{padding:13px 0;color:var(--ui-muted);font-size:.72rem}.vlr-post{margin-top:14px;padding:17px;border:1px solid var(--ui-line);border-radius:13px;background:var(--ui-surface-2)}.vlr-post h2{margin:0 0 5px;font-size:.95rem}.vlr-post p{margin:0 0 13px;color:var(--ui-muted);font-size:.72rem;line-height:1.5}@media(max-width:700px){.vlr-toolbar{display:block}.vlr-toolbar form{margin-top:12px}.vlr-grid{grid-template-columns:1fr}}</style>`;

async function page(request:Request,env:UiV2Env,context:UiV2Context){
  if(!context.user.canManageVs||!context.user.canViewIntelligence)return new Response("Forbidden",{status:403});
  const url=new URL(request.url),requested=Number(url.searchParams.get("weeks")||4),weeks=allowedWeeks.has(requested)?requested:4,report=await buildReport(env,weeks),feedback=url.searchParams.get("discord"),note=feedback==="posted"?"Leadership report posted to Discord.":feedback==="duplicate"?"This leadership report has already been posted.":feedback==="disabled"?"Choose a private Leadership channel in Discord Notifications first.":feedback==="failed"?"Discord could not receive the report. Nothing else was changed.":"";
  let content='<div class="vlr-note">No completed VS weeks are available yet. A completed week needs results for Monday through Saturday.</div>';
  if(report){const posted=await env.DB.prepare("SELECT posted_at FROM discord_notification_posts WHERE notification_type='vs_leadership' AND source_key=?").bind(report.sourceKey).first<{posted_at:string}>(),categories:ReportRow["category"][]=["watch","below","attention","no_score"],cards=categories.map(category=>{const rows=report.rows.filter(row=>row.category===category);return `<section class="vlr-card"><h2>${esc(label(category))} · ${rows.length}</h2><p>${category==="no_score"?"No recorded points across eligible days.":"Target-hit rate across eligible days."}</p>${rows.length?rows.map(row=>`<div class="vlr-row"><strong>${esc(row.name)}</strong><span>${row.hits}/${row.eligible} targets · ${fmt(row.total)}</span></div>`).join(""):'<div class="vlr-empty">No players in this category.</div>'}</section>`}).join(""),awayCount=report.rows.filter(row=>row.category==="away").length,excludedDays=report.rows.reduce((sum,row)=>sum+row.away,0);content=`<div class="vlr-toolbar"><div><strong>${report.weeks} completed VS ${report.weeks===1?"week":"weeks"}</strong><span>${esc(report.periodStart)} to ${esc(report.periodEnd)} · ${excludedDays} declared away ${excludedDays===1?"day":"days"} excluded · ${awayCount} fully away</span></div><form method="get"><label class="vlr-field"><span>Period</span><select name="weeks">${[2,4,6,8,10].map(value=>`<option value="${value}"${value===weeks?" selected":""}>${value} weeks</option>`).join("")}</select></label><button class="vlr-button">Preview</button></form></div><div class="vlr-grid">${cards}</div><section class="vlr-post"><h2>Private Leadership channel</h2><p>Only the four attention categories above are posted. Strong and Excellent players are omitted; declared away days are excluded before the status is calculated.</p>${posted?`<div class="vlr-note">Already posted on ${esc(posted.posted_at)}.</div>`:`<form method="post" action="/ui-v2/vs/leadership-report/discord"><input type="hidden" name="weeks" value="${weeks}"><input type="hidden" name="source_key" value="${esc(report.sourceKey)}"><button class="vlr-button" type="submit">Post Leadership Report to Discord</button></form>`}</section>`}
  const body=`${css}${note?`<div class="vlr-note">${esc(note)}</div>`:""}${content}`;
  return uiV2Html(renderUiV2Shell(context,{eyebrow:"Competition",title:"VS Leadership Report",description:"Preview the private attention report before posting it to the Leadership Discord channel.",body,activePath:"/ui-v2/vs",back:{href:"/ui-v2/vs",label:"VS Battle Centre"}}));
}

async function post(request:Request,env:UiV2Env,context:UiV2Context){
  if(!context.user.canManageVs||!context.user.canViewIntelligence||!playerSameOrigin(request,env))return new Response("Forbidden",{status:403});
  const form=await request.formData(),requested=Number(form.get("weeks")||4),weeks=allowedWeeks.has(requested)?requested:4,report=await buildReport(env,weeks);if(!report)return new Response("No completed VS weeks",{status:400});
  const supplied=String(form.get("source_key")||"");if(supplied!==report.sourceKey)return redirect(request,`/ui-v2/vs/leadership-report?weeks=${weeks}`);
  const existing=await env.DB.prepare("SELECT id FROM discord_notification_posts WHERE notification_type='vs_leadership' AND source_key=?").bind(report.sourceKey).first();if(existing)return redirect(request,`/ui-v2/vs/leadership-report?weeks=${weeks}&discord=duplicate`);
  const config=Object.fromEntries(((await env.DB.prepare("SELECT key,value FROM settings WHERE key='discord_leadership_channel_id'").all<Setting>()).results??[]).map(row=>[row.key,row.value]));if(!config.discord_leadership_channel_id)return redirect(request,`/ui-v2/vs/leadership-report?weeks=${weeks}&discord=disabled`);
  const categories:ReportRow["category"][]=["watch","below","attention","no_score"],fields=categories.map(category=>{const rows=report.rows.filter(row=>row.category===category),value=rows.length?rows.map(detail).join("\n").slice(0,1024):"None";return{name:`${label(category)} · ${rows.length}`,value,inline:false}}),excluded=report.rows.reduce((sum,row)=>sum+row.away,0);
  try{const response=await fetch(`https://discord.com/api/v10/channels/${config.discord_leadership_channel_id}/messages`,{method:"POST",headers:{authorization:`Bot ${env.DISCORD_BOT_TOKEN||""}`,"content-type":"application/json"},body:JSON.stringify({embeds:[{title:"Private VS Leadership Report",description:`**${report.weeks} completed VS weeks** · ${report.periodStart} to ${report.periodEnd}\n${excluded} declared away ${excluded===1?"day":"days"} excluded before classification.`,color:0xd7a83e,fields,footer:{text:`${context.alliance.name} · Leadership only`}}]})});if(!response.ok)throw new Error(`Discord message ${response.status}`);const message=await response.json<{id:string}>();await env.DB.batch([env.DB.prepare("INSERT INTO discord_notification_posts(notification_type,source_key,channel_id,discord_message_id,posted_by_account_id) VALUES('vs_leadership',?,?,?,?)").bind(report.sourceKey,config.discord_leadership_channel_id,message.id,context.user.accountId),env.DB.prepare("INSERT INTO audit_log(public_id,actor_account_id,actor_display_name,action,entity_type,entity_id,source,new_values) VALUES(?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),context.user.accountId,context.user.displayName,"discord.vs_leadership.posted","discord_notifications",report.sourceKey,"ui-v2-discord",JSON.stringify({weeks:report.weeks,periodStart:report.periodStart,periodEnd:report.periodEnd,channel:config.discord_leadership_channel_id,messageId:message.id}))]);return redirect(request,`/ui-v2/vs/leadership-report?weeks=${weeks}&discord=posted`)}catch(error){console.error(error);return redirect(request,`/ui-v2/vs/leadership-report?weeks=${weeks}&discord=failed`)}
}

export async function handleUiV2VsLeadershipReport(request:Request,env:UiV2Env,context:UiV2Context):Promise<Response|null>{const path=new URL(request.url).pathname;if(path==="/ui-v2/vs/leadership-report")return request.method==="GET"?page(request,env,context):new Response("Method not allowed",{status:405});if(path==="/ui-v2/vs/leadership-report/discord")return request.method==="POST"?post(request,env,context):new Response("Method not allowed",{status:405});return null}
