import type {UiV2Context,UiV2Env} from "./context";
import {esc,renderUiV2Shell,uiV2Html} from "./shell";

type PlayerStat={id:number;display_name:string;is_active:number;days:number;total:number;average:number;target_hits:number;best_score:number;last_date:string};
type DayStat={competition_date:string;challenge_name:string;daily_target:number;total:number;participants:number;target_hits:number;top_score:number};
type Summary={days:number;total:number;entries:number;players:number;target_hits:number};
const fmt=(value:number)=>value>=1e9?`${Number((value/1e9).toFixed(2))}B`:value>=1e6?`${Number((value/1e6).toFixed(2))}M`:value.toLocaleString("en-GB");
const css=`<style>
.vsp-summary{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin-bottom:16px}.vsp-stat{padding:14px;border:1px solid var(--ui-line);border-radius:12px;background:var(--ui-surface-2)}.vsp-stat span,.vsp-stat strong{display:block}.vsp-stat span{color:var(--ui-muted);font-size:.61rem;font-weight:900;text-transform:uppercase}.vsp-stat strong{margin-top:6px;font-size:1.15rem}.vsp-toolbar{display:grid;grid-template-columns:minmax(220px,1fr) auto;gap:10px;margin-bottom:14px}.vsp-search{padding:11px 12px;border:1px solid var(--ui-line-strong);border-radius:9px;background:var(--ui-surface-3);color:var(--ui-text)}.vsp-filters{display:flex;gap:6px}.vsp-filter{padding:10px 12px;border:1px solid var(--ui-line-strong);border-radius:9px;background:var(--ui-surface-3);color:var(--ui-navigation);font-size:.7rem;font-weight:900}.vsp-filter.active{border-color:var(--ui-hover);color:var(--ui-hover)}.vsp-card{margin-top:15px;padding:18px;border:1px solid var(--ui-line);border-radius:14px;background:var(--ui-surface-2)}.vsp-card h2{margin:0 0 13px;font-size:1rem}.vsp-table-wrap{overflow:auto}.vsp-table{width:100%;min-width:790px;border-collapse:collapse}.vsp-table th,.vsp-table td{padding:10px;border-top:1px solid var(--ui-line);font-size:.7rem;text-align:right;white-space:nowrap}.vsp-table th{color:var(--ui-muted);font-size:.59rem;text-transform:uppercase}.vsp-table th:first-child,.vsp-table td:first-child{text-align:left}.vsp-player strong,.vsp-player span{display:block}.vsp-player span{margin-top:3px;color:var(--ui-muted);font-size:.61rem}.vsp-former{color:var(--ui-warning)!important}.vsp-empty{padding:24px;color:var(--ui-muted);text-align:center}@media(max-width:850px){.vsp-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.vsp-stat:last-child{grid-column:1/-1}}@media(max-width:600px){.vsp-toolbar{grid-template-columns:1fr}.vsp-filters{display:grid;grid-template-columns:repeat(3,1fr)}}
</style>`;

export async function renderUiV2VsPerformance(env:UiV2Env,context:UiV2Context){
  if(!context.user.canViewVs&&!context.user.canManageVs)return uiV2Html(renderUiV2Shell(context,{eyebrow:"VS History",title:"VS Performance",description:"You do not have permission to view VS statistics.",body:"",activePath:"/ui-v2/vs/performance"}),403);
  const [playersResult,daysResult,summary]=await Promise.all([
    env.DB.prepare("SELECT p.id,p.display_name,p.is_active,COUNT(s.competition_date) days,COALESCE(SUM(s.points),0) total,COALESCE(AVG(s.points),0) average,COALESCE(SUM(CASE WHEN s.points>=d.daily_target THEN 1 ELSE 0 END),0) target_hits,COALESCE(MAX(s.points),0) best_score,MAX(s.competition_date) last_date FROM players p JOIN vs_scores s ON s.player_id=p.id JOIN vs_days d ON d.competition_date=s.competition_date GROUP BY p.id,p.display_name,p.is_active ORDER BY total DESC,p.display_name COLLATE NOCASE").all<PlayerStat>(),
    env.DB.prepare("SELECT d.competition_date,d.challenge_name,d.daily_target,COALESCE(SUM(s.points),0) total,COUNT(s.player_id) participants,COALESCE(SUM(CASE WHEN s.points>=d.daily_target THEN 1 ELSE 0 END),0) target_hits,COALESCE(MAX(s.points),0) top_score FROM vs_days d LEFT JOIN vs_scores s ON s.competition_date=d.competition_date GROUP BY d.competition_date,d.challenge_name,d.daily_target ORDER BY d.competition_date DESC").all<DayStat>(),
    env.DB.prepare("SELECT COUNT(DISTINCT d.competition_date) days,COALESCE(SUM(s.points),0) total,COUNT(s.player_id) entries,COUNT(DISTINCT s.player_id) players,COALESCE(SUM(CASE WHEN s.points>=d.daily_target THEN 1 ELSE 0 END),0) target_hits FROM vs_days d LEFT JOIN vs_scores s ON s.competition_date=d.competition_date").first<Summary>()
  ]),players=playersResult.results??[],days=daysResult.results??[];
  const playerRows=players.map((player,index)=>`<tr data-vsp-row data-status="${player.is_active?"active":"former"}" data-search="${esc(player.display_name.toLowerCase())}"><td class="vsp-player"><strong>${index+1}. ${esc(player.display_name)}</strong><span class="${player.is_active?"":"vsp-former"}">${player.is_active?"Active player":"Former player"}</span></td><td>${player.days}</td><td>${fmt(player.total)}</td><td>${fmt(Math.round(player.average))}</td><td>${player.target_hits}</td><td>${fmt(player.best_score)}</td><td>${esc(player.last_date)}</td></tr>`).join("");
  const dayRows=days.map(day=>`<tr><td><strong>${esc(day.competition_date)}</strong><br><span>${esc(day.challenge_name)}</span></td><td>${fmt(day.total)}</td><td>${day.participants}</td><td>${day.target_hits}</td><td>${fmt(day.daily_target)}</td><td>${fmt(day.top_score)}</td></tr>`).join("");
  const body=`${css}<div class="vsp-summary"><div class="vsp-stat"><span>VS days</span><strong>${summary?.days??0}</strong></div><div class="vsp-stat"><span>Total contribution</span><strong>${fmt(summary?.total??0)}</strong></div><div class="vsp-stat"><span>Score entries</span><strong>${summary?.entries??0}</strong></div><div class="vsp-stat"><span>Players recorded</span><strong>${summary?.players??0}</strong></div><div class="vsp-stat"><span>Target hits</span><strong>${summary?.target_hits??0}</strong></div></div><section class="vsp-card"><h2>Player performance history</h2><div class="vsp-toolbar"><input class="vsp-search" type="search" placeholder="Search active or former players…" data-vsp-search><div class="vsp-filters"><button class="vsp-filter active" type="button" data-vsp-filter="all">All</button><button class="vsp-filter" type="button" data-vsp-filter="active">Active</button><button class="vsp-filter" type="button" data-vsp-filter="former">Former</button></div></div><div class="vsp-table-wrap"><table class="vsp-table"><thead><tr><th>Player</th><th>Days</th><th>Total</th><th>Average</th><th>Target hits</th><th>Best day</th><th>Last score</th></tr></thead><tbody>${playerRows||'<tr><td colspan="7" class="vsp-empty">No VS scores have been imported yet.</td></tr>'}</tbody></table></div></section><section class="vsp-card"><h2>Competition day history</h2><div class="vsp-table-wrap"><table class="vsp-table"><thead><tr><th>Date & challenge</th><th>Alliance total</th><th>Players</th><th>Target hits</th><th>Target</th><th>Top score</th></tr></thead><tbody>${dayRows||'<tr><td colspan="6" class="vsp-empty">No competition days have been imported yet.</td></tr>'}</tbody></table></div></section><script>(()=>{const search=document.querySelector('[data-vsp-search]'),rows=[...document.querySelectorAll('[data-vsp-row]')],buttons=[...document.querySelectorAll('[data-vsp-filter]')];let filter='all';const apply=()=>{const term=(search?.value||'').trim().toLowerCase();rows.forEach(row=>row.hidden=!(filter==='all'||row.dataset.status===filter)||!(row.dataset.search||'').includes(term))};search?.addEventListener('input',apply);buttons.forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.vspFilter;buttons.forEach(item=>item.classList.toggle('active',item===button));apply()}))})();</script>`;
  return uiV2Html(renderUiV2Shell(context,{eyebrow:"VS History",title:"VS Performance",description:"Complete contribution history across active and former alliance players.",body,activePath:"/ui-v2/vs/performance",back:{href:"/ui-v2/vs",label:"VS Battle Centre"}}));
}
