import app from "./leadership_access";
import {playerActor,playerPermitted} from "./player_access";
import {leadershipHeader,leadershipShellCss,leadershipEsc} from "./leadership_shell";

interface Env { DB:D1Database }
type AuditRow={id:number;created_at:string;actor_display_name:string|null;action:string;entity_type:string;entity_id:string|null;source:string|null;old_values:string|null;new_values:string|null};
const esc=(v:unknown)=>leadershipEsc(String(v??""));
const pretty=(v:string)=>v.replaceAll("."," ").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const detail=(r:AuditRow)=>{const parts=[] as string[];if(r.entity_type)parts.push(pretty(r.entity_type));if(r.entity_id)parts.push(`#${esc(r.entity_id)}`);if(r.source)parts.push(`via ${esc(r.source)}`);return parts.join(" · ")};
const page=async(req:Request,e:Env,rows:AuditRow[],q:string)=>{const shell=await leadershipHeader(req,e);return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Audit Log</title><style>:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at top,#17243d 0,#0c1220 45%,#090e18 100%);color:#eef3ff}h1{margin:0 0 8px;font-size:1.8rem}p{color:#b8c4d9;line-height:1.5}.toolbar{display:flex;gap:10px;margin:22px 0}.toolbar input{flex:1;min-width:0;padding:12px 14px;border:1px solid #34445f;border-radius:11px;background:#0e1626;color:#fff;font-size:.95rem}.toolbar button{padding:12px 18px;border:0;border-radius:11px;background:var(--accent);color:#fff;font-weight:800;cursor:pointer}.audit{border:1px solid #2b3850;border-radius:14px;overflow:hidden;background:#0e1626}.event{display:grid;grid-template-columns:170px minmax(180px,1fr) minmax(180px,1.25fr);gap:18px;padding:16px 18px;border-bottom:1px solid #223047}.event:last-child{border-bottom:0}.when{color:#90a0bb;font-size:.82rem}.action{font-weight:800}.actor{margin-top:5px;color:#aebddd;font-size:.86rem}.meta{color:#90a0bb;font-size:.86rem}.empty{padding:28px;text-align:center;color:#90a0bb}.count{color:#8292ae;font-size:.85rem;margin:0 0 10px}@media(max-width:760px){.event{grid-template-columns:1fr;gap:7px}.toolbar{display:block}.toolbar button{width:100%;margin-top:9px}}</style>${leadershipShellCss(shell.accent,shell.icon)}</head><body><main>${shell.html}<div><h1>Audit Log</h1><p>A searchable history of meaningful changes across the platform.</p></div><form class="toolbar" method="get" action="/leadership/audit"><input name="q" value="${esc(q)}" placeholder="Search action, person, item or source"><button>Search</button></form><p class="count">${rows.length} most recent matching event${rows.length===1?"":"s"}</p><div class="audit">${rows.length?rows.map(r=>`<div class="event"><div class="when">${esc(r.created_at)}</div><div><div class="action">${esc(pretty(r.action))}</div><div class="actor">${esc(r.actor_display_name||"System")}</div></div><div class="meta">${detail(r)}</div></div>`).join(""):`<div class="empty">No audit events matched that search.</div>`}</div></main></body></html>`};

export default {async fetch(req:Request,e:Env,ctx:ExecutionContext){const u=new URL(req.url);if(req.method!=="GET"||u.pathname!=="/leadership/audit")return (app as any).fetch(req,e,ctx);const actor=await playerActor(req,e as any);if(!actor)return Response.redirect(new URL("/login",req.url),302);if(!await playerPermitted(e as any,actor,"audit.view"))return new Response("Forbidden",{status:403});const q=(u.searchParams.get("q")||"").trim().slice(0,100);let sql="SELECT id,created_at,actor_display_name,action,entity_type,entity_id,source,old_values,new_values FROM audit_log",args:any[]=[];if(q){sql+=" WHERE action LIKE ? OR actor_display_name LIKE ? OR entity_type LIKE ? OR entity_id LIKE ? OR source LIKE ?";const like=`%${q}%`;args=[like,like,like,like,like]}sql+=" ORDER BY id DESC LIMIT 200";const result=await e.DB.prepare(sql).bind(...args).all<AuditRow>();return new Response(await page(req,e,result.results??[],q),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-frame-options":"DENY"}})}} satisfies ExportedHandler<Env>;
