import * as XLSX from "xlsx";
import app from "./navigation_polish";

interface Env { DB:D1Database; ASSETS:R2Bucket; APP_URL:string; DISCORD_CLIENT_ID:string; DISCORD_CLIENT_SECRET:string; DISCORD_BOT_TOKEN:string; SETUP_KEY:string; AUTH_SECRET:string; }
type Actor={id:number;display_name:string};
type Rank={rank_level:number;display_name:string};
type ImportRow={name:string;rank:number;base:number|null;strength:number|null;squad1:number|null;errors:string[]};
const SESSION_COOKIE="ap_session";
const esc=(v:string)=>v.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const cookie=(r:Request,n:string)=>{for(const p of(r.headers.get("cookie")??"").split(";")){const [x,...z]=p.trim().split("=");if(x===n)return z.join("=")}return null};
const b64=(b:Uint8Array)=>{let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")};
const hash=async(v:string)=>b64(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v))));
const actor=async(r:Request,e:Env)=>{const t=cookie(r,SESSION_COOKIE);if(!t)return null;return await e.DB.prepare(`SELECT a.id,a.display_name FROM sessions s JOIN accounts a ON a.id=s.account_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>CURRENT_TIMESTAMP AND a.is_active=1 AND a.approval_status='active' AND a.is_owner=1 LIMIT 1`).bind(await hash(t)).first<Actor>()};
const sameOrigin=(r:Request,e:Env)=>{const site=r.headers.get("sec-fetch-site");if(site==="same-origin"||site==="none")return true;const origin=r.headers.get("origin");if(!origin)return true;return new Set([new URL(r.url).origin,new URL(e.APP_URL).origin]).has(origin)};
const redirect=(u:string,r:Request)=>Response.redirect(new URL(u,r.url),302);
const normalize=(v:unknown)=>v instanceof Response?v:new Response(String(v??""),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}});
const getMax=async(e:Env)=>{const row=await e.DB.prepare("SELECT value FROM settings WHERE key='player_max_base_level'").first<{value:string}>();const n=Number(row?.value??35);return Number.isInteger(n)&&n>=1&&n<=999?n:35};
const getRanks=async(e:Env)=>{const r=await e.DB.prepare("SELECT rank_level,display_name FROM alliance_ranks ORDER BY rank_level").all<Rank>();return r.results??[]};
const parsePower=(v:unknown)=>{if(v===null||v===undefined||String(v).trim()==="")return null;if(typeof v==="number")return Number.isFinite(v)&&v>=0?Math.round(v):NaN;const s=String(v).trim().replaceAll(",","").replace(/\s+/g,"");const m=s.match(/^([0-9]+(?:\.[0-9]+)?)([KMB])?$/i);if(!m)return NaN;const mult=!m[2]?1:m[2].toUpperCase()==="K"?1e3:m[2].toUpperCase()==="M"?1e6:1e9;return Math.round(Number(m[1])*mult)};
const val=(o:Record<string,unknown>,names:string[])=>{const entries=Object.entries(o);for(const n of names){const hit=entries.find(([k])=>k.trim().toLowerCase()===n);if(hit)return hit[1]}return ""};
const parseRank=(raw:unknown,rs:Rank[])=>{const s=String(raw??"").trim();if(!s)return 1;const m=s.match(/^R?([1-5])$/i);if(m)return Number(m[1]);const byName=rs.find(x=>x.display_name.trim().toLowerCase()===s.toLowerCase());return byName?.rank_level??NaN};
const parseRows=async(e:Env,file:File)=>{if(file.size>5*1024*1024)throw new Error("File is larger than 5 MB.");const ext=file.name.toLowerCase();if(!ext.endsWith(".xlsx")&&!ext.endsWith(".csv"))throw new Error("Use an .xlsx or .csv file.");const wb=XLSX.read(await file.arrayBuffer(),{type:"array"});const sheet=wb.Sheets[wb.SheetNames[0]];if(!sheet)throw new Error("The spreadsheet has no readable worksheet.");const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:""});if(!raw.length)throw new Error("The spreadsheet contains no player rows.");if(raw.length>150)throw new Error("Import a maximum of 150 players at a time.");const max=await getMax(e),rs=await getRanks(e);const existing=(await e.DB.prepare("SELECT display_name FROM players WHERE is_active=1").all<{display_name:string}>()).results??[];const existingNames=new Set(existing.map(x=>x.display_name.trim().toLowerCase()));const seen=new Set<string>();return raw.map((o,i)=>{const name=String(val(o,["player name","name","player"])).trim(),rank=parseRank(val(o,["rank"]),rs),baseRaw=String(val(o,["base level","base","base size"])).trim(),base=baseRaw===""?null:Number(baseRaw),strength=parsePower(val(o,["strength","player power","total power","power"])),squad1=parsePower(val(o,["squad 1 power","squad1 power","squad 1 strength","squad1 strength"])),errors:string[]=[];if(!name)errors.push("Player Name is required");if(name.length>80)errors.push("Player Name is too long");if(!Number.isInteger(rank)||rank<1||rank>5)errors.push("Rank must be R1–R5");if(base!==null&&(!Number.isInteger(base)||base<1||base>max))errors.push(`Base Level must be 1–${max}`);if(strength!==null&&(!Number.isFinite(strength)||strength<0))errors.push("Strength is invalid");if(squad1!==null&&(!Number.isFinite(squad1)||squad1<0))errors.push("Squad 1 Power is invalid");const key=name.toLowerCase();if(name&&existingNames.has(key))errors.push("An active player with this name already exists");if(name&&seen.has(key))errors.push("Duplicate name in this import");if(name)seen.add(key);return{name,rank:Number.isFinite(rank)?rank:1,base:Number.isFinite(base as number)?base:null,strength:Number.isFinite(strength as number)?strength:null,squad1:Number.isFinite(squad1 as number)?squad1:null,errors}})};
const styles=`:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at top,#17243d 0,#0c1220 45%,#090e18 100%);color:#eef3ff;padding:24px}main{width:min(94vw,1120px);margin:28px auto;background:#151d2e;border:1px solid #2b3850;border-radius:20px;padding:30px}.adminbrand{display:flex;align-items:center;padding-bottom:18px;border-bottom:1px solid #2b3850;margin-bottom:24px}.adminbrand a{margin-left:auto;color:#aebddd;text-decoration:none;font-weight:700}.step{font-size:.82rem;text-transform:uppercase;letter-spacing:.08em;color:#8292ae;font-weight:800}h1{margin:8px 0}p{color:#b8c4d9;line-height:1.5}.card{padding:18px;border-radius:14px;background:#0e1626;border:1px solid #2b3850;margin-top:18px}.button,button{display:inline-block;border:0;border-radius:10px;background:#5865f2;color:#fff;text-decoration:none;font-weight:800;padding:11px 14px;cursor:pointer}.secondary{background:#26344d}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}input[type=file]{width:100%;padding:12px;border:1px solid #3a4964;border-radius:10px;background:#0e1626;color:#fff}.hint{font-size:.82rem;color:#8292ae;margin-top:8px}.notice{padding:12px 14px;border-radius:10px;background:#24191c;color:#ffd5dc;margin:16px 0}.ok{background:#14251d;color:#baf4cf}.tablewrap{overflow:auto;margin-top:18px}table{width:100%;border-collapse:collapse;min-width:760px}th,td{text-align:left;padding:10px;border-bottom:1px solid #223047;font-size:.88rem}th{color:#90a0bb}.bad{color:#ffb3bf}.good{color:#87e6a7}@media(max-width:650px){body{padding:12px}main{padding:20px;margin:8px auto}.actions .button,.actions button{width:100%;text-align:center}}`;
const page=(body:string)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Import Players</title><style>${styles}</style></head><body><main><div class="adminbrand"><strong>Player Management</strong><a href="/players">← Players</a></div>${body}</main></body></html>`;
const importPage=(message="")=>new Response(page(`<div class="step">Players</div><h1>Import players</h1><p>Upload an existing roster from Excel or CSV. You will get a preview before anything is saved.</p>${message?`<div class="notice">${esc(message)}</div>`:""}<div class="card"><form method="post" action="/players/import/preview" enctype="multipart/form-data"><label><strong>Spreadsheet</strong></label><input type="file" name="file" accept=".xlsx,.csv" required><div class="hint">Columns: Player Name, Rank, Base Level, Strength, Squad 1 Power. Only Player Name is required; blank Rank defaults to R1.</div><div class="actions"><button type="submit">Preview import</button><a class="button secondary" href="/players/import/template.csv">Download Import Template</a></div></form></div>`),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}});
const previewPage=(rows:ImportRow[])=>{const bad=rows.some(x=>x.errors.length),trs=rows.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name||"—")}</td><td>R${x.rank}</td><td>${x.base??"—"}</td><td>${x.strength??"—"}</td><td>${x.squad1??"—"}</td><td class="${x.errors.length?"bad":"good"}">${x.errors.length?esc(x.errors.join("; ")):"Ready"}</td></tr>`).join("");const payload=esc(JSON.stringify(rows.map(({errors,...x})=>x)));return new Response(page(`<div class="step">Players</div><h1>Import preview</h1><p>Nothing has been saved yet. Check the rows below before committing the import.</p><div class="notice ${bad?"":"ok"}">${bad?"Fix the highlighted rows in the spreadsheet and upload it again.":`${rows.length} player${rows.length===1?"":"s"} ready to import.`}</div><div class="tablewrap"><table><thead><tr><th>#</th><th>Player Name</th><th>Rank</th><th>Base</th><th>Strength</th><th>Squad 1 Power</th><th>Status</th></tr></thead><tbody>${trs}</tbody></table></div><div class="actions"><a class="button secondary" href="/players/import">Choose another file</a>${bad?"":`<form method="post" action="/players/import/commit"><textarea name="payload" hidden>${payload}</textarea><button type="submit">Import ${rows.length} players</button></form>`}</div>`),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}})};
const audit=async(e:Env,a:Actor,action:string,id:string,values:unknown)=>e.DB.prepare("INSERT INTO audit_log (public_id,actor_account_id,actor_display_name,action,entity_type,entity_id,source,new_values) VALUES (?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),a.id,a.display_name,action,"player",id,"players.import",JSON.stringify(values)).run();
const commit=async(r:Request,e:Env,a:Actor)=>{if(!sameOrigin(r,e))return new Response("Forbidden",{status:403});const f=await r.formData();let rows:Omit<ImportRow,"errors">[];try{rows=JSON.parse(String(f.get("payload")||"[]"))}catch{return importPage("The import preview expired or was invalid. Please upload the spreadsheet again.")}if(!Array.isArray(rows)||!rows.length||rows.length>150)return importPage("The import preview was invalid. Please upload the spreadsheet again.");const max=await getMax(e),existing=(await e.DB.prepare("SELECT display_name FROM players WHERE is_active=1").all<{display_name:string}>()).results??[],used=new Set(existing.map(x=>x.display_name.toLowerCase()));for(const row of rows){const name=String(row.name||"").trim(),rank=Number(row.rank),base=row.base===null?null:Number(row.base),strength=row.strength===null?null:Number(row.strength),s1=row.squad1===null?null:Number(row.squad1);if(!name||name.length>80||used.has(name.toLowerCase())||!Number.isInteger(rank)||rank<1||rank>5||(base!==null&&(!Number.isInteger(base)||base<1||base>max))||(strength!==null&&(!Number.isInteger(strength)||strength<0))||(s1!==null&&(!Number.isInteger(s1)||s1<0)))return importPage(`Import stopped before saving because ${name||"a row"} is no longer valid.`);used.add(name.toLowerCase())}let count=0;for(const row of rows){const out=await e.DB.prepare("INSERT INTO players (display_name,rank,base_level,player_power,is_active) VALUES (?,?,?,?,1) RETURNING id").bind(row.name,row.rank,row.base,row.strength).first<{id:number}>();if(!out?.id)throw new Error("Player insert failed");await e.DB.prepare("INSERT INTO player_rank_history (player_id,old_rank,new_rank,changed_by_account_id,note) VALUES (?,NULL,?,?,?)").bind(out.id,row.rank,a.id,"Player imported").run();if(row.squad1!==null)await e.DB.prepare("INSERT INTO player_squads (player_id,squad_number,power) VALUES (?,1,?)").bind(out.id,row.squad1).run();await audit(e,a,"player.imported",String(out.id),{display_name:row.name,rank:row.rank,base_level:row.base,strength:row.strength,squad_1_power:row.squad1});count++}await audit(e,a,"players.bulk_imported","bulk",{count});return redirect(`/players?imported=${count}`,r)};
export default {async fetch(request:Request,env:Env):Promise<Response>{const u=new URL(request.url),p=u.pathname;if(p.startsWith("/players/import")){const a=await actor(request,env);if(!a)return redirect("/login",request);if(p==="/players/import"&&request.method==="GET")return importPage();if(p==="/players/import/template.csv"&&request.method==="GET")return new Response("Player Name,Rank,Base Level,Strength,Squad 1 Power\nExample Player,R1,35,120000000,42000000\n",{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":"attachment; filename=player-import-template.csv"}});if(p==="/players/import/preview"&&request.method==="POST"){if(!sameOrigin(request,env))return new Response("Forbidden",{status:403});const f=await request.formData(),file=f.get("file");if(!(file instanceof File))return importPage("Choose an Excel or CSV file first.");try{return previewPage(await parseRows(env,file))}catch(err){return importPage(err instanceof Error?err.message:"The spreadsheet could not be read.")}}if(p==="/players/import/commit"&&request.method==="POST")return commit(request,env,a);return new Response("Not found",{status:404})}const res=normalize(await (app as any).fetch(request,env));if(request.method==="GET"&&p==="/players"&&res.headers.get("content-type")?.includes("text/html")){let h=await res.text();h=h.replace('<a class="button" href="/players/new">+ Add player</a>','<div style="display:flex;gap:10px;flex-wrap:wrap"><a class="button secondary" href="/players/import">Import players</a><a class="button" href="/players/new">+ Add player</a></div>');const imported=u.searchParams.get("imported");if(imported)h=h.replace('<div class="toolbar">',`<div class="notice">${esc(imported)} players imported.</div><div class="toolbar">`);return new Response(h,{status:res.status,statusText:res.statusText,headers:res.headers})}return res}} satisfies ExportedHandler<Env>;
