import app from "./player_management_fixed";

interface Env { DB:D1Database; ASSETS:R2Bucket; APP_URL:string; DISCORD_CLIENT_ID:string; DISCORD_CLIENT_SECRET:string; DISCORD_BOT_TOKEN:string; SETUP_KEY:string; AUTH_SECRET:string; }
type Actor={id:number;display_name:string};
type Player={id:number;display_name:string;rank:number;base_level:number|null;is_active:number;joined_at:string|null;left_at:string|null;birthday_month:number|null;birthday_day:number|null};
const SESSION_COOKIE="ap_session";
const cookie=(r:Request,n:string)=>{for(const p of(r.headers.get("cookie")??"").split(";")){const [x,...z]=p.trim().split("=");if(x===n)return z.join("=")}return null};
const b64=(b:Uint8Array)=>{let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")};
const hash=async(v:string)=>b64(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v))));
const actor=async(r:Request,e:Env)=>{const t=cookie(r,SESSION_COOKIE);if(!t)return null;return await e.DB.prepare(`SELECT a.id,a.display_name FROM sessions s JOIN accounts a ON a.id=s.account_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>CURRENT_TIMESTAMP AND a.is_active=1 AND a.approval_status='active' AND a.is_owner=1 LIMIT 1`).bind(await hash(t)).first<Actor>()};
const sameOrigin=(r:Request,e:Env)=>{const site=r.headers.get("sec-fetch-site");if(site==="same-origin"||site==="none")return true;const origin=r.headers.get("origin");if(!origin)return true;const allowed=new Set([new URL(r.url).origin,new URL(e.APP_URL).origin]);return allowed.has(origin)};
const redirect=(u:string,r:Request)=>Response.redirect(new URL(u,r.url),302);
const getMaxLevel=async(e:Env)=>{const row=await e.DB.prepare("SELECT value FROM settings WHERE key='player_max_base_level'").first<{value:string}>();const n=Number(row?.value??35);return Number.isInteger(n)&&n>=1&&n<=999?n:35};
const loadPlayer=async(e:Env,id:number)=>await e.DB.prepare("SELECT id,display_name,rank,base_level,is_active,joined_at,left_at,birthday_month,birthday_day FROM players WHERE id=?").bind(id).first<Player>();
const audit=async(e:Env,a:Actor,action:string,id:number,values:unknown)=>e.DB.prepare("INSERT INTO audit_log (public_id,actor_account_id,actor_display_name,action,entity_type,entity_id,source,new_values) VALUES (?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),a.id,a.display_name,action,"player",String(id),"players",JSON.stringify(values)).run();
const parseBirthday=(value:string)=>{const m=value.trim().match(/^(\d{1,2})\/(\d{1,2})$/);if(!m)return{day:null,month:null,valid:value.trim()===""};const day=Number(m[1]),month=Number(m[2]);if(!Number.isInteger(day)||!Number.isInteger(month)||month<1||month>12||day<1||day>31)return{day:null,month:null,valid:false};const d=new Date(Date.UTC(2000,month-1,day));return{day,month,valid:d.getUTCMonth()===month-1&&d.getUTCDate()===day}};
const readForm=async(r:Request,e:Env)=>{const f=await r.formData(),name=String(f.get("display_name")||"").trim(),rank=Number(f.get("rank")||1),baseRaw=String(f.get("base_level")||"").trim(),joined=String(f.get("joined_at")||"").trim(),left=String(f.get("left_at")||"").trim(),birthdayRaw=String(f.get("birthday")||"").trim(),bmRaw=String(f.get("birthday_month")||"").trim(),bdRaw=String(f.get("birthday_day")||"").trim(),max=await getMaxLevel(e),base=baseRaw?Number(baseRaw):null,parsed=birthdayRaw!==""?parseBirthday(birthdayRaw):null,bm=parsed?parsed.month:(bmRaw?Number(bmRaw):null),bd=parsed?parsed.day:(bdRaw?Number(bdRaw):null),birthdayValid=parsed?parsed.valid:true;const valid=!!name&&name.length<=80&&Number.isInteger(rank)&&rank>=1&&rank<=5&&(base===null||(Number.isInteger(base)&&base>=1&&base<=max))&&birthdayValid&&(bm===null||(Number.isInteger(bm)&&bm>=1&&bm<=12))&&(bd===null||(Number.isInteger(bd)&&bd>=1&&bd<=31));return{valid,name,rank,base,joined:joined||null,left:left||null,bm,bd}};
const createPlayer=async(r:Request,e:Env)=>{const a=await actor(r,e);if(!a)return redirect("/login",r);if(!sameOrigin(r,e))return new Response("Forbidden",{status:403});const v=await readForm(r,e);if(!v.valid)return redirect("/players?error=invalid",r);try{const out=await e.DB.prepare("INSERT INTO players (display_name,rank,base_level,is_active,joined_at,left_at,birthday_month,birthday_day) VALUES (?,?,?,?,?,?,?,?)").bind(v.name,v.rank,v.base,v.left?0:1,v.joined,v.left,v.bm,v.bd).run();const id=Number(out.meta.last_row_id);await e.DB.prepare("INSERT INTO player_rank_history (player_id,old_rank,new_rank,changed_by_account_id,note) VALUES (?,NULL,?,?,?)").bind(id,v.rank,a.id,"Player created").run();await audit(e,a,"player.created",id,{display_name:v.name,rank:v.rank,base_level:v.base});return redirect(`/players/${id}?saved=1`,r)}catch{return redirect("/players?error=duplicate",r)}};
const updatePlayer=async(r:Request,e:Env,id:number)=>{const a=await actor(r,e);if(!a)return redirect("/login",r);if(!sameOrigin(r,e))return new Response("Forbidden",{status:403});const old=await loadPlayer(e,id);if(!old)return new Response("Not found",{status:404});const v=await readForm(r,e);if(!v.valid)return redirect(`/players/${id}?error=invalid`,r);try{await e.DB.prepare("UPDATE players SET display_name=?,rank=?,base_level=?,is_active=?,joined_at=?,left_at=?,birthday_month=?,birthday_day=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(v.name,v.rank,v.base,v.left?0:old.is_active,v.joined,v.left,v.bm,v.bd,id).run();if(v.rank!==old.rank)await e.DB.prepare("INSERT INTO player_rank_history (player_id,old_rank,new_rank,changed_by_account_id,note) VALUES (?,?,?,?,?)").bind(id,old.rank,v.rank,a.id,"Rank changed in player profile").run();await audit(e,a,"player.updated",id,{display_name:v.name,rank:v.rank,base_level:v.base,joined_at:v.joined,left_at:v.left,birthday_month:v.bm,birthday_day:v.bd});return redirect(`/players/${id}?saved=1`,r)}catch{return redirect(`/players/${id}?error=duplicate`,r)}};
const decorateForm=async(res:Response,e:Env,isNew:boolean)=>{if(!res.headers.get("content-type")?.includes("text/html"))return res;let h=await res.text();const max=await getMaxLevel(e);h=h.replace('<div class="crumb"><a href="/">Leadership Console</a></div>','<div class="crumb"><a href="/players">← Players</a></div>').replace('<div class="crumb"><a href="/">← Leadership Console</a></div>','<div class="crumb"><a href="/players">← Players</a></div>');const m=h.match(/<input name="base_level"[^>]*value="([^"]*)"[^>]*>/),current=m?.[1]??"";if(m){const options=['<option value="">Not set</option>',...Array.from({length:max},(_,i)=>{const n=String(i+1);return `<option value="${n}"${n===current?' selected':''}>${n}</option>`})].join("");h=h.replace(m[0],`<select name="base_level">${options}</select>`)}if(isNew){h=h.replace(/(<select name="rank">)([\s\S]*?)(<\/select>)/,(all,start,opts,end)=>{let clean=String(opts).replace(/ selected/g,"");clean=clean.replace(/<option value="1"/, '<option value="1" selected');return start+clean+end})}const bm=h.match(/<select name="birthday_month">[\s\S]*?<\/select>/),bd=h.match(/<input name="birthday_day"[^>]*value="([^"]*)"[^>]*>/);if(bm&&bd){const monthSelected=bm[0].match(/<option value="(\d+)" selected/),day=bd[1]||"",month=monthSelected?.[1]||"",value=day&&month?`${String(day).padStart(2,"0")}/${String(month).padStart(2,"0")}`:"";const birthday=`<div><label>Birthday</label><input name="birthday" type="text" inputmode="numeric" maxlength="5" placeholder="DD/MM" pattern="(?:0?[1-9]|[12][0-9]|3[01])\/(?:0?[1-9]|1[0-2])" value="${value}"><div class="hint">Day and month only · DD/MM</div></div>`;const birthdayBlock=new RegExp(`<div><label>Birthday month<\\/label>${bm[0].replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}<\\/div><div><label>Birthday day<\\/label>${bd[0].replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}<\\/div>`);h=h.replace(birthdayBlock,birthday+'<div></div>')}return new Response(h,{status:res.status,statusText:res.statusText,headers:res.headers})};
export default {async fetch(request:Request,env:Env):Promise<Response>{const u=new URL(request.url),p=u.pathname;if(p==="/players/create"&&request.method==="POST")return createPlayer(request,env);const m=p.match(/^\/players\/(\d+)\/update$/);if(m&&request.method==="POST")return updatePlayer(request,env,Number(m[1]));const res=await (app as any).fetch(request,env);if(res instanceof Response&&request.method==="GET"&&(p==="/players/new"||/^\/players\/\d+$/.test(p)))return decorateForm(res,env,p==="/players/new");return res}} satisfies ExportedHandler<Env>;
