import app from "./security_access";
interface Env { DB:D1Database; ASSETS:R2Bucket; APP_URL:string; DISCORD_CLIENT_ID:string; DISCORD_CLIENT_SECRET:string; DISCORD_BOT_TOKEN:string; SETUP_KEY:string; AUTH_SECRET:string; }
type Branding={brand_main_logo?:string;brand_login_logo?:string;brand_favicon?:string;footer_text?:string;theme_accent?:string;theme_icon?:string};
const esc=(v:string)=>v.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const withHtml=(res:Response,html:string)=>{const headers=new Headers(res.headers);headers.delete("content-length");return new Response(html,{status:res.status,statusText:res.statusText,headers})};
const getBranding=async(env:Env)=>{const keys=['brand_main_logo','brand_login_logo','brand_favicon','footer_text','theme_accent','theme_icon'],q=await env.DB.prepare(`SELECT key,value FROM settings WHERE key IN (${keys.map(()=>'?').join(',')})`).bind(...keys).all<{key:string;value:string}>();return Object.fromEntries((q.results??[]).map(x=>[x.key,x.value])) as Branding};
const assetUrl=(key?:string)=>key?`/assets/${encodeURIComponent(key)}`:"";
const polishPending=async(res:Response,env:Env)=>{if(!res.headers.get("content-type")?.includes("text/html"))return res;let html=await res.text();const alliance=await env.DB.prepare("SELECT name,tag,server_number FROM alliance WHERE id=1 LIMIT 1").first<{name:string;tag:string|null;server_number:number|null}>().catch(()=>null),s=await getBranding(env).catch(()=>({} as Branding)),name=alliance?.name||"Alliance",identity=`${alliance?.tag?`[${esc(alliance.tag)}] · `:""}${alliance?.server_number?`Server #${alliance.server_number}`:""}`,logo=s.brand_login_logo||s.brand_main_logo,accent=/^#[0-9a-fA-F]{6}$/.test(s.theme_accent||"")?s.theme_accent!:"#5865f2",icon=/^#[0-9a-fA-F]{6}$/.test(s.theme_icon||"")?s.theme_icon!:"#aebddd",logoHtml=logo?`<img src="${assetUrl(logo)}" alt="${esc(name)}">`:`<span class="brandfallback">${esc((alliance?.tag||name).slice(0,5).toUpperCase())}</span>`;html=html.replace('<div class="duck">🦆</div>',`<div class="pendingbrand">${logoHtml}</div>`);html=html.replace('<a href="/auth/logout">Sign out</a>',`<a class="pendingSignout" href="/auth/logout">Sign out</a><div class="pendingfooter"><strong>${esc(name)}</strong><span>${s.footer_text?.trim()?esc(s.footer_text.trim()):identity}</span></div>`);if(s.brand_favicon)html=html.replace('</title>',`</title><link rel="icon" href="${assetUrl(s.brand_favicon)}">`);html=html.replace('</head>',`<style>:root{--ap-accent:${accent};--ap-icon:${icon}}.duck{display:none}.pendingbrand{width:92px;height:92px;margin:0 auto 18px;display:flex;align-items:center;justify-content:center;border-radius:20px;overflow:hidden}.pendingbrand img{display:block;width:100%;height:100%;object-fit:contain}.brandfallback{width:100%;height:100%;display:flex;align-items:center;justify-content:center;border-radius:20px;background:var(--ap-accent);font-weight:900}.pendingSignout{display:inline-block;margin-top:4px;padding:12px 22px;border-radius:11px;background:var(--ap-accent);color:#fff!important;font-weight:800;text-decoration:none}.pendingfooter{display:flex;justify-content:space-between;gap:14px;margin-top:28px;padding-top:17px;border-top:1px solid #2b3850;color:#8292ae;font-size:.78rem;text-align:left}.pendingfooter strong{color:var(--ap-icon)}.pendingfooter span{text-align:right}@media(max-width:650px){.pendingfooter{display:block;text-align:center}.pendingfooter span{display:block;text-align:center;margin-top:5px}}</style></head>`);return withHtml(res,html)};
export default {async fetch(request:Request,env:Env):Promise<Response>{const url=new URL(request.url);if(url.pathname==="/security-access")return Response.redirect(new URL("/security/access",request.url),302);const result=await(app as any).fetch(request,env);if(!(result instanceof Response)){if(typeof result==="string")return new Response(result,{headers:{"content-type":"text/html; charset=utf-8"}});throw new TypeError("Worker handler did not return a Response")};if(["/pending","/access-declined","/access-blocked"].includes(url.pathname))return polishPending(result,env);return result}} satisfies ExportedHandler<Env>;
